### ISSUE TITLE
Apply for vendor account. Allow applicants to enter description and upload logo

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#103]
Currently we allow user to enter only email and name

let's discuss it first

**Comment by SilhouetteBS** [comment]
If the ability to include address information and other vendor information, it would be better if not only they could enter their email, name, description, and logo, but any of the information that could be input for a vendor. This would help the onboarding process of vendors because a store owner may be able to get all necessary information from the Vendor Sign Up form.
