### ISSUE TITLE
PayPal Standard: Set no_shipping option to 1 always

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#1034]
When shipping is required, Nopcommerce sets the no_shipping option to 2. This causes PayPal to require the user to specify a shipping address. A user might enter a different shipping address to what they entered when placing their order through NopCommerce, then they will be very unhappy when their order doesn't show up to that address becuase NopCommerce effectively disregards the new shipping address. 

More information about no_shipping=2 here 
https://developer.paypal.com/webapps/developer/docs/classic/paypal-payments-standard/integration-guide/Appx_BillingShippingAddress/ 

Suggested fix: 
Recommend always setting no_shipping to 1 or providing an option. 

My code:

```
    //this causes problems, changed to 1 for all orders
    //if (postProcessPaymentRequest.Order.ShippingStatus != ShippingStatus.ShippingNotRequired)
    //    builder.AppendFormat("&no_shipping=2", new object[0]);
    //else
    //    builder.AppendFormat("&no_shipping=1", new object[0]);

    builder.AppendFormat("&no_shipping=1", new object[0]);
```

Let's make it configurable

**Comment by kwerty** [comment]
This was an issue I submitted
https://nopcommerce.codeplex.com/workitem/12134

If no_shipping is set to 1 then the payment will not be eligible for PayPal Seller Protection. However, PayPal Seller Protection is not available in many countries, so it would still be good to have an option to configure no_shipping in the PayPal Standard configuration page.

There is no point in asking my customers for a shipping address since they have already entered it on the Shipping address page, and since requiring an address to be entered into PayPal provides no additional benefit.

I propose the following option text -

- [ ] Require user to specify shipping address during PayPal checkout (Warning: Payments without shipping address not eligible for PayPal Seller Protection

**Comment by RomanovM** [comment]
Solved in https://github.com/nopSolutions/nopCommerce/commit/20ebb2d443476b56b54e0c55187f36082e3aa2e8
