### ISSUE TITLE
Recurring Payments - should be processed automatically even if 'manual credit card' is payment type - the invoice should be generated on the due date

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#1077]
To find/process recurring payments with 'manual billing' is quite a lengthy process - imagine even you just had 100 recurring payments - you would need to search through the list every day to look for orders marked with a date when you need to process - then you need to open that payment, click 'history' tab then click 'process next payment'. 
it's too prone to user error. 

I'm using recurring payments to generate invoices - i'm using 'manual credit card' as a payment method which means the orders are not processed automatically which i think is a problem because i often forget to do it on the due date ( then when i do, the order date is the processing date, not actually the date that the recurring payment was due ) 

i think the order should be generated automatically (so it's in the database just as though a customer had just placed it - then we mark the order as paid while we 'manage order' - we have to do this manually after the order is generated anyway ) 

Maybe the syntax is misleading, because it's not simply a recurring payment, it is actually a recurring order, more specifically it is new order made on a recurring basis

**Comment by 3dmerchant** [comment]
To help developers looking at this for specifications, confirm:
You need a recurring order module (physical product is shipped):  
- create a repeat sales order on a specific schedule you set (every 30 days, for example) 
- collect payment on same day as ship, or select days in advance (in case card fails)?
- if payment fails, what happens? Someone has to think this through. 

With respect to payment, the module needs to create a token for subsequent recurring billing. If using stored tokens, and the payment gateway is sending the transaction type as MANUAL instead of REPEAT/RECURRING SALE, then you're at risk of chargeback because it's the wrong sale type.

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box because it's a too specific requirement
