### ISSUE TITLE
Make PayPal Express plugin available out of the box

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1136]
Let's think about it - http://www.nopcommerce.com/p/1149/paypal-express-payment-plugin.aspx

**Comment by kryptoncodex** [comment]
If you're going to do it please make sure the option to prevent customers from selecting an address from their PayPal address book is included. I was looking at the PayPal Express API and there is an option setting to do so. Without this option customers can select an address and if that address returns a 10 digit US zip code it doesn't match a lot of customers 5 digit zip codes in their sales tax database table at which point no sales tax is charged. We cannot use PayPal Express for that reason because all the current PayPal Express plugins do not have that feature implemented.
