### ISSUE TITLE
Page class on <html>

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1338]
Source: http://www.nopcommerce.com/boards/t/41427/page-class-on-html.aspx and http://www.nopcommerce.com/boards/t/41427/page-class-on-html.aspx#166532

TODO: discuss class names first

**Comment by Al3ksBG** [comment]
By the way, putting this class on the body is also completely acceptable. It all comes down to personal preference. The difference for me is that if you put it on the html element and you want to style the body you would have to specify it like this ".current-page-template > body" instead of ".current-page-template". The idea about putting the class on the html element is to be at the most top level of the DOM.
