### ISSUE TITLE
Error log in text file when database connection goes wrong

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1369]
Source: http://www.nopcommerce.com/boards/t/41839/error-log-in-text-file-when-database-connection-goes-wrong.aspx and http://www.nopcommerce.com/boards/t/41600/ef-validation-errors-with-context-are-not-logged.aspx

**Comment by odises** [comment]
I think filesystem is preferred for logs instead of RDBMS.
For example Web Servers like IIS, Apache, etc save their access and error logs in files instead of RDBMS by default.
Maybe people asks How to log filesystem error if it fails?
And it is quite true, but if that fails, there is more chances that your DB is inaccessible as well.
For putting it all together:

1. Too many things can fail with the database, and logging this failures is important too.
2. Also there is an extra layer between our application and the DB (ORM like EntityFramework) that it has its probability and chances of error and failure.
3. Unless you have a database system allowing autonomous transactions (or no transactions at all), logging would require a separate connection so a rollback or commit in logging doesn’t interfere with rollback or commit in the application.
4. Many things worth logging happen during startup, i.e. possibly before the database connection has been established.

I believe using logging frameworks like Log4net or NLog is more safe solution for logging.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
