### ISSUE TITLE
OrderTotal Rounding

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1424]
Would be nice to have the ability to configure OrderTotal rounding.
Eg. in Sweden decimals (ören/cents) are not used anymore, and when using discount codes with percentage, the order total get decimals.

 i want the order totals (only) to look like this:
Sub-total: 10,00
Tax         2,50
## Rounding:   0,50

Total:     13,00

See discussion at http://www.nopcommerce.com/boards/t/41958/suggestion-ordertotal-rounding.aspx (waiting for reply)

and https://en.wikipedia.org/wiki/Cash_rounding

See related work item - https://github.com/nopSolutions/nopCommerce/issues/677

Contribution: https://github.com/nopSolutions/nopCommerce/pull/1983 and https://github.com/nopSolutions/nopCommerce/pull/1992

**Comment by mfalkao** [comment]
My I suggest a slightly different implementation.
Instead of using the suggested RoundingType it would be sufficient to state the precision as decimal (like 0.01, 0.05, 0.5) and a rounding type the states midpoint rounding (to even, AwayFromZero).

Rounding could then be implemented as:
v: the value to round
p: precision as decimal
m: midpoint rounding

q = Math.Truncate(v/p);
r = Math.Round(v/p - q, p);
result = (q + r) * p;

Furthermore I would suggest to have two rounding settings per currency. One for Price and one for Amount.

**Comment by skoshelev** [comment]
Closed #1424
