### ISSUE TITLE
Further admin area re-design and simplify changes (UI/UX changes)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1647]
For example, http://www.nopcommerce.com/boards/t/43350/nopcommerce-380-beta-released-please-share-your-impressions.aspx?p=15#172628

Other ideas? Your suggestions?

some other related work items - https://github.com/nopSolutions/nopCommerce/issues/1842

Let's also think how to simplify product details page. Right now "Info" tab looks really huge. Also for example, display LxWxH in one row (like opencart does). Some other suggestions about this page at https://github.com/nopSolutions/nopCommerce/issues/1996 (see comments)

![735a68de54](https://cloud.githubusercontent.com/assets/16681184/23784928/0005e61e-0576-11e7-8b85-449c75119d06.jpg)
![4796741f30](https://cloud.githubusercontent.com/assets/16681184/23784927/fff7730e-0575-11e7-99d3-fc44f8f02259.jpg)

**Comment by eadameg** [comment]
In configuration>settings create a new section "Administration Settings" for values such as adminareasettings.defaultgridpagesize, adminareasettings.hideadvertisementsonadminarea, etc.
This section may include other settings like catalog default settings such as catalogsettings.defaultcategorypagesizeoptions, catalogsettings.defaultmanufacturerpagesize, etc. (otherwise they should be included in Advanced view for Catalog Settings)

**Comment by eadameg** [comment]
Automatically change adminareasettings.defaultgridpagesize when the user selects another grid page size from the drop-down box, because is annoying, when, for instance, the administrator is updating a catalog or orders with many records selects grid size 100 and then he edits one and goes back to the listing the size is back again to the 15 default.

**Comment by eadameg** [comment]
1. Bulk editing for Categories and Manufacturers for main fields such as name, published/unpublished and order.

2. In Products Bulk Edit add more columns and let the user hide some of them This could be done in Administration Settings commented above

**Comment by eadameg** [comment]
Define more configurable default values for Products/Categories/Manufacturers such as:
For products:
  "Set Show on HomePage True"
  "Set Show on HomePage False"
  "Set Published"
  "Set Unpublished"
  "Set Mark as New True"
  "Set Mark as New False"
  "Set Disable Buy Button True"
  "Set Disable Buy Button False"

**Comment by eadameg** [comment]
In regard to my previous comment, I just figured out that is not necessary to have defaults for products, since the Copy makes redundant

**Comment by AndreiMaz** [comment]
done now. one more task - https://github.com/nopSolutions/nopCommerce/issues/3666
