### ISSUE TITLE
Add caching of some entities in admin area

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#173]
For example, product list page could be slow if a store owner has 100K categories or manufacturers. Although it's VERY rare case 

We already have support for category caching. Let's think about support for manufacturers, vendors 

Source: http://www.nopcommerce.com/boards/t/35960/listing-all-productsmanage-products-under-admin-panel-is-very-slow.aspx

**Comment by ArturAlekseev** [comment]
I have >10k categories now. First i'v added caching. But it does not solve all problems.
Because even if they are cached they are all transferred in response (html) and its a huge data to transfer with each request. Also kendo ui dropdownlist that is used everywhere to add/select category (except for product list page) can't manage so many of them.
I think the only reasonable and fast solution is on categories list page add ability to show category id (i'v made it to show selected category id in additional field under the table). And then everywhere else I change dropdown list to EditorFor (so that user just add categoryid).
Its easy to have 2 windows opened in explorer where you can look category id on one page and enter it on another. And what is more important is that it is very fast.

**Comment by ArturAlekseev** [comment]
Adding caching does not solve the problem fully.
If we have > 1000 categories, then even if they are cached HTML size is very big and badly loaded by browsers (especially mobile). Not counting that its hard to select needed one from such a long list.
Maybe a view design should be different when categories number is greater than some number.

**Comment by AndreiMaz** [comment]
@ArturAlekseev there's a separate task for user-friendly selection - https://github.com/nopSolutions/nopCommerce/issues/1892
