### ISSUE TITLE
Further re-design (simplify) product details page

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1996]
Let's think how we can make it simpler. Right now "Info" tab looks really huge

For example, display LxWxH in one row (like opencart does)

Your suggestions?

**Comment by oumiller21** [comment]
I would also like to include simplifying the product details page by moving the inventory management to it's own tab. We use the Track Inventory > Use Multiple Warehouses feature and we have roughly 30 warehouse locations. Even though products may only span 5 or 6 warehouses, the main tab gets cluttered up pretty quickly with all of the warehouses. Moving the inventory management to a separate tab or even managing it in it's own area would make things much easier to read. Thoughts?

**Comment by eadameg** [comment]
>  Right now "Info" tab looks really huge

Not a big problem because it only looks huge when in Advance mode. 

> I would also like to include simplifying the product details page by moving the inventory management to it's own tab.

Maybe I would just leave Inventory Method and Stock Quantity in info and have the rest in a separate tab "Advance inventory". Maybe another tab "Other Mappings" for Manufacturers, Related Products and Cross sells

**Comment by infinito62** [comment]
More important, reintroduce Category Display order.
Excuse me, but why don't use the grid as related or cross sell products? Behaviour is the same. Categories are not tags nor stores, just stick to them: are of greatest importance for showcasing products.

**Comment by AndreiMaz** [comment]
@infinito62 we think it's more user-friendly. Furthermore, you still can manage "display order" and "is featured" properties right on a category details page

**Comment by infinito62** [comment]
Hi Andrei,
I understand your point of you - as a developer.
In this case mine is from a user.
If I have to switch back and forth from product page to categories I'll become crazy.
Anyway, let's strike a happy medium. Hyperlink category sticks so at least user can open in a new window the categories and try to search the product involved. Using CTRL + F of the browser, as there's no filter in the category product page - there are sometimes more than 200 products to search into.
Believe me, it's not a really great idea this system, it's a real waste of time.

**Comment by eadameg** [comment]
In configuration>settings create a new section "Administration Settings" for values such as adminareasettings.defaultgridpagesize, adminareasettings.hideadvertisementsonadminarea, etc. 
This section may  include other settings  like catalog  default settings such as catalogsettings.defaultcategorypagesizeoptions, catalogsettings.defaultmanufacturerpagesize, etc. (otherwise they should be included in Advanced view for Catalog Settings)

**Comment by eadameg** [comment]
Automatically change adminareasettings.defaultgridpagesize when the user selects another grid page size from the drop-down box, because is annoying, when, for instance, the administrator is updating a catalog or orders with many records selects grid size 100  and then he edits one and goes back to the listing the size is back again to the 15 default.

**Comment by tigran-avdalyan** [comment]
Product discription, specification, .….,    View in Tab mode

**Comment by AndreiMaz** [comment]
moved to https://github.com/nopSolutions/nopCommerce/issues/1647
