### ISSUE TITLE
Category/manufacturer import (with pictures) bug

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2077]
Value cannot be null. Parameter name: picture

But Parameter name: picture have a value

C:\inetpub\wwwroot\MYSYTE\content\images\manufacturers\logo.jpg

in settings Media setting
Pictures are stored into...:    file system

**Comment by skoshelev** [comment]
@tigran-avdalyan I didn't find a way to repeat this error. Can you attach the full StackTrace of this error?

**Comment by ssamartzis** [comment]
Hello, the issue exists and its very easy to recreate.
Just try to update the manufacturers from an excel file that has the Picture column filed  with a picture that exist in a directory on the server nopcommerce is running from.
It will throw an error:
System.ArgumentNullException: Value cannot be null. Parameter name: picture at Nop.Services.Media.PictureService.LoadPictureBinary(Picture picture, Boolean fromDb) at Nop.Services.ExportImport.ImportManager.LoadPicture(String picturePath, String name, Nullable`1 picId) at Nop.Services.ExportImport.ImportManager.ImportManufacturersFromXlsx(Stream stream) at Nop.Admin.Controllers.ManufacturerController.ImportFromXlsx()
When you don't have a Picture or the picture name is wrong (does not exist) then no error happens.
This is very critical since you cannot update (mass) manufacturers with pictures.

**Comment by skoshelev** [comment]
@ssamartzis Thank you, I try reproduce and fix this problem.

**Comment by AndreiMaz** [comment]
@tigran-avdalyan Tigran, we cannot reproduce it. Could you please the share your stack trace?

**Comment by skoshelev** [comment]
Closed #2077
