### ISSUE TITLE
Display store closed when database is not accessible

### ISSUE THREAD

**Issue by shurub3l** [nopSolutions/nopCommerce#2180]
Right now, when there is a problem with the database access the website displays Runtime Error (Server Error in '/' Application.). I think it should display the store closed page, or a different more user friendly error page.

**Comment by AndreiMaz** [comment]
Thanks a lot!

But it should display the error page with complete stack. So it's eaisier to investigate. It's by design.

**Comment by stephdep** [comment]
"But it should display the error page with complete stack. "
To shop visitors, really  ? I would rather think it mails the admin with details, logs the issue with full stack trace, and shows a banner with a general and gentle message to inform the visitor about the fact there is a technical issue.

**Comment by AndreiMaz** [comment]
It should be the error page with a friendly message but not a store closed page. So by default in such cases visitors will see it (ErrorPage.htm). So just customize ErrorPage.htm file so it looks any way you want. This is how it works by design

And to see the full error stack store owners (developers) can edit web.config file. Just set mode="Off" of "customErrors"

**Comment by stephdep** [comment]
I agree Andrei. Does a store admin/owner get notified of this exception(al) event ?

**Comment by AndreiMaz** [comment]
No. It's not possible. Anyway database is not available (hence email account info cannot be loaded)

**Comment by stephdep** [comment]
There is always a way ;-) It's a matter of not losing business, better to try as much as is still possible.
Create a cached ExceptionHandler that loads all the needed data upfront , email smpt settings etc 
at startup, and then has it available when the exception happens.
