### ISSUE TITLE
Show "Visible individually" only if product type is "Simple"

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#2210]
Do it using javascript like it's already done for other fields

Also ensure that works fine for importing (when not specified, it should be enabled)

**Comment by infinito62** [comment]
If it's a matter of defaults and label no problem, but PLEASE don't modify behaviour!
It works fine and a lot of customization has been arranged around.

**Comment by AndreiMaz** [comment]
This behaviour won't be change. This checkbox just won't be visible when "Grouped" product type is selected

**Comment by infinito62** [comment]
This is a problem.When I create a grouped product I don't want it to be visible immediately.  It'll be when I send the monthly newsletter to customers. This means that grouped product must be false. I can control this via SQL trigger of course but this is extra work. Please leave behaviour as now, it works fine. 
Inviato da Yahoo Mail su Android 
 
  Il Gio, 9 Mar, 2017 alle 19:50, Andrei Mazulnitsyn<notifications@github.com> ha scritto:   
This behaviour won't be change. This checkbox just won't be visible when "Grouped" product type is selected

**Comment by AndreiMaz** [comment]
why don't you use "Published" for such purposes?

**Comment by infinito62** [comment]
In fact I do. I use variants sincronized via Sql to erp back and forth.  I sincronize prices,  stock, names, obsolescence, new product, starting date, promos, tier prices, pricelists per customer roles and published against complex conditions. In all this mess with 2500 variants not always everything works like a swiss watch. It happens that new products are published while shouldn't, that's why I use visible individually in grouped produts as a definitive switch.  All variants have this flag off.  In this way everything is under control. Without sp, triggers, night routines that check everything, it'impossible to manage a complex ecommerce that sells hundreds of produts a day in complex orders. Inviato da Yahoo Mail su Android 
 
  Il Gio, 9 Mar, 2017 alle 20:53, Andrei Mazulnitsyn<notifications@github.com> ha scritto:   
why don't you use "Published" for such purposes?

**Comment by infinito62** [comment]
Anyway, you can include this feature in Basic view, while in Advanced it can be up.
