### ISSUE TITLE
Excel import. Support more than three pictures

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2281]
Now we can only add one picture for each time.
We need to insert Multiple Pictures from 1 time.
And add Multiple Pictures to product by List of pictures links.
List can be by Excel.

**Comment by tigran-avdalyan** [comment]
We can change product Import Excel Style. Like this.
![capture](https://cloud.githubusercontent.com/assets/17789934/24497960/28e93418-154e-11e7-8597-7881f66d8c00.PNG)

**Comment by AlexGeller** [comment]
The nopCommerce only allows to upload three pictures for every products on one time, this maybe related to upload performance.

**Comment by tigran-avdalyan** [comment]
if this issue while done https://github.com/nopSolutions/nopCommerce/issues/2320
we can enable this function without risks.

**Comment by ADERET1** [comment]
Tigran, AndreiMaz,
Is it possible to upload more than 3 images using Excel at one time?
I tried using the format Tigran showed up and got an error.

**Comment by skoshelev** [comment]
Hi @ADERET1. You can't import or export more than three images right now. This issue has a status "on hold", maybe we resolve it later

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization. The current approach (columns) are more friendly for simple scenarious.

**Comment by RomanovM** [comment]
See also: https://www.nopcommerce.com/boards/t/63778/suggestion-potentially-increase-the-number-of-product-images-that-can-be-importedexported.aspx

**Comment by davidandrewpowell** [comment]
@AndreiMaz I appreciate this issue was discussed and closed a while ago but for my project I require multiple images per product (not many; maybe 4 or 5) but I do require more than 3 images to be able to be imported.

I see this issue suggested having a list of images beneath the imported product which I appreciate would be more work than you would like and since the import product routine is quite long there may be a little risk involved in introducing it.

As you are aware, for excel imports, Nopcommerce currently imports product images via the fields:
Picture1
Picture2
Picture3

Would it be possible instead to allow the user to just add additional columns as necessary, thus introducing:
Picture4
Picture5
etc

I don't think it would be much work to change the **xml and excel** **imports and exports**.

For example, instead of the following code when importing products:

```
var picture1 = DownloadFile(metadata.Manager.GetProperty("Picture1")?.StringValue, downloadedFiles);
var picture2 = DownloadFile(metadata.Manager.GetProperty("Picture2")?.StringValue, downloadedFiles);
var picture3 = DownloadFile(metadata.Manager.GetProperty("Picture3")?.StringValue, downloadedFiles);

productPictureMetadata.Add(new ProductPictureMetadata
{
    ProductItem = product,
    Picture1Path = picture1,
    Picture2Path = picture2,
    Picture3Path = picture3,
    IsNew = isNew
});
```

I imagine something similar (not yet tested) instead:

```
IList<string> picturePaths = new List<string>();
int pictureNumber = 1;
var picturePath = metadata.Manager.GetProperty($"Picture{pictureNumber}")?.StringValue;
                    
while (!string.IsNullOrEmpty(picturePath))
{
    picturePath = DownloadFile(picturePath, downloadedFiles);
    picturePaths.Add(picturePath);
    pictureNumber++;
    picturePath = metadata.Manager.GetProperty($"Picture{pictureNumber}")?.StringValue;
}

productPictureMetadata.Add(new ProductPictureMetadata
{
    ProductItem = product,
    PicturePaths = picturePaths,
    IsNew = isNew
});
```

Someone mentioned above that adding extra images will impact on performance which I appreciate but surely this is on the user to be sensible about how the excel files are broken down to perform their imports.

Finally, if you do decide to implement this then I do not mind writing the pull request with unit tests (where possible) and submitting this.  I will need to write this for my own project but I would much rather this be part of the Nopcommerce functionality.

I look forward to hearing your thoughts. Thanks.
