### ISSUE TITLE
Import Product Picture URL Support

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2282]
when importing product, picture Address not support URL format

**Comment by lataing** [comment]
I think it's necessary.

**Comment by AndreiMaz** [comment]
Thanks. But wedon't plan to support it. Mostly because it'll make resizing not possible

**Comment by petemitch** [comment]
I think the nop product import routine could download the file from the url and then store it in the database or local file system as usual. It doesn't need to keep a permanent record of the external url, just use it to retrieve the initial image instead of having to copy the source images to the live webserver.

**Comment by skoshelev** [comment]
Closed #2282

**Comment by kryptus47** [comment]
> Thanks. But we don't plan to support it. Mostly because it'll make resizing not possible

Well, I totally disagree with you. If your image source is IceCat for example, they give you four urls per product, LowPic, MediumPic, HighPic, ThumbPic, so there is absolutely no need to resize the pictures. 
And in my opinion, this is not a request that you can just close like this since you didn't understand the concern about the database size. I have about 500'000 with each having several pictures, do you think it is ok that my database is going to be like 100Gb+ ?

Honestly I don't understand the way you consider thoses issues, it is like the specification attribute grouping, a total nonsense.
