### ISSUE TITLE
Metric (Fractional) product quantities

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#232]
Metric product quantities: 

the ability to calculate the price based on the unit of measure (weight, length, volume..) 
1 - setup the variant to optionally set the price per unit. 
2 - create the pricePerUnit list for the variant 
3 - modify the order manager to look for wether the price si perunit or fixed price. if per unit, then look for the price and multiply by the number of products added to cart (in this case it is the number of units) 

Keep in mind that not all payment methods support decimal quantities

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box.

**Comment by sencagri** [comment]
So, I am ready to contribute. Is there any disadvantage?

**Comment by luc-cap** [comment]
Hello ,
        I have been using Nop since version 2.65, and   I think it is one of the best shopping cart solution based in .NET Core, but I think you had to develop Decimal quantity feature support from the beginning.

Needless to say, I lost another sale due to this lack.

I work with small to medium-sized companies, the loss of the Sevenspikes API + the inability to use their graphical plugins (if I set decimal quantities in the product entity) make it really difficult to work.

Now that Nop:
     - It is based on the latest version of .NET Core
     - Has an Async Repository
     - It is deployable as Docker Container
     - Is is deployable on Azure
     - Is Multidatabase
     - Has very high quality graphic plugins developed by their Partners

Please make it able to place product orders by setting a Decimal quantity.

I am sure that many sites are not developed in nopcommerce due to the lack of this fundamental feature.

Sevenspikes itself has made itself available to add support of the feature in its plugins.
 
``
If the nopCommerce team adds support for decimal quantity then of course we will also add it in our plugins.

_Originally posted by @noptemplates in https://github.com/nopSolutions/nopCommerce/issues/5314#issuecomment-773970122_ 
``

This would also allow you to lower the price of the APIs you have developed. Reading the documentation, they look and will be great!  honestly I would need to buy them, but for medium-small companies, the price is high.

Please tag this issue as an "Enterprise / highlight feature "  for the next relase

Thanks

Luca

**Comment by sencagri** [comment]
> Hello ,
> I have been using Nop since version 2.65, and I think it is one of the best shopping cart solution based in .NET Core, but I think you had to develop Decimal quantity feature support from the beginning.
> 
> Needless to say, I lost another sale due to this lack.
> 
> I work with small to medium-sized companies, the loss of the Sevenspikes API + the inability to use their graphical plugins (if I set decimal quantities in the product entity) make it really difficult to work.
> 
> Now that Nop:
> - It is based on the latest version of .NET Core
> - Has an Async Repository
> - It is deployable as Docker Container
> - Is is deployable on Azure
> - Is Multidatabase
> - Has very high quality graphic plugins developed by their Partners
> 
> Please make it able to place product orders by setting a Decimal quantity.
> 
> I am sure that many sites are not developed in nopcommerce due to the lack of this fundamental feature.
> 
> Sevenspikes itself has made itself available to add support of the feature in its plugins.
> 
> ``
> If the nopCommerce team adds support for decimal quantity then of course we will also add it in our plugins.
> 
> _Originally posted by @noptemplates in [#5314 (comment)](https://github.com/nopSolutions/nopCommerce/issues/5314#issuecomment-773970122)_
> ``
> 
> This would also allow you to lower the price of the APIs you have developed. Reading the documentation, they look and will be great! honestly I would need to buy them, but for medium-small companies, the price is high.
> 
> Please tag this issue as an "Enterprise / highlight feature " for the next relase
> 
> Thanks
> 
> Luca

Totally agree with you

**Comment by Horus76** [comment]
Totally agree with you , 
I use nopcommerce salla version 1.9, and many customers have asked us for the ability to manage decimals, (unfortunately lost) would be a big step, and make a difference with direct competitors.
I really hope you can plan them.

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization

It'll cause too many issues with third-party providers (e.g. payments or shipping services)

**Comment by JosephMDavis** [comment]
I, too, have lost several clients due to not being able to support fractional quantities. Occasionally I am able to build a customers site with another tool, but we don't like to do that for a myriad of reasons. 

I know you just decided (again) not to implement this but I wanted to add my vote anyway. 

This isn't ideal but maybe a solution would be to have a secondary qty field that is used only when an optional "Fractional Quantities" setting is turned on. When using this option, mileage would vary for third-party plugins. This would give developers time to implement support in their plugins for it.

In the very least, could you post a list of the plugins you're worried about not supporting it? We could then work with those developers to support it.

**Comment by glhays** [comment]
This still has my vote as well. The global market place has a vast product list that requires a true UOM (unit of measure) type product.


________________________________
