### ISSUE TITLE
Ensure nopCommerce is GDPR compliant

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2361]
Decide whether to support it out of the box.

Right now there's a third-party plugin https://www.nopcommerce.com/p/3068/gdpr-plug-in.aspx

see https://www.nopcommerce.com/boards/t/51492/gdpr-avg-support-in-nop-41.aspx

**Comment by tmotionsglobal** [comment]
Thanks for posting my comments. We are woking with organisations in the UK to make them GRDP compliant for the May 2018 deadline. Will be happy to provide any support.

**Comment by AndreiMaz** [comment]
@tmotionsglobal Thanks. I’ve reviewed the site and requirements. I haven’t found anything that could affect nopCommerce. Maybe, I missed something. Do you have certain details what we could miss?

**Comment by mspapens** [comment]
It's about procedures (not affecting nopCommerce) and functions (affecting nopCommerce). To make sure the procedures are efficient, nopCommerce should support a minimum of these functions:
- Make sure as much personal data is encrypted in the db (some of it maybe already, also think about data like IP address and what products are viewed)
- Make sure as much personal order/payment data is encrypted (some of it maybe already)
- Add function to create a report that contains all data that is stored about the customer, including viewed and ordered products and how they are paid for
- Add function to anonymise personal data so that nothing can be tracked back to the customer (the delete customer option does a soft delete today)
- Add function to request the report and anonymisation via the My Account page.
- Add task to auto-anonymise or delete certain details after a period of time.
- Add consent functions in My Account and during account registration to record in detail when and how the customer has agreed to it.

I'm not an expert in this area, so I'm sure this list is incomplete. I think it is a lot of work and I certainly hope that all the effort is worth it. I remember the EU Cookie law and how people now respond to it...

**Comment by AndreiMaz** [comment]
one more reply from our user

1. In The new core framework is it right that MS did not support ODATA at this moment?

If so do you have an idea if they are working on it and also a timeframe?

I am asking, because we had made an connector which is based on ODATA and we are getting a new law in Europe (which is also valid for US if they sell in Europe). The new privacy law is coming on may 2018, at one of the new principals is, that a customer has to explicite accept the privacy conditions and it is mportand to sace the day and time when he had it done. 99 new paragraphs on 80 pages law…

I am sure that every shop must have some changes about this. Because the customers need this, they need surly the new version of nop, but without ODATA…

So any ideas of that?

2. no the cookie law was something simple. The new one it’s called: GDPR - The new EU Data Protection Basic Regulation (DSGVO).

And it has some new important changes, actually I am reading a lot about it, also we have an appointment with our lawyer.

One thing is that the customer must confirm what and why things are used (IP, Cookie, Trackingpixel etc.) and it has to be saved in a database (the date when he has signed). Also if he wants to cancel all his private information, it should be done in 72 hours and so on …

But it is not only valid in EU, is is valid also in USA when they make business in the European market. So it will become a very important change to to a lot of companys who are making online business (also companies like Facebook etc.).

So  I think that perhaps would be a good feature if nop 4.0 works also with the old .NET Framework (hybrid), so all Plugins and ODATA is working.

When new low gets online, I think it would be a serious problem if a company could not change to the new version of nop because something is missing.

But I will keep you informed what we get on new information.

In any case it us valid in the complete EU and all external countries who makes business with EU.

They called something out: 20 Mill / or 4% of the gross profit is to pay (maximum) if the law is broken. 

We will see and we have also 8 Month… lot of time…

A basic article is:
https://de.wikipedia.org/wiki/Datenschutz-Grundverordnung

You could translate it very good with the new translator of German founders:
https://www.deepl.com/translator

**Comment by tmotionsglobal** [comment]
yes, GDPR compliance is fairly comprehensive exercise, which includes complete analysis of the business and applications with regard to handling and processing of personal data, appointing DPO (data protection officer) and formulating policies and procedures. But here we are looking at only the application part where our Clients are using nopCommerce as a platform for their B2C and B2B projects. Our clients can alter the parts of their nopCommerce configuration to achieve basic compliance, such as, data encryption and user registration forms for consent and 'right to erasure'. They would need to make changes in the user table in db to ensure the personal information is stored in encrypted form. However, we can build and offer a ready-made solution in nopCommerce to meet these requirements. At the moment default registration form (http://demo.nopcommerce.com/register) are simple and do not contain fields (in form and db) that they would need to manage consent as per the GDPR requirement. Also at present the personal data (name, address, etc) are not encrypted in the user table in db of nopCommerce.
We, at Tmotions are in the process of developing plug-ins which will be available at the nop marketplace and can be integrated easily to fulfil these requirements. We are also exploring the option of using a third party user/identity management service which can be integrated to nopCommerce.
I will keep you informed on this.
I can't comment on ODATA as we have never implemented it.

**Comment by samdubey** [comment]
Hope this webinar helps
https://www.pluralsight.com/resource-center/webinars/how-general-protection-regulation-will-impact-it

**Comment by tmotionsglobal** [comment]
join the webinar "nopCommerce & GDPR" to learn more on this topic.

https://attendee.gotowebinar.com/register/5043168854127692547

The General Data Protection Regulation (GDPR): Is your business compliant? 

The EU GDPR is due to come into effect in May 2018. GDPR will require businesses to demonstrate that they are protecting the personal data rights of EU Citizens. The GDPR will have significant impact on e-commerce and online businesses that deal with customers and users in the EU countries, even if they are based outside of the EU, and regardless of Brexit. 

In this webinar, experts from TMotions and Digital Governance will share practical insights for organisations of all sizes to help them prepare for the GDPR, and how nopCommerce-based applications need to make essential changes to achieve GDPR compliance. 

What you will learn: 
•	Key things you need to know about the EU data protection regulation changes 
•	GDPR impact on e-commerce and online shops 
•	GDPR compliance in nopCommerce based applications 
•	Compliance by Design 


After registering, you will receive a confirmation email containing information about joining the webinar.

**Comment by cklenk** [comment]
What nop versions did this all get added into?

**Comment by AndreiMaz** [comment]
4.10+ out of the box

**Comment by cklenk** [comment]
Okay thank you
