### ISSUE TITLE
QR code support

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#241]
More and more people are getting smartphones. And idea would be to get a barcodegenerator, to generate a barcode (QR) for a productsite or any other site for that matter.  Like the activeate a product/category is shown in the admin section, a button saying show barcode. This will make it easy for people to "write" the link onto their smartphone if they found an offer the wish to save. 

Forum source: http://www.nopcommerce.com/boards/t/19953/create-barcode-for-phone.aspx

Maybe, it's better to implement it as a plugin

Let's choose a library. For example, https://github.com/codebude/QRCoder

also see a comment below

**Comment by suddenelfilio** [comment]
Should you consider a library for QR why not open it to any barcode type supported by the library instead of only QR? You're looking at this from a customer perspective, but what about a store owner? generating barcodes for orders, products and so on which are not WR might be added value. Especially if you keep in mind that barcode scanners (hardware) that support QR are still more expensive than a basic 2D barcode scanner. Main concern here is since this is a web application is how to react on a "barcode scan" from a device? I know SEOShop used to have this functionality, but it was flaky at best. Maybe now its better don't know.

**Comment by AndreiMaz** [comment]
After some consideration decided not to implement out of the box (leave for customization)

For plugin development
