### ISSUE TITLE
External authentions for ASP.NET Core 2.0 (use the core identity)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2500]
my suggestion in to implement the core identity which will cover all external connections.
its simple and easy and i think it should be part of the solution

Source: https://www.nopcommerce.com/boards/t/48357/external-authentions-for-aspnet-core-20.aspx

**Comment by JeanCollas** [comment]
I would also really appreciate it, to be able to use the ASP.NET Core Identity for the whole authentication process.
It would allow having nopCommerce as a service that is plugged to existing websites with their own authentication.

**Comment by JeanCollas** [comment]
@AndreiMaz Is there any reason why you would not use the Core Identity? 
Only for the connection (email authentication and external).

Is it because of development involved or structural issues? 
If this is because of dev, I would be happy to chat with somebody to see if I could provide an implementation as I actually need it.

**Comment by esbee** [comment]
We all agree on this...
