### ISSUE TITLE
Think out how to delete folders with locales (e.g. \en, \de) from output

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2547]
It started since moving to ASP.NET Core

**Comment by poyker** [comment]
I am not sure if this issue is related to the plugins or just Nop.Web but there is no point to create a new issue anyway.

It would be great if you could improve **ClearPluginAssemblies.proj** to delete these locale folders from the plugins. Now if you build the solution every plugin has around 4MB unnecessary locale folder (even if they are needed they could be loaded from the Nop.Web project and there is no need each plugin to have them).

**Comment by skoshelev** [comment]
Closed #2547
