### ISSUE TITLE
FatalException and ExecutionEngineException in ScheduleTaskService.cs - GetAllTasks()

### ISSUE THREAD

**Issue by mmccann-umph** [nopSolutions/nopCommerce#2558]
When installing a new instance of nopCommerce 4.0 using Sql Server Express with windows authentication and sample:data true I intermittently get errors thrown from ScheduleTaskService.cs -> GetAllTasks(bool showHidden=false).

I either get a FatalException - this may be caused by the CLR exception on line 88.   If I continue restarting then it will eventually run without throwing the exception.

Once installed, if I try to run Nop.Web with IISExpress (clean install, no changes to code or settings) I get a different exception on the same method and line of code.
System.ExecutionEngineException on line 88 (var tasks = query.ToList();)

one more report - https://www.nopcommerce.com/boards/t/49120/nopcommerce-400-beta-released-please-share-your-impressions.aspx?p=3#194798 and https://www.nopcommerce.com/boards/t/49120/nopcommerce-400-beta-released-please-share-your-impressions.aspx?p=4#194852

and the same topic https://github.com/nopSolutions/nopCommerce/issues/2455

**Comment by poyker** [comment]
@mmccann-umph 

[This](https://developercommunity.visualstudio.com/content/problem/29782/managed-debugging-assistant-fatalexecutionengineer.html) helped me a lot.

Just go to "Tools -> Options -> Debugging" in VS2017 and Uncheck this "Enable Diagnostic Tools while debugging". This worked for me.

I am experiencing some other issues and I am curious if you have them too:

- Restart Application or Installing/Uninstalling a plugin stops the Debugger. I guess this is because when the Web.config is changed the whole Nop.Web.exe process is stopped and a new one is started. It would be great if there was a way to continue debugging though.

**Comment by AndreiMaz** [comment]
This issue is not of nopCommerce but of .NET. It was solved in 4.7.1 which don't plan to use (https://github.com/Microsoft/dotnet/blob/master/releases/net471/dotnet471-changes.md - "Fixed intermittent crash during GC with ETW memory tracing turned on"). Now the only solution is 'Enable Diagnostics Tools while debugging'

**Comment by RomanovM** [comment]
The only solution is disable 'Enable Diagnostics Tools while debugging' https://github.com/dotnet/coreclr/issues/10717#issuecomment-297469227
