### ISSUE TITLE
Product attribute price adjustments as percentages

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#26]
Currently it is possible only to adjust product price using fixed amounts (eg. if color = blue -> price is +5). It would be very benficial if it would be possible to do such adjustment using percentage basis. Eg. if size id XL then price is 10% more; if size is XS than price is 25% less etc. 

Forum source: http://www.nopcommerce.com/boards/t/19239/percentage-adjustment-for-product-variant-attributes.aspx 

We should add percent to the base product price only (in case if there several product attributes with price adjustments)

**Comment by AndreiMaz** [comment]
One interesting thing thing to note is that once we start to do percentages the order becomes important. With value only adjustments this wasn't important since addition is commutative (order unimportant) but with a possible mix of addition and multiplication it suddendly is important. Eg.

base price of $10 * 120% + $10 = $22
(base price of $10 + 10) * 1.2 = $24 ..

**Comment by AndreiMaz** [comment]
"One interesting thing thing to note is that once we start to do percentages the order becomes important. With value only adjustments this wasn't important since addition is commutative (order unimportant) but with a possible mix of addition and multiplication it suddendly is important. Eg.
base price of $10 * 120% + $10 = $22
(base price of $10 + 10) * 1.2 = $24 .."

The percentage or sum addition should be applied over the adjusted base price resulting from previous adjustment

**Comment by MikeDub** [comment]
I agree this feature is valuable and in my cases, the percentage would generally be calculated as a percentage of the base price, with this abstraction order would not be important.
If it was done as a percentage of the sum I agree order would be important. 
I would recommend an initial implementation with just the base price as the calculation so it can be could be of benefit to some, while adding the cumulative option later.

**Comment by AndreiMaz** [comment]
On the other side we can separate add percent to the base price only. And then sum all additional fees

**Comment by skoshelev** [comment]
Closed #26
