### ISSUE TITLE
Performance optimization of bundling and minification

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2612]
it's quite slow now

**Comment by alecrt** [comment]
Why not cache for 120mins or even more?
In production environment no one should play much with js and css. 
Anytime there's the clear cache button available in the admin area.

Take a look at Umbraco: client dependency cache assets forever. Manual file change in clientdependency.config file is necessary in order to force bundles update!

In my opinion, in production env, performance must be the king rule.

**Comment by AndreiMaz** [comment]
@alecrt actually, yeah. you're right
