### ISSUE TITLE
Save all inline scripts into external file

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2682]
We already move inline scripts to the footer. We can also save them into external file and reference it (process dynamically before rendering). I'll be even faster. Let's make it configurable.

**Comment by colinwphillips** [comment]
Please keep in mind that HTTP/2 alleviates most of the benefits of consolidation of all files - I'd request you leave the consolidation portion as an independent configurable performance feature if implemented (move to external file[s] can be turned on independent of consolidation - the former is definitely huge for us).

I.E. if moved to external file - CDN would further boost performance of resources.
However if file becomes one large JS resource, it would not become blocking due to footer but if it is no longer downloaded as part of the HTML it could create a jittery experience for the user if the JS alters the DOM.

Additionally - CDN features like Cloudflare's RocketLoader would be defeated with this consolidation enabled, but would boost tremendously with external JS.

A perhaps over-engineered solution would be to consolidate up to a configurable file size/length and break the files into separate files that could be loaded in parallel over HTTP/2.

**Comment by AndreiMaz** [comment]
after some consideration we've decided not to implement this functionality
