### ISSUE TITLE
Slow VS building

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2766]
Some users report that it became very slow (starting 4.00)

**Comment by Xzelsius** [comment]
Yes it is really annoying.

Here some links
https://github.com/dotnet/cli/issues/8103
https://github.com/dotnet/project-system/issues/2588
https://github.com/Microsoft/msbuild/issues/2238

But i don't think it is because of 4.00. I am facing the same with a default project created by console (`dotnet new mvc`)

**Comment by ChrisJollyAU** [comment]
Might be fixed in VS 15.5 
See https://developercommunity.visualstudio.com/content/problem/37643/vs-2017-build-very-slow.html

**Comment by adamwulala** [comment]
Should be related to this improvement https://www.facebook.com/welovedotnet/posts/164386160726204
It already improved open solution time and build time at vs15.5

**Comment by skoshelev** [comment]
We investigated this problem and came to a conclusion that it is not related to our platform. And also with each visual studio update the performance rises. That's why we close this ticket.

Closed #2766

**Comment by Joebeazelman** [comment]
I notice when I open my nopcommerce solution in VS 2019 on both Windows and MacOS, VS slows to a crawl even when you're not compiling. I am also having an issue which may or may not be related. When I try to build version 4.3 in VS Code, it crashes the IDE during ClearPluginAssemblies.proj. I was able to glimpse the msbuild error and it said "arguments too long" and dumps out a very long error message.

Does VS Studio 2019 and or VS Code perform some preliminary build process in the background?  I suspect it does, since it has to process json configuration and project files in order to have the same build results of dotnetcore. These files don't necessarily have to be included in the solution to be processed. It is possible VS is executing some tasks in the background such as ClearPluginAssemblies.proj or some other task. I did notice when I removed the "ClearPluginAssemblies.dll $().." line from the ClearPluginAssemblies.proj, VSCode no longer crashed and the build was very fast.
