### ISSUE TITLE
Unable to load DLL 'libuv'

### ISSUE THREAD

**Issue by ArturAlekseev** [nopSolutions/nopCommerce#2786]
DllNotFoundException: Unable to load DLL 'libuv': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

Here:
```
 public static void Main(string[] args)
        {
            var host = WebHost.CreateDefaultBuilder(args)
                .UseKestrel(options => options.AddServerHeader = false)
                .UseStartup<Startup>()
                .Build();

            host.Run(); //<< HERE
        }
```
When Nop.Web and all other are set to be built as Any CPU.
Temp solution is to specify Nop.Web x86 or x64.

**Comment by Xzelsius** [comment]
Are you sure you have restored all package references and rebuilt the whole solution?

Because for me everything builds and runs well on Any CPU, x86 and x64.
I've debugged and tested both Debug and Release Builds with IIS Express and Nop.Web.exe.

git ref is at [0268bf4](https://github.com/nopSolutions/nopCommerce/commit/0268bf4f9cf72df870ba1ef17c41f151415e7f06)

What Visual Studio version are you using?

**Comment by ArturAlekseev** [comment]
Well. I'm not at the latest ref. Maybe this is the issue.

**Comment by ArturAlekseev** [comment]
I'v synced with latest commits. And issue is gone.
