### ISSUE TITLE
Display a warning if multiple plugins try to override the same interface, etc

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2805]
This way there won't be any conflicts (issues). For example, if two plugins override the same service

**Comment by mewajda** [comment]
Please try to make this a priority feature.  A colleague and I just spent hours trying to figure out why a plugins' code wasn't firing.  It turned out that 3 other plugins were overriding the same service as the plugin in question, but those plugins were registered later.  This would be very helpful to bring to the attention of store owner/devs if it happens.

**Comment by skoshelev** [comment]
Closed #2805

**Comment by RomanovM** [comment]
Reopened since moved to net core service provider (details [here](https://github.com/nopSolutions/nopCommerce/commit/44cb2cce21bbbdd600b1f5e6ad3f243df7dfe696#diff-d80847b13175d4700fe5c31f6abb19fbef2d797993cdbae89579967e8aed516bR457)).

**Comment by skoshelev** [comment]
Closed #2805
