### ISSUE TITLE
Development. Add more events

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#282]
Add more events such as:
1. customer registration (already done)
2. Formatting customer username/email/full name
3. Prepared model (for example, ProductModel). This even could be used to modify a model before passing it to a view
4. see pull request https://github.com/nopSolutions/nopCommerce/pull/2559

Other suggestions? prepare a list of such events first

More: http://www.nopcommerce.com/boards/t/46636/suggestion-new-events-for-customer-events.aspx

also see related - https://github.com/nopSolutions/nopCommerce/issues/1959

**Comment by turbochris** [comment]
I would like an event on important stuff before update. 

So current product update is:

` public virtual void UpdateProduct(Product product)
        {
            if (product == null)
                throw new ArgumentNullException("product");

            //update
            _productRepository.Update(product);

            //cache
            _cacheManager.RemoveByPattern(PRODUCTS_PATTERN_KEY);

            //event notification
            _eventPublisher.EntityUpdated(product);
        }`

I would like it changed to:

 public virtual void UpdateProduct(Product product)
        {
            if (product == null)
                throw new ArgumentNullException("product");

           //event notification
            _eventPublisher.EntityBeforeUpdate(product);

            //update
            _productRepository.Update(product);

            //cache
            _cacheManager.RemoveByPattern(PRODUCTS_PATTERN_KEY);

            //event notification
            _eventPublisher.EntityUpdated(product);
        }

This will allow me to keep track of changes in different plugins. It would be a cool way af making a "Price change history" or similar. Of course it could give a serious performance hit. So maybe also send the EF change tracker with, so a developer can ignore if a field has not been modified. 

I.E i don't care if name of product has been changed. But I do care if price has changed. If the changetracker is included in the event, I will be able to see if a specific field has been updated, before making a GetProductById to see old product's value..

**Comment by SuperArtie** [comment]
I have submitted a pull request to be looked at in regards to this issue. [#2559](https://github.com/nopSolutions/nopCommerce/pull/2559)

I have added extensions to EventPublisher so that events can be published with view models.

I would find it extraordinarily useful to have the ability to massage/validate data before it gets stored in the db.

An example could be for a plugin utilizing a third-party address verification service. If the form submitted for a new customer address fails validation, ModelState.IsValid could be set from the plugin by consuming these events, instead of having to use mvc ActionFilters or overriding a default controller action.
