### ISSUE TITLE
Display "From" prices for products with attributes or combinations with price adjustments (configurable)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#29]
We have product boxes on catalog pages (category, manufacturer, etc). In some cases, we have product attributes with price adjustments. In some cases, we have attribute combinations with price adjustments.

So actually we should display the minimum possible price of a product. So if a product could have different prices (based on selected attributes), then we should display "From ..." price instead of the fixed base price (such as it's done now at https://demo.nopcommerce.com/desktops - just an example).

Also, let's make it configurable whether to display the base price or display the minimum possible price. Otherwise, it can affect the performance in some cases. Add this new setting to admin area > configuration > catalog pages > "Catalog pages" block > "Display "From" prices" setting (disabled by default)

**Comment by AndreiMaz** [comment]
I was going to bring up something on the 3.4 roadmap, but because it was already looking awesome, I was going to wait until 3.5 before bringing this up. But seeing the statement "make it configurable because it can seriosly affect performance (disable by default) ", I will mention it now.

If we took a different architecture approach, many of these expensive lookups could be minimized. If we had an additional background job that ran off a queue, we could do very complex logic like this work item is requesting with no performance impact.

Just like cache is updated when we save a product in the admin, any changes could also be pushed to a stack (similar to what we are doing already with activity monitor). So, lets look at a practical scenario.

Store admin comes in and makes price adjustments to attribute options and maybe even updates a lot of attribute combinations. We write (using a queue paradigm) the events to a background work stack. So, an example row would be (ProductId, enum for price adjustment, etc). Within a min or two, the background job would pull off the stack and determine (From and To) prices based on changes, then write these 2 values right into 2 new columns in the product table and updates the cache as normal.

When this product is pulled for the Catalog for someone browsing, the From and To are now simple fields that have no "real-time" calculation needed.

This same architecture shift could be applied to many many scenarios in nopCommerce. The goal being, during user browsing of the site, avoid complex logic by just putting results as simple attributes, and leaving the calculation of those values to back-end services. 

As this work item is on the 3.4 roadmap now, I will make a note in the roadmap thread.

**Comment by AndreiMaz** [comment]
One additional point to the above comment. Essentially this adds up to introducing the concept of "Calculated fields" populated by background jobs to make catalog browsing faster.

**Comment by AndreiMaz** [comment]
Thanks for suggestion. Please note that nopCommerce supports tier prices per customer role. So these ranges could vary based on customer role and some complex discount rules. That's why it should be done "real-time"

**Comment by AndreiMaz** [comment]
An alternative would be an option to hide the "From" and "To" prices on Catalog pages.

**Comment by AndreiMaz** [comment]
Does this effect performance of the while web site regardless if this method of dealing with product attribute pricing is only need a on a few products? Example computer a system page.

I worked around this sort of by creating a custom category template page for the category page for the computer system configurators. I hid the price and add to cart section so it is juts the picture and short description. So the person has to click to the product page to see the system and the attribute based pricing. 
Not ideal I know. But it is all I could come up with until some solution is found to allow for pricing to show up correctly. 
Another option I tried to do but could not figure out was to replace the Add to cart button with a Configure button that bring you to the product. page so at least there is a obvious button to press. 

I sure hope some solution happens that allows for the dynamic pricing to show up as expected. This would make it perfect and do what our old cold fusion based configurator could do. :)

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. It can affect performance too much. Leave it for customization

**Comment by PanagLtd** [comment]
> Thanks for suggestion. Please note that nopCommerce supports tier prices per customer role. So these ranges could vary based on customer role and some complex discount rules. That's why it should be done "real-time"

You can multiply the calculation and saved rows for each customer rule and store and add 2 fields in the table with the customer role and sore that these rows apply to . It is still going to be extremely faster than real-time calculation.
