### ISSUE TITLE
Google Analytics. Qty is not properly passed

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2992]
nopCommerce version: 4.00

Steps to reproduce the problem: 
1. Create a product. Set its SKU
2. Add a product attribute and two values (e.g. value1 and value2)
3. Add this product to the cart with qty 1 and value1
4. Add this product to the cart with qty 1 and value2
5. Place an order
6. You'll see in GA only one product line (SKU) with qty 1 (that it wrong)

Of course, we can create combinations and its unique SKU. But it won't help us when product attribute type is textbox.

So we can group products (qty) by SKU and sum up its cost. But not sure that it's correct way to go

**Comment by justindongqiang** [comment]
I will look into this bug over the weekend.

**Comment by justindongqiang** [comment]
@AndreiMaz I am pretty new with GA and I have set up the account and I just got my GA works on my localhost by changing the js code in the setting...  and will try to reproduce it on my local box.   "You'll see in GA only one product line (SKU) with qty 1 (that it wrong)",  can you please shoot me a screenshot to highlight where it goes wrong in GA? That will be greatly help understand the issue and speed up the RCA..

**Comment by AndreiMaz** [comment]
@justindongqiang Thanks a lot! please note that in 4.10 we send this info using API calls to GA (not JS)

**Comment by justindongqiang** [comment]
![2018-05-13_9-15-21](https://user-images.githubusercontent.com/18490641/39968171-771813f2-568e-11e8-8e0f-5f175c9736ee.jpg)
I was saying I added one line of code in GA setting(see screenshot) so that I could see the activity from my localhost in GA. I see we have changed the tracking code in v4.1 and I will add that line to v4.1 in GA to test it.

**Comment by justindongqiang** [comment]
@AndreiMaz I have preformed step 1 to 5 and order has been placed. Now I went to GA and it looks as below. Can you show me where to see step 6 "You'll see in GA only one product line (SKU) with qty 1 (that it wrong)" please?

![2018-05-13_20-32-31](https://user-images.githubusercontent.com/18490641/39974266-1eb657e6-56ed-11e8-98a1-90cc127509c0.jpg)

**Comment by justindongqiang** [comment]
Alright I think I found it in the code the EnableEcommerce need to be enabled. I will try that tomorrow. 
But please confirm following GA setting if they are correct settings. Can it fire api ProcessOrderEvent in EventConsumer class?
Should we go with Google Analytics or Universal Analytics?
Which checkbox need to be checked in order to reproduce this issue?

![2018-05-13_21-04-07](https://user-images.githubusercontent.com/18490641/39974990-9be56942-56f1-11e8-8bca-4e7d16a14bef.jpg)

Thanks,
Justin

**Comment by AndreiMaz** [comment]
fixed as part of https://github.com/nopSolutions/nopCommerce/issues/2993

**Comment by AndreiMaz** [comment]
Please note that it works only with "JS" setting enabled

**Comment by justindongqiang** [comment]
Thank you AM. I have been on vacations with family and lost track on this issue. I will then look at other issues.
