### ISSUE TITLE
Replace js "Confirm" to Nop-action-confirmation window for Admin/Order/AddShipment

### ISSUE THREAD

**Issue by DmitriyKulagin** [nopSolutions/nopCommerce#3086]
The task is to rewrite the logic of displaying the additional message so that it is calculated on the model, not in the javascript. Thus, already at the model level, it will be decided which confirmation window to display on the page.
In the event model, we can not track the negative decision for confirmation, which is now generated in the "confirm ()".
It is necessary to use "asp-additional-confirm".

**Comment by justindongqiang** [comment]
@DmitriyKulagin I will take a look at this issue and I will refer to your  today's commit.

**Comment by justindongqiang** [comment]
@DmitriyKulagin I am pretty much done with the changes and just wanted to make sure that if we need to have confirmation window for both Save and SaveAndContinue events.

**Comment by DmitriyKulagin** [comment]
@justindongqiang Yes it is necessary for both events.

**Comment by justindongqiang** [comment]
@DmitriyKulagin I checked in additional changes to make sure confirmation window only opens when meets the condition of warehouse quantity. Please review and let me know if you have any questions.

1. As soon as you bind button id with nop-action-confirmation tag helper, the button click would open confirmation window always. This works fine for pretty much all the case, such as a Deletion button, but no in this case.

2. The confirmation window has to open when a condition met. Otherwise, it won't display confirm window. I have added workaround code to resolve this case. Basically I have looked what nop-action-confirmation did, and removed its auto generated code by tag helper on the fly, in focus event, it reset button status so it wont call confirmation window method.

3. I made a little more changes to make the code neat and dry, like jquery chaining and self 'this'.  

4. The script was included in the if statement "if (itemsFromMultipleWarehouses.Any())", I will need to remove it and make a little adjustment to sb sting to return a true if there is no items. The reason to remove line of 'if (itemsFromMultipleWarehouses.Any())' is because, in case there is no warehouse settings, and the entire script inside if statement won't happen, and the script I wrote to remove confirmation tag helper won't happen either,  the confirmation window should not appear, but we already bind the save button with nop-action-confirmation, this is causing confirmation window open where we donot want it open. I hope I made it a little clear.

Let me know if you have any questions.
 
Thanks,
Justin

**Comment by justindongqiang** [comment]
Any updates? Andrei. Perhaps we could get this in and refactoring tag helper later.

**Comment by DmitriyKulagin** [comment]
Closed #3127
