### ISSUE TITLE
Shipping by weight: product attribute weight adjustment not picked up

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3183]
nopCommerce version: 4.00

Steps to reproduce the problem: 
1. Shipping price adjusted according to weight adjustment set in product attributes
eg Weight = 100 Shipping price = 2.00
Weight adjustment = 500 weight should be 600 Shipping price = 12.00 

2. Weight adjustment = 500 Shipping price = 2.00

3 https://www.priorsrec.co.uk/arrowhead-iron-t-hinges 

Original weight = 300
Weight adjustment on 18inch is 1000 so buying 2 should remove UK 1st Class Post, this is still there in shipping estimate

4. No private mods

Source: https://www.nopcommerce.com/boards/t/54163/shipping-by-weight-product-attribute-weight-adjustment-not-picked-up.aspx

**Comment by DmitriyKulagin** [comment]
@AndreiMaz 
Since all plug-in settings are not listed in the task, it is difficult to say where the author made an error in the settings. But I think that the matter is in the "Manual (Fixed or By Weight and By Total)" settings. I tested different variations with "Weight adjustment" on the product details and it works correct. According to the formula - "Formula to calculate rates [additional fixed cost] + ([order total weight] - [lower weight limit]) * [rate per weight unit] + [order subtotal] * [charge percentage]"

**Comment by DmitriyKulagin** [comment]
Closed, details on the [source.](https://www.nopcommerce.com/boards/t/54163/shipping-by-weight-product-attribute-weight-adjustment-not-picked-up.aspx?p=2#209330)
