### ISSUE TITLE
Synchronize display of old/strikethrough price when attribute that changes price is selected.

### ISSUE THREAD

**Issue by compito** [nopSolutions/nopCommerce#3188]
nopCommerce version: 4.0

Steps to reproduce the problem: 
Go to detail page of product with attributes that can change base price. Old price and new/campaign price are shown. 
Select an attribute, material for the couch in my example. 
![screen](https://user-images.githubusercontent.com/3284850/43204170-7d41a916-9020-11e8-9c85-909b2db57537.png)

When you select an attribute that has additional charge, only campaign price is changed, old price remains the same. It looks weird, as if campaign price is higher than regular/old price. Both prices should be changed according to selected attribute. 
![screen-2](https://user-images.githubusercontent.com/3284850/43204169-7d22e800-9020-11e8-9dca-6645fc786a23.png)

Somewhat related to issue #3072

**Comment by compito** [comment]
Hi, is there any plan to implement this in one of the coming versions?

**Comment by AndreiMaz** [comment]
but If an attribute combination has overridden price, how can be calculated the "old" price?

**Comment by joekrauss** [comment]
Hello Andrei – from our perspective the term “override price” should mean it’s the price customers see when visiting a product, regardless of tier pricing, price or old price. The logic for override price seems to have gotten lost somewhere after 3.9 of NopCommerce. We used to use this option for promotional pricing overrides, it was typically used against a color or size attribute on a product listing. Now we have to create the same product attribute item as a standalone product in order to run discounts or promotions.

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality
