### ISSUE TITLE
"asp-disabled" doesn't work for nop-editor if bound to an int

### ISSUE THREAD

**Issue by spottedmahn** [nopSolutions/nopCommerce#3270]
**nopCommerce version:** 4.0

**Steps to reproduce the problem:** 

I've imported the [imported the fix](https://github.com/nopSolutions/nopCommerce/commit/8513819dd2076f206feac09586f5cdab3083474d) but it still doesn't work on model properties whose type is `int?`.  The patch does work on other data types.

```html
<div class="form-group">
	<div class="col-md-3">
		<nop-label asp-for="SomeInt" />
	</div>
	<div class="col-md-9">
		<nop-editor asp-for="SomeInt" asp-disabled="true" />
	</div>
</div>
```
```csharp
public class SomeModel : BaseNopEntityModel
{
	[Display(Name = "Some int")]
	public int? SomeInt { get; set; }
}
```

Related to: #2714

**Comment by DmitriyKulagin** [comment]
@spottedmahn 
Hi, 
I can not reproduce the error, it works correctly.
From the data type, the presence of the "disabled" attribute should not depend. Perhaps there is an error somewhere in your project. Try to reproduce the problem on a clean version of "release-4.10".

**Comment by DmitriyKulagin** [comment]
It is provided that the nop-editor tag should only be used in the administration panel. However, at the moment there are restrictions on its use with the attribute "disabled" for the types int, DateTime, double. Since the fields of these types are generated using the Bootstrap TouchSpin-v4.2.5 library (jquery.bootstrap-touchspin.js), we can not ensure that the "disabled" property works correctly in these cases, because this is not provided by this library.
