### ISSUE TITLE
NopCommerce have Future or not

### ISSUE THREAD

**Issue by ecommerce-tester** [nopSolutions/nopCommerce#3293]
NopCommerce keeps track of their competitors, and  needs of the  E-Commerce  sphere?
I recommend to study GrandNode, Virto Commerce, OpenCart, PrestoShop, Magento, to study functions that are absent in the NopCommerce.
NopCommerce does not have such simple functions as Full Rental features, Calendar, Auction, user friendly Product filter feature, Full advanced slider feature, Full Multi Vendor, Multi Currency Price for Product, Video for Product, Ribbon for Product/Categories, Beautiful Themes, Functional Default Plugins  and many more

I recommend to create more Milestones (4.30, 4.40, .....) for community plaining(use NopCommerce in future or not)

**Comment by cnEUL** [comment]
It's right to list all the good things in other systems, there are always a lot of points missing in your own system. I also would like to have some of these points, but I can understand very well, and personally find it a good decision to go the way to platform independence first. 

I am also sure that some of the points will come in 4.30 and later. But I also accept that the developer resources are limited and the path is not short.

I also know some of the listed shops and their weaknesses and in the end I switched to nopCommerce because the overall system is simply very good - in my opinion this is what nopCommerce really is.

Due to the upcoming platform independence the headwind will certainly be stronger, but there will still be a lot more users and therefore also a lot of new and good plugins, this is a completely natural way.

What I would also like to see, however, is an official roadmap that should also be evaluated and corrected by the core staff. Less because I would switch back to another product, but much more to prepare myself better.

**Comment by AndreiMaz** [comment]
Thanks a lot for suggestion! We've already studies all popular systems. We have a list of specific tasks we plan to implement. You can find all of them on this GitHub site (and filter by the next milestone/version).

if you have any specific suggestions, please create a seperate work item. I thin kwe can close this one because it's just a discussion rather than a specific work item

**Comment by ecommerce-tester** [comment]
@AndreiMaz 
What you think about SmartStore.net ?
