### ISSUE TITLE
Add the ability to hide order (and payment request) custom values from the customer

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#3304]
Something like we do it for the order note https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Core/Domain/Orders/OrderNote.cs#L28. In this case, we'll need to create a special class for custom values and not use a dictionary. Also ensure that it'll be correctly serialized in Order.CustomValuesXml.

Source: https://www.nopcommerce.com/boards/t/55439/order-details-and-pdf-showing-token.aspx
and https://www.nopcommerce.com/boards/topic/54935/custom-values-are-showing-up-in-order-receipts-nop-41

**Comment by cnEUL** [comment]
Hi, what could we do with such a feature, i mean what is the reason for such a feature in the real world? @RomanovM

**Comment by brakim** [comment]
Actully this i was looking for this feture when writing a Subscription plugin against BrainTree and i needed to store the PaymentType (CreditCard / Paypal) and some other stuff on the Order Request that i didn't want the customer to see.

I ended up storing it in GenericAttribtues on the customer and deleted them once i had the order and could store the information on the order itself instead of the customer.

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization
