### ISSUE TITLE
Bug in the upgrade script for Picture and PictureBinary tables

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3357]
nopCommerce version: 4.10

Steps to reproduce the problem: https://www.nopcommerce.com/boards/t/55655/bug-in-nopcommerce-410-upgrade-script-for-picture-and-picturebinary-tables.aspx

**Comment by jc9999jc** [comment]
I also encountered this bug.

I have several scenarios with this bug.

After monitoring the CPU usage with VS diagnostic tool It take about 2000ms to go throw 
GetPictureUrl method (IPictureService).

I have a service that retrieve products with pictures prices and more..

This bug is also reflected , but unfortunately it's not the only bug. I also found same behavior for the following methods:

GetFinalPrice (IPriceCalculationService)
GetProductPrice (ITaxService)

Last thing, I have a service that runs and deletes records (usually more than thousands for each run). After running the websites uses 90% CPU and the website crashes. 

I made a little investigation and found out that the problem comes form Nop.Data. EFReposidotry library.

I believe it's something with the new .Net Core 2.1 framework.

----
 
In order to simulate the environment you should use nopCommerce database 4.00 version and then to run the update script for 4.10 version.

In my opinion this bug is suitable for fatal status. Right now websites fall down after requesting one of the services that use theses methods.

**Comment by jc9999jc** [comment]
I found DynamicProxyGenAssembly2 --> Castle.Proxies.PictureProxy get_PictureBinary method with CPU time consumption of 90%

**Comment by skoshelev** [comment]
Hi @jc9999jc Can you open a new issue and add more detail of your problem?

**Comment by skoshelev** [comment]
Closed #3357

**Comment by jc9999jc** [comment]
OK.

You can go to PrepareProductListModel func from Nop.Web.Areas.Admin.Factories.ProductModelFactory

make the product search without page index: like this:

            //get products
            var products = _productService.SearchProducts(showHidden: true,
                categoryIds: categoryIds,
                manufacturerId: searchModel.SearchManufacturerId,
                storeId: searchModel.SearchStoreId,
                vendorId: searchModel.SearchVendorId,
                warehouseId: searchModel.SearchWarehouseId,
                productType: searchModel.SearchProductTypeId > 0 ? (ProductType?)searchModel.SearchProductTypeId : null,
                keywords: searchModel.SearchProductName,
                //pageIndex: searchModel.Page - 1, pageSize: searchModel.PageSize,
                overridePublished: overridePublished);

try to run it.

The result is that you will need to wait more than 15 minutes for list of 1000 items
