### ISSUE TITLE
Css bundling not working

### ISSUE THREAD

**Issue by bulutkartal** [nopSolutions/nopCommerce#3440]
nopCommerce version: 4.1

Steps to reproduce the problem: 
when you choose to bundle css it creates .css file but look for .min.css so returns 404.

**Comment by bulutkartal** [comment]
I guess min.css should be removed from here

`//render
                    result.AppendFormat("<link href=\"{0}\" rel=\"stylesheet\" type=\"{1}\" />", urlHelper.Content("~/bundles/" + outputFileName + ".min.css"), MimeTypes.TextCss);`

**Comment by Joebeazelman** [comment]
I am having the same issue as well.  It happens locally on my machine, but not on my live server.  It also happens with the Prisma theme from NopTemplates, but not the default theme. The problem is occuring in the following code:

                        _processor.Process(configFilePath, new List<Bundle> { bundle });

The BundleFileProcessor.Process method fails silently.

**Comment by LubovKhokhlova** [comment]
Hello!
This situation is not reproduced in our environment, in bundling mode, both files are created simultaneously - regular and .min.

**Comment by RomanovM** [comment]
It occurs in virtual directories. Regular bundled file is generated incorrectly and the minified one isn't created. Moved to https://github.com/nopSolutions/nopCommerce/issues/2674

**Comment by Joebeazelman** [comment]
I found a solution to my problem. It turns out that the BundlerMinifier library will silently fail with no file generated if it encounters a syntactical issue.  In my case, I had an extraneous character near the end of a file.

**Comment by croaton23** [comment]
I had a similar issue - minified css and js bundles didn't build in nopCommerce 4.20. I'm using it on Linux, so the problem in my case was with path generation. I managed to fix minification by replacing in file **PageHeadBuilder.cs** the line:

`var configFilePath = _hostingEnvironment.ContentRootPath + "\\" + outputFileName + ".json";`

with

`var configFilePath = _hostingEnvironment.ContentRootPath + Path.DirectorySeparatorChar + outputFileName + ".json";`

So that path is generated with a backslash in Windows and a forward slash in Linux. (Haven't tested on Windows, though)

**Comment by saeidmh83** [comment]
I had a same problem with nopCommerce v4.0. get latest version of BundlerMinifier.Core and my problem resolved.

**Comment by ParamjotSingh5** [comment]
I had similar issue - minified css bundles did'nt build in nopCommerce 4.0. I fixed it by changing the name of the file that is being sent back as resultant file name. 
Replace this line in file **PageHeadBuilder.cs**. "Remove `min` from file name"

`result.AppendFormat("<link href=\"{0}\" rel=\"stylesheet\" type=\"{1}\" />", urlHelper.Content("~/bundles/" + outputFileName + ".min.css"), MimeTypes.TextCss);
`

with 

`result.AppendFormat("<link href=\"{0}\" rel=\"stylesheet\" type=\"{1}\" />", urlHelper.Content("~/bundles/" + outputFileName + ".css"), MimeTypes.TextCss);`

so that resultant file points to generated file, not to the minified.

**Comment by ArturSprinter** [comment]
Today I encountered same problem in nopCommerce 4.40.0.
I enabled JS & CSS minification and for one CSS file `min` creation failed (of course silently without any errors, file is just missing).
