### ISSUE TITLE
Running nopCommerce in Web Farm Does Not Update installedPlugins.json Properly

### ISSUE THREAD

**Issue by toddca** [nopSolutions/nopCommerce#3451]
nopCommerce version: 4.1

Steps to reproduce the problem: 
1. Install nopCommerce on two web servers and configure to point to the same DB.
2. Install a plugin - the installedPlugins.json will be updated to include the name of this plugin on the server for which you are connected.

Note: the second web server still has the original installedPlugins.json with the original list of installed plug-ins prior to step #2.

Looking for a workaround/solution as well as any other issues running nopCommerce in a web farm.

**Comment by RomanovM** [comment]
Related task: https://github.com/nopSolutions/nopCommerce/issues/2494

**Comment by cvalerio** [comment]
If hosting environment is Windows, there are several workarounds to this:

1. Install plugin in each server manually: if small farm (2-3 servers) and/or you want to verify plugin is functioning before reattaching server to the farm, this is my preferred way; this also doesn't need any particular setup at server level;
2. Use DFS Replication to sync folders between server: useful in large farms, needs some setup and wise exclusions, but it should work (applications would still need manual restart in order to load new plugins, though...)
3. Use Jenkins or similar tools to deploy plugins and automatically restart applications: REALLY large farms, really complicated, but I think viable solution...

HTH

**Comment by toddca** [comment]
I would not use DFSR, updating one web app will start replication to occur and depending on the file/location being replicated the web apps on the other servers will be restarted constantly and impact your entire server farm. You are better off taking each machine out of the LB, updating it, and then putting it back into service.

As far as updating the installedPlugins.json - we usually do not install/uninstall plugins all that much in production, but when we do we do so on one machine, replicate the installedPlugins.json to the others and restart each web app. Have not had an issue to this point but that may depend on the plugins you use.

**Comment by skoshelev** [comment]
Closed #3451

**Comment by toddca** [comment]
@skoshelev - when storing in redis why do you give this key/value its own DB and why do you hardcode the DB Id? 

Also - why can't this just be stored in the SQL DB?

**Comment by skoshelev** [comment]
@toddca We cannot use the database to store these values, because the database may not be exists when caching should already work

**Comment by toddca** [comment]
When do you cache installed plugins when the Db does not exist? In fact, when do you even install plugins when the Db does not exist ???

-Todd
________________________________

**Comment by skoshelev** [comment]
Hi @toddca. I do not understand why you ask about plugins? The point is that caching may starts working even before database initialization, which means we can't save caching settings in it. As far as installation of plugins is concerned, they are installed after creating the main database structure.

**Comment by toddca** [comment]
Yes so why cant we cache the contents of installedPlugins.json in the DB?

-Todd
________________________________

**Comment by ianpowell2017** [comment]
@toddca, did you find out how to solve this?  I am trying to install nopCommerce in a web farm scenario.  I am trying to figure out the steps to load balance this in AWS
