### ISSUE TITLE
Setup failed: Value cannot be null.  Parameter name: hashAlgorithm

### ISSUE THREAD

**Issue by Leftyx** [nopSolutions/nopCommerce#3452]
nopCommerce version: 4.10

Steps to reproduce the problem: 

Create a database in Sql Server 2012 sp4
Publish NopCommerce on IIS (v 8.0) with a Nop-Template theme.
Run installation

![image](https://user-images.githubusercontent.com/171024/49665151-e964f900-fa4b-11e8-8c07-f44c97ec273d.png)

`CodeFirstInstallationService `calls `InstallCustomersAndUsers ` which, at some point, tries to resolve `ICustomerRegistrationService`:

```
//set hashed admin password
var customerRegistrationService = EngineContext.Current.Resolve<ICustomerRegistrationService>();
customerRegistrationService.ChangePassword(new ChangePasswordRequest(defaultUserEmail, false, PasswordFormat.Hashed, defaultUserPassword));
```
and calls `ChangePassword`.  

`CustomerRegistrationService` uses `_customerSettings` (CustomerSettings) in the constructor but the object is not resolved properly.

For hashed password the property `_customerSettings.HashedPasswordFormat` is empty.

In happens pretty much all the time but it works smoothly in debug on my local machine.

This is a trace of all the properties of `CustomerSettings` found in `CustomerRegistrationService.ChangePassword` ( **"HashedPasswordFormat": null** ) :

```
{
    "UsernamesEnabled": false,
    "CheckUsernameAvailabilityEnabled": false,
    "AllowUsersToChangeUsernames": false,
    "UsernameValidationEnabled": false,
    "UsernameValidationUseRegex": false,
    "UsernameValidationRule": null,
    "DefaultPasswordFormat": "Clear",
    "HashedPasswordFormat": null,
    "PasswordMinLength": 0,
    "UnduplicatedPasswordsNumber": 0,
    "PasswordRecoveryLinkDaysValid": 0,
    "PasswordLifetime": 0,
    "FailedPasswordAllowedAttempts": 0,
    "FailedPasswordLockoutMinutes": 0,
    "UserRegistrationType": "0",
    "AllowCustomersToUploadAvatars": false,
    "AvatarMaximumSizeBytes": 0,
    "DefaultAvatarEnabled": false,
    "ShowCustomersLocation": false,
    "ShowCustomersJoinDate": false,
    "AllowViewingProfiles": false,
    "NotifyNewCustomerRegistration": false,
    "HideDownloadableProductsTab": false,
    "HideBackInStockSubscriptionsTab": false,
    "DownloadableProductsValidateUser": false,
    "CustomerNameFormat": "0",
    "NewsletterEnabled": false,
    "NewsletterTickedByDefault": false,
    "HideNewsletterBlock": false,
    "NewsletterBlockAllowToUnsubscribe": false,
    "OnlineCustomerMinutes": 0,
    "StoreLastVisitedPage": false,
    "StoreIpAddresses": false,
    "SuffixDeletedCustomers": false,
    "EnteringEmailTwice": false,
    "RequireRegistrationForDownloadableProducts": false,
    "AllowCustomersToCheckGiftCardBalance": false,
    "DeleteGuestTaskOlderThanMinutes": 0,
    "GenderEnabled": false,
    "DateOfBirthEnabled": false,
    "DateOfBirthRequired": false,
    "DateOfBirthMinimumAge": null,
    "CompanyEnabled": false,
    "CompanyRequired": false,
    "StreetAddressEnabled": false,
    "StreetAddressRequired": false,
    "StreetAddress2Enabled": false,
    "StreetAddress2Required": false,
    "ZipPostalCodeEnabled": false,
    "ZipPostalCodeRequired": false,
    "CityEnabled": false,
    "CityRequired": false,
    "CountyEnabled": false,
    "CountyRequired": false,
    "CountryEnabled": false,
    "CountryRequired": false,
    "StateProvinceEnabled": false,
    "StateProvinceRequired": false,
    "PhoneEnabled": false,
    "PhoneRequired": false,
    "FaxEnabled": false,
    "FaxRequired": false,
    "AcceptPrivacyPolicyEnabled": false,
    "$type": "CustomerSettings"
}
```

**Comment by PrasadHettiarachchi** [comment]
Hi 

I have tried to Deploy 4.10 on a Plesk based Windows Server Environment and I got the Following Errors in the Order they are Listed below

_____________________________

- First Try

 Setup failed: Cannot find the object "dbo.QueuedEmail" because it does not exist or you do not have permissions.

I have Read / Write Access to the MS SQL Server DB form the DB user name. 

2nd Try from where it stooped above
Setup failed: Value cannot be null. Parameter name: hashAlgorithm

3rd and Subsequent Tries from where it stooped above
Setup failed: Sequence contains more than one element

__________________________

However, I do not get any errors during Setup of Version 4.0 on the same environment. 

Hope this Helps

Thanks and Regards

Prasad

**Comment by hojatallahkazemi** [comment]
[Solved]
This bug is due to a file access error that is not handled by the code
To resolve this issue, remove the files and folders and folder's items from read-only mode.
Presentation\Nop.Web\wwwroot\images\thumbs,
Presentation\Nop.Web\web.config
Of course, read-only mode may be re-created for these files and folders, which you must remove read-only mode.

**Comment by hojatallahkazemi** [comment]
**[Solved]**
This bug is due to a file access error that is not handled by the code
To resolve this issue, remove the files and folders and folder's items from read-only mode.
Presentation\Nop.Web\wwwroot\images\thumbs,
Presentation\Nop.Web\web.config
Of course, read-only mode may be re-created for these files and folders, which you must remove read-only mode.
