### ISSUE TITLE
Rounding Discount Overstates or Understates Actual Discount Amount

### ISSUE THREAD

**Issue by toddca** [nopSolutions/nopCommerce#3610]
nopCommerce version: 4.10

Steps to reproduce the problem: 
1. Configure a store with default currency of Euro
2. Set an alternate currency of British Pound
3. Create product with price and map to a discount such as 10 euro off.
4. Using British Pound add product to cart and add promo code to apply discount.
5. For British Pound use round up .05 rounding.

My product has a price of 68.40 pounds and with the 10 Euro discount this is a 8.55 pounds discount once the currency conversation is calculated, for a final price of 59.85. 
68.40-8.55 = 59.85

However the 'your save' amount is 8.60 pounds.

The issue is the amount shown in the "you save" {discount} -- this is built in the cartItemModel.Discount - the root problem is when we call FormatPrice() the discount gets rounded which is not correct. Rounding this value, for my case, overstates the discount being given to the user.

We actually use a custom rounding method but the repro here is based on default rounding methods - it really does not matter, any rounding is incorrect here. I do not see a way to format a price without invoking rounding.

**Comment by DmitriyKulagin** [comment]
Not reproduced on latest version 4.20

Test data are as follows:
  - the amount of goods 80 euros
  - the ratio of the relationship between currencies 0.855 (apparently this is the same as yours - I clarify to bring complete clarity.)
  - rounding is more than 0.05 (0.06 rounding to 0.10)
So we get a discount of 68.40 - (10 * 0.855) = 59.85 which will be displayed in "you save"

Perhaps the problem is that you use a custom method of rounding. Or to the results added taxes. Describe step by step what settings you use when the problem is still relevant.
