### ISSUE TITLE
Nivo slider plugin is not install

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#3733]
nopCommerce version: 4.20 beta

Steps to reproduce the problem: 

1) i've downloaded 4.20 beta no source version.

2) deployed in local IIS

3) Go Local plugins.

4) I found that nivo slider plugin is not installed.

I thought that you guys set pre uninstall as it is.

5) After try to install and restart application 2-3 times but it still shows like below pictures.

Also, i didn't see any new entity at setting table for nivo slider .

![nivo](https://user-images.githubusercontent.com/41533502/56915426-1afe5f80-6ad4-11e9-949e-99efaeae66a2.PNG)

**Comment by davidandrewpowell** [comment]
I believe this issue is occurring in `NivoSliderPlugin.Install()` in:

`var sampleImagesPath = _fileProvider.MapPath("~/Plugins/Widgets.NivoSlider/Content/nivoslider/sample-images/");`

This line returns a path without a trailing /.

Then the code segments:

`sampleImagesPath + "banner1.jpg"`

and

`sampleImagesPath + "banner2.jpg"`

will then give incorrect paths.

I would suggest using `Path.Join(sampleImagesPath, "banner1.jpg")` to join the paths rather than using string concatenation.

**Comment by davidandrewpowell** [comment]
I've created pull request [3757](https://github.com/nopSolutions/nopCommerce/pull/3757) to help fix this issue.  I've just realized that someone is assigned to this issue so apologies if this causes any confusion.

Please note that the pull request contains 2 commits.  The first directly fixes this issue.  The second is a refactoring of the `Install()` and `Uninstall()` methods to simplify the methods (see commit message).

**Comment by yuessir** [comment]
I have the same issue.

**Comment by davidandrewpowell** [comment]
Please ignore my last comment above regarding pull request [3757 ](https://github.com/nopSolutions/nopCommerce/pull/3757). I have just realised that we have a `NopFileProvider.Combine(string[])` as an abstraction of `Path.Combine(string[])` so I have changed the PR to use this library instead of using `Path.Combine` directly.  I also removed the commit to refactor the class in order to simplify the PR (I will commit this refactoring in the future).

The commit that I have made is now consistent with how paths are joined in the rest of the application and will fix the issue, However, I should point out that even though the path joining was an issue, I do not believe it was the reason that the issue occurred.

It seems that the reason this issue occurred was due to `NopFileProvider.MapPath(string path)` removing the trailing forward slash from the path.  If we look to commit [234c85a4 ](https://github.com/nopSolutions/nopCommerce/commit/234c85a4d6b5110030368de5908c78274cbc184d) by @RuS984 we can see that the following version of `MapPath` (and its associated dependency on `Combine(string)`):

```
public virtual string MapPath(string path)
{
    path = path.Replace("~/", string.Empty).TrimStart('/');
    return Combine(BaseDirectory ?? string.Empty, path);
}

public virtual string Combine(params string[] paths)
{
    var path = Path.Combine(paths.SelectMany(p => p.Split('\\', '/')).ToArray());

    if (path.Contains('/'))
        path = "/" + path;

    return path;
}
```

I believe that it is this commit that has introduced this bug.  In the previous commit, `Combine(string[])` was defined as:

```
public virtual string Combine(params string[] paths)
{
    return Path.Combine(paths);
}
```

I believe this new functionality is trying to combine the new path using separators that are dependent on the current OS but I still have the following questions for @RuS984 :

1. Is it okay that this functionality is removing the trailing slash?  Could the issue that is occurring here be occurring anywhere else in the application?

2. Is the following code segment correct?:

```
if (path.Contains('/'))
        path = "/" + path;
```

It is not clear from reading the code (to me anyway) in what circumstance you would want to add a leading forward slash.  Where in the path are you looking for a '/' to then justify adding a '/' one to the beginning on the path?

Thank you

**Comment by RomanovM** [comment]
@davidandrewpowell Thanks for the contribution. You can create a new issue to discuss MapPath method implementation. I close this task about Nivo slider plugin installation.
