### ISSUE TITLE
Product Tier price Edit pop up is not display(can't able to edit)

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#3765]
nopCommerce version: 4.20 beta

Steps to reproduce the problem: 
1) setup at local IIS

2) go Admin/Product/Edit/40

3) Click on tier price and directly click on save button without anything change from this pop up.

4) Edit that record it should open Tier price in edit mode but it redirect to Product list page.

https://www.loom.com/share/8c613ad3bba0420ea58d5d16980d896e

**Comment by davidandrewpowell** [comment]
On clicking the Tier Price edit button it should be calling:

`public virtual IActionResult TierPriceEditPopup(int id)`

but instead it is calling:

`public virtual IActionResult ProductAttributeCombinationEditPopup(int id)`

The prices partial `_CreateOrUpdate.Prices.cshtml` (which displays the tier prices) contains the javascript function:

```
function renderColumnEdit(data, type, row, meta) {
    return '<button onclick=\"javascript:OpenWindow(\'@Url.Content("~/Admin/Product/TierPriceEditPopup/")' + data + '?btnId=btnRefresh&formId=product-form\', 800, 600, true); return false;\" class="btn btn-default"><i class="fa fa-pencil"></i>@T("Admin.Common.Edit")</button>';
}
```

The URL here is correct, so why is it calling the wrong action?

Because, the partial `_CreateOrUpdate.ProductAttributes.Combinations.cshtml` contains the following javascript function:

```
function renderColumnEdit(data, type, row, meta) {
    return '<button onclick=\"javascript:OpenWindow(\'@Url.Content("~/Admin/Product/ProductAttributeCombinationEditPopup/")' + data + '?btnId=btnRefreshCombinations&formId=product-form\', 800, 700, true); return false;\" class="btn btn-default"><i class="fa fa-pencil"></i>@T("Admin.Common.Edit")</button>';
}
```

This function has the same name and because both of these partials are rendered together by the `_CreateOrUpdate.cshtml` partial, the names clash and this unexpected result occurs.  Additionally, there is another `renderColumnEdit()` function in the `_CreateOrUpdateProductAttributeMapping.Values.cshtml` partial but I'm not sure if this is causing an issue or not.

To prevent this issue I would therefore recommend updating the method names.  Additionally, I have identified a number of other 'render' methods used in the `_CreateOrUpdate` partials so I would recommend changing these also to prevent future naming collisions also.

I would recommend using the following method names instead:

**`_CreateOrUpdate.Pictures.cshtml`:**
    renderColumnProductPictureUrl -> renderPicturesColumnProductPictureUrl

**`_CreateOrUpdate.Prices.cshtml`:**
    renderColumnEdit -> renderPriceColumnEdit

**`_CreateOrUpdate.ProductAttributes.Combinations.cshtml`:**
    renderColumnPrice -> renderProductAttributesCombinationsColumnPrice 
    renderColumnAttributesXml -> renderProductAttributesCombinationsColumnAttributesXml 
    renderColumnEdit -> renderProductAttributesCombinationsColumnEdit 

**`_CreateOrUpdate.StockQuantityHistory.cshtml`:**
    renderQuantityAdjustment -> renderStockQuantityHistoryQuantityAdjustment 

**`_CreateOrUpdateProductAttributeMapping.Values.cshtml`:**
    renderColumnEdit -> renderProductAttributeMappingValuesColumnEdit

**Comment by davidandrewpowell** [comment]
Please see [pull request 3765](https://github.com/nopSolutions/nopCommerce/pull/3785) which fixes this above issue as described.

**Comment by davidandrewpowell** [comment]
See also issue [3786](https://github.com/nopSolutions/nopCommerce/issues/3786).
