### ISSUE TITLE
All Settings (advanced) - don't allow to edit "store" column

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#3769]
nopCommerce version: 4.2 beta

Steps to reproduce the problem: Edit record in All Settings, and try edit store column.
![err1](https://user-images.githubusercontent.com/17789934/57129404-24ddc800-6d4b-11e9-98a8-e2f16104f670.PNG)

**Comment by tigran-avdalyan** [comment]
And missing "Resource name" Value in English Language

**Comment by RomanovM** [comment]
It's by design. There is no way to using dropdownlist editor in DataTables. You can delete the old record and create the new one if you want to change store of the settings.
What about missed locales, just run last S[QL upgrade script](https://github.com/nopSolutions/nopCommerce/blob/develop/upgradescripts/4.10-4.20%20(under%20development)/upgrade.sql)
