### ISSUE TITLE
Remove Nop.Tests/TestExtensions and replace with FluentAssertions

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#3833]
Source: https://www.nopcommerce.com/boards/t/63365/suggestion-remove-nopteststestextensions-and-replace-with-fluentassertions.aspx

**Comment by davidandrewpowell** [comment]
As mentioned in the link above, we already have abstractions around `NUnit.Framework.Assert` tests in the following nopcommerce libraries:

[Nop.Tests/ExceptionAssert.cs](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Tests/Nop.Tests/ExceptionAssert.cs)
[Nop.Tests/TestExtensions.cs](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Tests/Nop.Tests/TestExtensions.cs)
[Nop.Tests/TypeAssert.cs](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Tests/Nop.Tests/TypeAssert.cs)

For example, the `TestExtensions` library has a method:

```
public static T ShouldNotBeNull<T>(this T obj)
{
    Assert.IsNotNull(obj);
    return obj;
}
```

which would call in our test as:

`result.ShouldNotBeNull();
`

This works fine for those tests that we have.  However, I feel that switching to FluentAssertions instead of using our own libraries would offer the following benefits:

**1. Readability & Expressability**

For some of the tests we have in nopcommerce (such as the one mentioned above), FluentAssertions does not offer much readability benefit.  For example:

In nopcommerce: `result.ShouldNotBeNull();`
vs in FluentAssertions: `result.Should().NotBeNull();`

I would switch to FluentAssertions based on this alone. But there are are some tests where it does improve readability.  For example:

In Nopcommerce:
```
ExceptionDelegate action = () => subject.Foo("Bar");
ExceptionAssert.Throws(typeof(ArgumentException), action);
```

vs FluentAssertions:
```
Action action = () => subject.Foo("Bar");
action.Should().Throw<ArgumentException>();
```

I hope you would agree that this last test is slightly more readable.

Note: In addition, FluentAssertions offers other test alternatives around test exceptions:
```
action.Should().Throw<ArgumentException>().WithMessage("whatever");
action.Should().Throw<ArgumentException>().WithInnerException<ArgumentException>();
action.Should().Throw<ArgumentException>().WithInnerException<ArgumentException>().WithMessage("whatever");
action.Should().Throw<ArgumentNullException>().Where(e => e.Message.StartsWith("did"));
action.Should().Throw<ArgumentNullException>().And.ParamName.Should().Be("message");
action.Should().NotThrow();
action.Should().NotThrow<InvalidOperationException>();
```
etc.


**2. The [FluentAssertions github](https://github.com/fluentassertions/fluentassertions) library continues to be maintained.**

The purpose of the FluentAssertions library is to do one job (test framework abstractions) and to do that job well.   Nopcommerce has a different focus so why not instead use the external test framework.


**3. The FluentAssertions library has unit tests.**

For those that are interested, these unit tests can be seen [here](https://github.com/fluentassertions/fluentassertions/tree/master/Tests/Shared.Specs).

I believe that in nopcommerce, the `ExceptionAssert` class has some unit tests (also in the same class file) with some commented out tests so I'm not sure (without looking though) how relevant these are.  I don't believe that the `TestExtensions` and `TypeAssert` classes have unit tests.

This may explain why in nopcommerce we have the following tests in Nop.Tests/TestExtensions:

```
public static T ShouldNotNull<T>(this T obj)
{
    Assert.IsNull(obj);
    return obj;
}

public static T ShouldNotNull<T>(this T obj, string message)
{
    Assert.IsNull(obj, message);
    return obj;
}
```

Test usage would therefore be:

```
object result = new object();
result.ShouldNotNull();
```

However, this test would (in my opinion) unexpectedly fail as it actually tests this is null.  Maybe this is a badly worded test perhaps but we do also have `ShouldNotBeNull()` and `ShouldBeNull()` tests in the framework so I'm not quite sure the purpose of these existing tests.  I would like to think that a test driven approach to this framework would have driven out these duplicate tests and poor (IMHO) naming.


**4. FluentAssertions offers a more extensive number of test assertion abstractions**

I would recommend you take a look at the [documentation](https://fluentassertions.com/documentation/) to see what is offered.

But some random quick examples include:

```
result.Should().BeGreaterThan(4);
result.Should().NotBe(10);
result.Should().BeInRange(1, 10);
result.Should().BeNegative();
result.Should().BeOneOf(new[] { 3, 6});
result.Should().BeBefore(2.March(2010));
result.Should().NotBeAfter(2.March(2010));
result.Should().NotBeSameDateAs(2.March(2010));
result.Should().NotHaveYear(2011);
result.Should().BeAtLeast(2.Days()).Before(deliveryDate); 
result.Should().BeInAscendingOrder(x => x.SomeProperty);
```
and many many more.

**Comment by davidandrewpowell** [comment]
For those interested, I have created PR [3836](https://github.com/nopSolutions/nopCommerce/pull/3836) to help aid the discussion.

The pull request is (in my opinion) a complete implementation so if you do decide to implement this in nopcommerce then you should be able to merge this straight into develop.

I will keep an eye on the branch to make sure it is maintained should anyone add any new tests outside of this.

**Comment by skoshelev** [comment]
Hi @davidandrewpowell. Thank you for your analyzing and code
