### ISSUE TITLE
Possible issues with System.Drawing on Linux

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#3842]
We started doing some Linux testing and found out that you are using Bitmap and Image classes in  FileRoxyFilemanService.cs.

Please note that System.Drawing is not supported on Linux   (unless you do some sudo stuffs) and you better use some other library instead. 
So now for example the file upload in the editor is not working on Linux (and a lot of other functionality from the editor too).

p.s: Just noticed that you already use ImageSharp so you can change the code to use it instead.

Source: https://www.nopcommerce.com/boards/t/61916/nopcommerce-420-feedback-and-improvements.aspx#231890

See also: https://github.com/dotnet/corefx/issues/20325

**Comment by tigran-avdalyan** [comment]
https://photosauce.net/blog/post/5-reasons-you-should-stop-using-systemdrawing-from-aspnet

**Comment by skoshelev** [comment]
We cannot refuse to use the System.Drawing.Common since this library is required for the operation of other modules important to us: EPPlus and iTextSharp. For UNIX compatible systems, two packages are required: libgdiplus and libc6-dev. Details can be found in[ this ticket](https://github.com/dotnet/runtime/issues/27200)

Closed #3842
