### ISSUE TITLE
4.20 Square Plugin - 

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#3920]
nopCommerce version: 
4.20

Issue:
Square Plugin requires "sandbox-" for the Access Token in the Sandbox mode. But in current Square up, the token may not have or does not have "sandbox-" mine doesn't, see screenshot

Steps to reproduce the problem: 
1) log into square
2) go into credentials
3) hit Replace Token under the sandbox section
4) dopes not have sandbox-

Resolution:
Remove the "sandbox-" validation

![square](https://user-images.githubusercontent.com/20989983/58748392-0c45f800-8446-11e9-9499-ca13081c03ca.PNG)

**Comment by cunnpole** [comment]
You can get it to work if you fudge the values manually via the Admin/Setting/AllSettings and search for square. I'd suggest you backup your database first though

**Comment by Ochapparel** [comment]
Yeah I did. Just figured I’d let them know it’s not mandatory and could remove that validation

**Comment by DmitriyKulagin** [comment]
Closed #3920

**Comment by garrie007** [comment]
Hi,

Do these changes actually make this plugin work, had no luck with the square plugin that comes with nop 4.20 from the webite.

"An error occurred while obtaining an access token and One or more errors occurred. (A task was canceled.) & "Choose your business location. Location is a required parameter for payment requests."

I have tried using sandbox mode but did not work either.

Square payment error: Error calling ListLocations: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

Regards

**Comment by RomanovM** [comment]
@garrie007 These changes are only related to access token management. But looking at your log, your error is related to LocationsApi. 
Check again that you have configured the plugin correctly.
If the error will be repeated, try to contact Square support with this question, since with our test credentials everything works as it should.

**Comment by garrie007** [comment]
> @garrie007 These changes are only related to access token management. But looking at your log, your error is related to LocationsApi.
> Check again that you have configured the plugin correctly.
> If the error will be repeated, try to contact Square support with this question, since with our test credentials everything works as it should.

Hi,

Thank you for the reply.

Regards
