### ISSUE TITLE
Add Instagram to default social media links

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#3997]
Let's add a new social network to admin area > configuration > general settings > Social media block. The field (input) name will be "Instagram URL" and the hint will be "Specify your Instagram page URL. Leave empty if you have no such page." No default value is required during the installation.

Then display this block in public store (if a page URL is entered). We can use the same [sprite image](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Themes/DefaultClean/Content/images/social-sprite.png) but replace [removed](https://github.com/nopSolutions/nopCommerce/issues/3597) g+ icon to the instagram one.

Source: https://www.nopcommerce.com/boards/t/40409/instagram-url.aspx?p=2#242498

See also: https://github.com/nopSolutions/nopCommerce/issues/2087

**Comment by pillbug22** [comment]
Agreed; we had done the same on previous versions (replaced G+ with IG logo and URL), and now had to modify the footer view to include it again once G+ was removed.

Bonus would be to make the footer icon section more flexible by creating your own list instead of a pre-determined list of social sites. We also custom added LinkedIn, and other nopCommerce admins may have even other sites they want to link to.
