### ISSUE TITLE
Make "buy now" redirect to login page if customer is not logged in.

### ISSUE THREAD

**Issue by rollsch** [nopSolutions/nopCommerce#4049]
Make "buy now" redirect to login page if customer is not logged in. Make it configurable on the order settings

Currently if you do not enable anon purchases (required by us) then there is no purchase button and it is not intuitive that they must register/login to purchase. 

Is there anyway we could still have the buy now button but force the user to login/register if they click it?

**Comment by kenanilgun** [comment]
> We already have our own plugin, so I can implement it myself when I get time. Thanks for the offer. I assume you would charge for this?

Roland, I can try with small effort, no problem charge.

**Comment by kenanilgun** [comment]
Hi Ronald, 

I developed some plugin and theme on nopCommerce 4.0, Can you check plugin features. If you need like that this we can talk about it

https://github.com/kenanilgun/nopCommerce/tree/issue-4049

Have a good work.

**Comment by kenanilgun** [comment]
Hi Ronald, Did you look plugin?

**Comment by AndreiMaz** [comment]
@rolandh Hi Ronald, what exactly "buy now" button do you mean? "add to cart"? Please clarify

**Comment by rolandh** [comment]
Yes the add to cart button.

**Comment by glhays** [comment]
Would that not redirect a guest from adding to the cart?
________________________________

**Comment by rolandh** [comment]
So the issue is we must have our users register/sign up before buying, but some of them are very IT illiterate and struggle with the process as we have disabled anonymous checkout.

Even if we put in massive bold text "PLEASE REGISTER AND SIGN IN BEFORE PURCHASING" they don't know what to do.

If we could make the "add to cart" button when not logged in redirect to the register page and then redirect back to the purchase page. Or somehow other improve this flow it would help with getting more purchases.

There are a few other improvements like a proper 1 page checkout, instead of the current "Use one page checkout" which still requires you to press next at least 3x which would also help improve sales.

**Comment by glhays** [comment]
I get it! And as well have disabled anonymous checkout. But a guest who may purchase, is still a potential customer. No perfect solution for all scenarios I guess.
________________________________

**Comment by AndreiMaz** [comment]
@rolandh Sorry,  but I still don't fully understand the issue. This how it works now
1. You disable anonymous checkout
2. A customer adds some product to the cart. Or multiple products (still not logged in)
3. There's a "checkout" button on the shopping cart page. When a customer clicks it, he's redirected to the login page where it's required to login or register
Usually it works this way (require a login before the checkout, not before adding to the cart)

BTW, regarding your suggestion with a proper 1 one checkout. Here is a work item - https://github.com/nopSolutions/nopCommerce/issues/4849

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box.
