### ISSUE TITLE
Pictures in Nivo Slider are not HTTPS secured

### ISSUE THREAD

**Issue by liqili** [nopSolutions/nopCommerce#4109]
nopCommerce version: 4.30

Steps to reproduce the problem: 

I'm using Nginx as a proxy and enabled https. However, the pictures in Nivo Slider are not https secured.

**Comment by liqili** [comment]
Eventually solved by change the line below:
`        public virtual string GetStoreHost(bool useSsl)
        {
            if (!IsRequestAvailable())
                return string.Empty;

            //try to get host from the request HOST header
            var hostHeader = _httpContextAccessor.HttpContext.Request.Headers[HeaderNames.Host];
            if (StringValues.IsNullOrEmpty(hostHeader))
                return string.Empty;

            //add scheme to the URL
//            var storeHost = $"{(useSsl ? Uri.UriSchemeHttps : Uri.UriSchemeHttp)}{Uri.SchemeDelimiter}{hostHeader.FirstOrDefault()}";
            var storeHost = $"//{hostHeader.FirstOrDefault()}";

            //ensure that host is ended with slash
            storeHost = $"{storeHost.TrimEnd('/')}/";

            return storeHost;
        }`

**Comment by DmitriyKulagin** [comment]
Hi @liqili,
Your solution method looks too radical, but this is not the root cause that the pictures are sent via the http protocol. We do not have accurate information about configuring Nginx, but when you enable SSL in IIS, image requests go off over the https scheme. Try to track what result the `_webHelper.IsCurrentConnectionSecured()` method will check, maybe you just need to activate the "UseHttpClusterHttps/UseHttpXForwardedProto" settings in the `appsettings.json` file

**Comment by DmitriyKulagin** [comment]
@liqili Only in Nivo Slider images are not protected by https or is this applicable to the entire store?

**Comment by AndreiMaz** [comment]
Cannot reproduce the issue
