### ISSUE TITLE
64bit x64 support

### ISSUE THREAD

**Issue by rolandh** [nopSolutions/nopCommerce#4159]
nopCommerce version: 4.00

We are using version 4.00 still however this question is relevant for the latest version as well.

Can we change to compile for x64 instead of x32? We have a large cache which we would like to take advantage of a very big in memory store if possible.

Are there any reason why x32 is selected by default? I read somewhere that performance was better and that was why. Is this the only reason? Any other problems?

**Comment by skoshelev** [comment]
Hi @rolandh.

There is another reason why we use x86 architecture. All our libraries are built with the "Any CPU" modifier except Nop.Web. This is due to the fact that there the NuGet package for libuv  is no contains  assemblys for "Any CPU". And we cannot choose x64 instead of x86 due to the fact that many users still use systems based on this architecture.

Despite the above, we don't see any reason why you can't change the architecture for your project at x64

**Comment by rolandh** [comment]
That explains a lot. I tried Any CPU and it did not work and I did not know why at the time, but x64 appears to work perfectly.

Thanks for the reply,
