### ISSUE TITLE
Hide unused footer sections

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#4176]
nopCommerce version: 4.2

Steps to reproduce the problem: in footer we have 4 sections 
1."Information", 
2."Customer service", 
3."My account" , 
4."Follow us"
Needs to hide section if section haven't items(we disable in General settings>>Footer items)
or we haven't any Social Media page.

**Comment by gschechter** [comment]
The titles of the footer sections are pulled from string localization,  you can set them to HTML whitespace `&nbsp;` via http://yoururl/Admin/Language/Edit/ by searching for `footer.` (the period helps find the exact resource). 

The best thing is to modify the footer view in in `\Presentation\Nop.Web\Views\Shared\Components\Footer\Default.cshtml `

Wrapping the foot-block with conditional's for the content inside being displayed.
`@if (Model.DisplaySitemapFooterItem || Model.DisplayContactUsFooterItem)
        {
            <div class="footer-block information">
                <div class="title">
                    <strong>@T("Footer.Information")</strong>
                </div>
                <ul class="list">
                    @if (Model.SitemapEnabled && Model.DisplaySitemapFooterItem)
                    {
                        <li><a href="@Url.RouteUrl("Sitemap")">@T("Sitemap")</a></li>
                    }
                    @foreach (var topic in Model.Topics.Where(x => x.IncludeInFooterColumn1).ToList())
                    {
                        <li><a href="@Url.RouteUrl("Topic", new { SeName = topic.SeName })">@topic.Name</a></li>
                    }
                    @if (Model.DisplayContactUsFooterItem)
                    {
                        <li><a href="@Url.RouteUrl("ContactUs")">@T("ContactUs")</a></li>
                    }
                </ul>
            </div>
        }`

I believe the Nop way of doing this would be add to the FooterModel a series of bool's to display those sections, and have it set the properties in the ModelFactory placing the new conditionals in the model factory instead of the View.

**Comment by tigran-avdalyan** [comment]
![1111](https://user-images.githubusercontent.com/17789934/69801593-06f91880-11f1-11ea-9f13-96e58e084b8f.png)

**Comment by gschechter** [comment]
Here are a few things I'd like to do to implement this.
- [ ] Change "footer column" to "footer section"
- [ ] Footer will display the "sections" as an unlimited number of integers if non exist (or are hidden) the section doesn't get displayed,  new DB table
- [ ] Use footer items to track links,  new DB table
- [ ] Change topic's to be assigned a footer section instead of 3 limited columns, change DB table remove 3 bools and 1 int field.
- [ ]  Change Admin/ _GeneralCommon.FooterItems.cshtml to use two grids,  one for the sections, and the other for control of items (including the topics that are set elsewhere to display in the footer, can change the footer section here or remove them from a footer to be re-added on the topics Admin).

Doing all of this is the _correct_ way to do it in my eyes.  It would be much cleaner than just adding more booleans for hiding the "columns",  and would let the user have more level of customization without getting into the cshtml file.   

However it would mean a breaking change for any custom themes that are using the FooterModel,  or leaving redundant attributes in place that would need to be removed when breaking changes were appropriate.

**Comment by AndreiMaz** [comment]
After some consideration we've decide not to implement this functionality and leave it for customization.
