### ISSUE TITLE
Reduce LocaleStringResource entries for "Name"

### ISSUE THREAD

**Issue by ryanbarlow1** [nopSolutions/nopCommerce#4256]
nopCommerce version: 
4.2

Steps to reproduce the problem: 

I'm currently working on building a plugin and I realized how many times duplicate English entries are in the LocaleStringResource table. For example, in the default v4.2 install there are 61 entries with the ResourceValue of "Name". Couldn't we simplify most of these by creating a Common.Name entry in the table and referencing that instead?

Also, this isn't the only occurance where this is happening. You can see this if you run this SQL query:
```SELECT COUNT(ResourceValue) AS Counts, ResourceValue FROM LocaleStringResource GROUP BY ResourceValue ORDER BY Counts DESC```

I've attached a screenshot with the top 20 results of this query as well:
![results](https://user-images.githubusercontent.com/24322375/72094941-b804cf80-32d4-11ea-940b-4ce1a48a70eb.PNG)

Thanks!

**Comment by gschechter** [comment]
I believe the string resources appear to have duplicates because in some languages those might be different words versus in English we use the same word to describe multiple things.   I am not a linguist but I think these examples will help explain it.

https://www.spanishdict.com/translate/name

>  la figura
All of the biggest names in fashion are going to be at the show.Todas las más importantes figuras de la moda van a estar en la presentación.

> el nombre
My name is James.Mi nombre es James.

**Comment by AndreiMaz** [comment]
gschechter  is absolutely right. We have to leave it for other languages
