### ISSUE TITLE
Status of 4.2 vulnerabilities?

### ISSUE THREAD

**Issue by jackfagner** [nopSolutions/nopCommerce#4297]
nopCommerce version: 4.2

What is current status of the following vulnerabilities, all published during last year?
I can't find any details of these issues in this repository.

CVE-2019-11519
CVE-2019-19682
CVE-2019-19683
CVE-2019-19684
CVE-2019-19685

Source:
https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=nopCommerce

**Comment by AndreiMaz** [comment]
@DmitriyKulagin https://github.com/nopSolutions/nopCommerce/issues/3713

**Comment by DmitriyKulagin** [comment]
@jackfagner 
CVE-2019-19684 - in fact it is not a security issue and is determined by the security of downloadable plugins
CVE-2019-19682 The HTML content editor in the secure administration area is open only to administrators, therefore this is not considered a real vulnerability scenario
CVE-2019-11519 Fixed with e2bba46
All vulnerabilities of RoxyFileman are resolved [here](https://github.com/nopSolutions/nopCommerce/commit/7d9f4bf5b8de15c5828043ac7005bc7bef2a9544)

**Comment by rolandh** [comment]
"All vulnerabilities of RoxyFileman are resolved here"

Can we get a list of which versions of nopcommerce are affected? Are earlier versions vulnerable?
