### ISSUE TITLE
Tier Price deleted after Editing

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#4298]
nopCommerce version: 4.20
>I found the Tier Price gets deleted after editing it. Creation and deletion of the Tier Price work fine. Changing 'Customer Role' along with 'Price' prevents the issue from time to time but not guaranteed.

Source: https://www.nopcommerce.com/boards/topic/78132/nopcommerce-42-tier-price-gets-deletec-after-editing

**Comment by holydk** [comment]
It's already fixed in 4.30 version. Closed #4298

**Comment by Mehnock** [comment]
Can this be fixed for 4.2?  We are not planning on switching to 4.3 yet and this bug is a show stopper for us.

**Comment by Mehnock** [comment]
I created a workaround that may help determine the source of the problem.  It's described here:
https://www.nopcommerce.com/en/boards/topic/78132/nopcommerce-42-tier-price-gets-deletec-after-editing/page/2#265956

In case you can take a look.

What I found is that if we send the tierPrice entity to the context with a null CustomerRole [virtual] property, the context deletes the tierPrice instead of updating it, even though the CustomerRoleId property is set.  I think this is a bug in the EFCore but my workaround works but ensuring we don't send a null CustomerRole back to the context.
