### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by patsadow2** [nopSolutions/nopCommerce#4299]
nopCommerce version: 4.20

Hello I am using K8S with docker and let's encrypt on K8S and after enabling SSL i have problem
ERR_TOO_MANY_REDIRECTS

I've also used

```
  "Hosting": {
    //Set to "true" the settings below if your hosting uses a load balancer. It'll be used to determine whether the current request is HTTPS
    "UseHttpClusterHttps": true,
    "UseHttpXForwardedProto": true,

    //Use the setting below if your hosting doesn't use "X-FORWARDED-FOR" header to determine IP address.
    //In some cases server use other HTTP header. You can specify a custom HTTP header here. For example, CF-Connecting-IP, X-FORWARDED-PROTO, etc
    "ForwardedHttpHeader": ""
  },

```

  select * from [nopcommerce3].dbo.Setting s where s.name = 'securitysettings.forcesslforallpages'
Value True

![image](https://user-images.githubusercontent.com/19226186/74873535-b01e5d80-535f-11ea-8cc5-2bb0342e86a7.png)

Any idea how to solve it ?

**Comment by nguyenhthai** [comment]
Actually I ran into this issue recently when deploying into Azure VM that sits behind a load balancer. When I followed the comment in the appsettings.json file for configuration under load balancer, this issue came up. After a few tries, I discovered that the first option was actually the cause since it is expecting the property "**HTTP_CLUSTER_HTTPS**" with value "**on**" within the header and I don't think Azure load balancer even setting up to use that property. So even if that mentions to set both to true, I don't think that it apply to all the scenarios. And also the naming is quite confusing.

So in your case, you can try to leave "**UseHttpClusterHttps**" as false and see if that helps. The other setting "**UseHttpXForwardedProto**" can be turn on if you actually use the X-FORWARDED-FOR in the header, otherwise, it will be default to X-FORWARDED-PROTO.

**Comment by patsadow2** [comment]
Thanks :)
