### ISSUE TITLE
ANCM Failed to Load dll error on host site on SmarterAsp

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4412]
nopCommerce version: 4.30 Beta

Steps to reproduce the problem: 
Getting error **ANCM Failed to Load dll** after deploy 4.30 Beta on SmarterAsp

![0](https://user-images.githubusercontent.com/13154058/78024210-9cf6a880-7375-11ea-95e2-adc950f25136.png)

**Comment by rajupaladiya** [comment]
This is resolved by change AspNetCoreModuleV2 to AspNetCoreModule in web.config

Old Line
`  <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />`

New Line
`  <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />`

**Comment by DmitriyKulagin** [comment]
@rajupaladiya I published the site locally, on IIS 10 and everything worked. Perhaps the solution to your problem may be to complete the following steps:
1. Take the last build from the "develop" branch
2. check [this](https://docs.microsoft.com/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-3.1#50032-ancm-failed-to-load-dll)
3. This might be caused by a bitness mismatch between IIS application pool and published application
 - Open IIS manager - Application Pool - Select App pool - Advanced Settings
 - Update “Enable 32 bits applications” from false to true

**Comment by rajupaladiya** [comment]
@DmitriyKulagin - As I mentioned in the task, this error getting on [SmarterAsp.Net](https://www.smarterasp.net/), not in IIS in local machine.

**Comment by DmitriyKulagin** [comment]
@rajupaladiya   I understand that you are trying to publish the application on SmarterAsp hosting, but it seems to me that the problem is in the configuration conflict between the application settings and the hosting. Above, I have already described the steps that can help solve the problem, but I really don’t see a reason now to change the AspNetCoreModuleV2 module to an older version. In addition, you can change the settings in the web.config file before deploying the application in accordance with the requirements of a particular hosting provider.

**Comment by rajupaladiya** [comment]
@DmitriyKulagin - Okay noted.

**Comment by vipulsatyanam** [comment]
@rajupaladiya  i think one of the solution is installing below

You just need to install this package below. After that you can use the AspNetCoreModuleV2 :)

https://dotnet.microsoft.com/download/thank-you/dotnet-runtime-2.2.2-windows-hosting-bundle-installer

Once installation is completed, It should work without any change in web.config.

**Comment by zakavi** [comment]
This is resolved by change AspNetCoreModuleV2 to AspNetCoreModule in web.config
