### ISSUE TITLE
Two stages setting to enable SSL

### ISSUE THREAD

**Issue by maplewang** [nopSolutions/nopCommerce#4591]
nopCommerce version: 4.3 and bellow

Steps to reproduce the problem: when failed to config ssl function in http server, that may cause admin area is unreachable.
so wondering if we can set a second stage confirmation, just like we change windows screen resulations. we can temporally activate ssl function, if the ssl function is good, shows a page with button and a timer, the administrator click at that page so that SSL can be set, otherwise after 20 seconds the ssl setting will roll back.

actually wrong ssl configuration like Too many redirects occurs too often.

Implementation described in comments - https://github.com/nopSolutions/nopCommerce/issues/4591#issuecomment-967211595

**Comment by AndreiMaz** [comment]
@exileDev The way to implement:
1. When a store owner ticks the checkbox, we save a temporary setting "resetsslvalueafterapplicationrestart" with "true" value
2. Then redirect to a new "confirmation" page with "Yes" and "No" question
3. If a user clicks "Yes", then we'll delete this temporary "resetsslvalueafterapplicationrestart" setting.
4. If SSL is not installed, then a store owner even won't see this "confirmation" page because of the "many redirects" issue
5. After the application restart, we should check value of "resetsslvalueafterapplicationrestart" . If it's set to "true", then set "SSL" value of a store to "false". So everything will continue working fine

**Comment by exileDev** [comment]
Closed #4591. We've implemented it a bit differently
