### ISSUE TITLE
File upload product attribute throw error on product detail page

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#4683]
nopCommerce version: 4.3

Steps to reproduce the problem: 

1) I have added one file upload control with product
2) Make sure add value as "1-1-2019"
3) open product on public site and get error page

![screenshot-nopcommerce430rc nopadvance com-2020 05 04-23_52_46](https://user-images.githubusercontent.com/10364140/80999530-76d79300-8e62-11ea-8852-81a635d0b47a.png)
![screenshot-nopcommerce430rc nopadvance com-2020 05 04-23_52_17](https://user-images.githubusercontent.com/10364140/80999536-78a15680-8e62-11ea-82d9-1aa547d5fa3d.png)

**Comment by AndreiMaz** [comment]
Also see related https://github.com/nopSolutions/nopCommerce/issues/4686. It's a separate work item to ignore "default value" for "File upload" attribute types because it'll be still possible to set its "default value" even when we implement https://github.com/nopSolutions/nopCommerce/issues/4686. For example, set some "default value" for "textbox" attribute type, then change the attribute type to "file upload", save
