### ISSUE TITLE
Check out new features of C# 8

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4833]
More info: https://docs.microsoft.com/ru-ru/dotnet/csharp/whats-new/csharp-8

Let's check and decide what we should use in nopCommerce

**Comment by badijm** [comment]
hi, If if available, I could pick & try this.

**Comment by badijm** [comment]
@AndreiMaz 

Hi, I think we can use `System.Range/Index` instead of `.Substring()` in some cases. I've measure their performance difference using **Benchmark.net**  

Their main feature - less heap allocation, as they are **struct**, so no string coping 

Further reading - https://stackoverflow.com/questions/55167287/what-is-range-and-index-types-in-c-sharp-8. 

**Results**

![image](https://user-images.githubusercontent.com/22330489/90159993-c7f6fd00-dd56-11ea-8151-9ff3631e3ee0.png)


**Source code:**

        `[Benchmark(Baseline = true)]
        public void SplitWithSubstring()
        {
            var first = FullName.Substring(0, separatorIndex).Trim();
            var second = FullName.Substring(separatorIndex + 1).Trim();
            DeadCodeEliminationHelper.KeepAliveWithoutBoxing(first);
            DeadCodeEliminationHelper.KeepAliveWithoutBoxing(second);
        }

        [Benchmark()]
        public void SplitWithRange()
        {
            var first = FullName[0..separatorIndex].Trim();
            var second = FullName[^separatorIndex..].Trim();
            DeadCodeEliminationHelper.KeepAliveWithoutBoxing(first);
            DeadCodeEliminationHelper.KeepAliveWithoutBoxing(second);
        }
`

Let's discuss it more deeply. Thanks.

**Comment by DmitriyKulagin** [comment]
Closed #4833
