### ISSUE TITLE
Startup is slow ~ 4 minutes when having lots of Language Resources to update 

### ISSUE THREAD

**Issue by roman-gherman** [nopSolutions/nopCommerce#4893]
nopCommerce version: 4.3

Steps to reproduce the problem: 
The issue was introduced in https://github.com/nopSolutions/nopCommerce/issues/4782
The groupby and sort are slowing down the startup of nopcommerce by several minutes.
The slowness is much more visible when using MySql DB.

I have done a fix for this: https://github.com/nopSolutions/nopCommerce/pull/4892

**Comment by skoshelev** [comment]
Hi @roman-gherman. Thanks for your contribution. I looked at your solution and found it a bit complicated. I add more simple code to improve performance. But I don't understand how it may slow startup if this method used only during installation or when importing new resources.

**Comment by roman-gherman** [comment]
@skoshelev I am using a nop-template Emporium theme with lots of plugins.
They and I guess many others, use that method to update the language strings.
This is done during Startup. 
And that is because the GroupBy is slow.

This  is why I have done this with a dictionary.

**Comment by roman-gherman** [comment]
@skoshelev unfortunately your commit: https://github.com/nopSolutions/nopCommerce/commit/cefe82f74f860ae3145d415affd51b7e1475856a
is a bit wrong.

You are not taking the latest version.
Please add a: .OrderBy(lsr => lsr.Id)

**Comment by joekrauss** [comment]
I agree the issue appears with nop-templates plugins that results in a lengthy startup of NopCommerce. I use the fix provided by Roman and the site starts within a minute, otherwise it could take 4 or more minutes.
Initially the fix was to prevent a duplicate local resource but it added the lengthy startup.


> On Jul 7, 2020, at 6:52 AM, Roman Gherman <notifications@github.com> wrote:
> 
> ﻿
> @skoshelev I am using a nop-template Emporium theme with lots of plugins.
> They and I guess many others, use that method to update the language strings.
> This is done during Startup.
> And that is because the GroupBy is slow.
> 
> This is why I have done this with a dictionary.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



Defense Solution Group, Inc. / DSG Arms
Office: 817-806-9242
Fax: 817-615-8820
Email: 
6100 Conveyor Drive
Cleburne, TX 76031-0998
CAGE: 1L0J5
GSA: GS-07F-6007R 
https://dsgarms.com
https://www.dsgholsters.com
http://www.dsginc.com
The content of this email is confidential and intended for the recipient specified in the message only. It is strictly forbidden to share any part of this message with any third party, without the written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future.

**Comment by skoshelev** [comment]
> @skoshelev unfortunately your commit: [cefe82f](https://github.com/nopSolutions/nopCommerce/commit/cefe82f74f860ae3145d415affd51b7e1475856a)
> is a bit wrong.
> 
> You are not taking the latest version.
> Please add a: .OrderBy(lsr => lsr.Id)

I am not 100% sure, but I believe that since there is no sorting, the data from the database will go sorted by the primary key; therefore, adding sorting by id should not be necessary

**Comment by roman-gherman** [comment]
When there is no sorting, data from DB does not necessarily return it sorted by the primary key.
adding .OrderBy(lsr => lsr.Id) will make it more safe, by keeping the latest version

**Comment by skoshelev** [comment]
Ok. I think it may sense. Thank you for your help and contribution.

**Comment by skoshelev** [comment]
Closed #4893
