### ISSUE TITLE
Web API support

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4988]
Previously our community used one of the most popular API plugin for nopCommerce - https://www.nopcommerce.com/en/api-plugin. But it's a third-party plugin and the nop-templates team decided not to upgrade it to the latest version.

It's one of the most demanded features. That's why we consider implementing the API (by nopCommerce team)

**Comment by brian-lagerman** [comment]
Can you elaborate more on 

> the nop-templates team decided not to upgrade it to the latest version

I've been following the upgrade path [here ](https://github.com/SevenSpikes/api-plugin-for-nopcommerce/issues/223), and there appears to be activity as of just a few days ago. If you're aware that this plugin is being abandoned, that would be critical information for us.

We're working on our initial version of nopCommerce and the API integration is a must. We've been preparing the site on version 4.2 since the API is supported there, with the hopes up upgrading to 4.3 before our first release. Our planning and timeline are clearly affected by this.

I will say that I feel the API belongs in the core product anyway. The API touches so many parts of the core, that version upgrades understandably take significant time to implement. Anyone using the API plugin is therefore forced to wait a good bit longer on version upgrade adoption.

**Comment by naymore** [comment]
Hello there, I am currently searching for an e-commerce solution to integrate in our existing WCM system.
So I'm still in the process of digging through all the documentation and everything... so please correct me if I'm wrong.

Looking at the aforementioned API-plugin I indeed wonder if there is no option to integrate nopCommerce into existing WCM deployments on an API-only level ("headless"). I'm just watching the [youtube video where that guy praises the architecture in the highest tones](https://www.youtube.com/watch?v=6gLbizzSA9o&list=PLnL_aDfmRHwtJmzeA7SxrpH3-XDY2ue0a). But reading this issue makes me wonder if the "backend" is tightly coupled to the "frontend" which is of course perfectly ok, just not the solution I am looking for.

**Comment by P-de-Jong** [comment]
I'm currently looking into headless alternatives to nopCommerce. It would be awesome if nopCommerce adds a headless option.

**Comment by eadameg** [comment]
For us it's a deal breaker if the API is not provided ASAP

**Comment by luc-cap** [comment]
Hi,
      the API project is very important.

At the time of Nop3.65, in ROADMAP, there was integration with Orchard, I would like to point out that currently Orchard Core has been rewritten in .NET Core 3.1 and offers 2 plugins ..
The first enables an admin page where you can configure an OpenID Authorization Server.
The second enables an admin page where you can add OpenID Clients  (  OpenId Connect Flows  enabled ) for  authentication.
 
Have look at this already working , simple solution  offered by OrchardCore.

Orchard core in turn was inspired by the Github project: OpenIddict: a versatile solution to implement an OpenID Connect server and token validation in any ASP.NET Core 2.1, 3.1 and 5.0 application.

https://github.com/openiddict/openiddict-core

I hope this info can be useful. 

Orchard Core screen-shots:


![authentication_client](https://user-images.githubusercontent.com/36303714/112610340-dd6bf380-8e1c-11eb-8ae2-5b1c84fad304.png)
![authentication_server](https://user-images.githubusercontent.com/36303714/112610343-de048a00-8e1c-11eb-8080-312f638492d7.png)

**Comment by ckoch1979silentservice** [comment]
Will it really be released with version 4.5?

**Comment by AndreiMaz** [comment]
@ckoch1979silentservice Yes. Furthermore, it'll be released for 4.40 as well

**Comment by ckoch1979silentservice** [comment]
So it will be a separate module? When will it be released?

**Comment by AndreiMaz** [comment]
@ckoch1979silentservice Yes, ETA is June

**Comment by ckoch1979silentservice** [comment]
Is the code here on Github?

**Comment by AndreiMaz** [comment]
No

**Comment by eadameg** [comment]
Hi Andrei. Could you give some details of the new API?:

- Is it just an upgrade of the API developed by Nop-Templates
- Does it have some improvments? 
- If so, could you please provide highlights?
Thanks in advance

**Comment by AndreiMaz** [comment]
@eadameg Hi Eduardo

1. No, it's a new plugin
2. Yes, it'll be a much richer plugin
3. Not yet. We'll share more details later

**Comment by goransipic** [comment]
Hi @AndreiMaz , will WebApi have support for oauth2 protocol for mobile devices (Authorization Code Flow + PCKE )

[https://github.com/openid/AppAuth-Android](url)

**Comment by martingust** [comment]
API-first GraphQL solution would be the dream. Just like the move Saleor Commerce did a few years ago.

“We could have stopped there, but saw brands pressing for more revolutionary front-end experiences,” Mencel says. “Decoupling Saleor’s core from its presentation layer was the obvious path to revolutionary front-ends. As difficult as it was, we tore down what was a rather good open-source e-commerce platform and rebuilt it API-first”.
https://techcrunch.com/2021/03/18/saleor/

**Comment by AxelAndersen** [comment]
Hi

I read that this new API would come out this June, is that right?
We are moving to NopCommerce with 2 existing webshops, but need to wait for an API to be able to transfer the products.

Best regards,
Axel

**Comment by eadameg** [comment]
I understand the ETA is beginning of July

> Hi
> 
> I read that this new API would come out this June, is that right?
> We are moving to NopCommerce with 2 existing webshops, but need to wait for an API to be able to transfer the products.
> 
> Best regards,
> Axel

I understand the ETA is beginning of July

**Comment by matthewha** [comment]
Hi,

Any chance for an update on timing? Really looking forward to this feature as an official one, although will keep using the excellent work of stepanbenes at https://github.com/stepanbenes/api-for-nopcommerce in the meantime.

Thanks,

Matt

**Comment by NextComercio1** [comment]
Any updates on release date?

**Comment by AndreiMaz** [comment]
Just to let you know that we've almost finished the plugin and we plan to release it soon (for version 4.40). The updated ETA is August. This plugin will cover almost all methods of nopCommerce core (backend and frontend). And I also have to announce in advance that this plugin will be available as a paid plugin on our marketplace. Of course, we plan to invest all profit from this plugin into the growth of our team and further development of nopCommerce core. We hope that our community supports us and understands and that the nopCommerce team also has to monetize some small part of all the work we do during all these years.

**Comment by brian-lagerman** [comment]
I don’t take issue with the API being a paid plugin, but I could see problems if the API source code isn’t available and extendable. At least in the prior community API plugins we’ve tried, most customizations to nopCommerce Core would require a similar customization to the API. Adding a simple property to Products (say MSRP for example) did require API DTO and mapping changes to reflect the availability of the new property. Maybe you’ve already included support for these types of customizations, I don’t know.

It would just be unfortunate if developers had to choose between extending nopCommerce Core and using the API. Something to consider anyway.

**Comment by MaximG1234** [comment]
Yeah, I have to second the above post by @brian-lagerman. I have no problem paying for the plugin (although I think strategically NopCommerce might be making a mistake making people pay for a piece of core functionality) but I will very likely need the ability to extend the API because I expect it will lack features that I need and I cant wait for others to resolve potential bugs. 

It would be a deal breaker for me to use the API without the ability to get access to the source code.

**Comment by iwhp** [comment]
There is also the problem that if the plugin is not part of the public source code, the logic has to be coded there AND in this Web API. How can that be an advantage? In the long run, this doesn't seem to be a good decision and am I considering about moving to another open source project...

**Comment by ActionWebsites** [comment]
Completely agree with the replies here that source code for the paid plugin is an absolute must. If partners/paying developers don't have access to the API source then it is useless and not worth bothering with.

**Comment by jakubmaguza** [comment]
How far are you from releasing first version of API? I know you mentioned August, but you think of beginning, or end of August?

**Comment by brandon71** [comment]
We are currently looking at moving our platform to NopCommerce. We maintain our own API with our current system due to many third party integrations. Source code access to the API is a must for us. Please let us know if their will be a source code option as soon as possible.

**Comment by AndreiMaz** [comment]
@jakubmaguza the beginning of August

**Comment by AndreiMaz** [comment]
@brandon71 Source code will be available

**Comment by ActionWebsites** [comment]
> @brandon71 Source code will be available

Great news, well done.

**Comment by goransipic** [comment]
That is awesome @AndreiMaz, community can handle bug fix-es and new features. It's important that you have started with official release.  Great news! I'm a mobile developer a can make mobile apps with your web API now.

**Comment by darocker22** [comment]
@AndreiMaz how will the plugin be licensed? Will it be based on a per site or will there be an option to put on unlimited sites?  Thanks!!! We are looking forward to being able to use and take advantage of the new API.

**Comment by AndreiMaz** [comment]
And here we go. The official web API plugin is finally released. Please find it at https://www.nopcommerce.com/web-api

**Comment by ghd258** [comment]
收费的

**Comment by brandon71** [comment]
Hello,

Thank you for the information on the release of the new API. We are very excited to see all the hard work in action! 
We are looking at using NopCommerce as a core platform to replace our current system. There are a couple items we need to figure out how to handle on our side.
The cost of the api alone is more than we charge some new clients to get up and running. I believe the email mentioned discounts for purchasing in quantities.- Is there a possibility to pay for licenses up front without tying them to a url/domain? i.e. buy 5, 10 or 20 licenses now then assign a domain to a license as we get new clients.- Have you setup any multi-license break points so I could have an idea how pricing would progress with quantities?
We are evaluating our marketing strategy and have not decided on a final domain for a our new release but would like to start evaluating implementation with the API.  Are there any options to test and work with the API before deciding on a domain? I have no issue paying now, I just don't want to waste the money on a domain that will never be used.

Thank You,
Brandon
  

    On Wednesday, August 11, 2021, 06:10:09 AM MDT, ghd258 ***@***.***> wrote:  
 
 


收费的

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by goransipic** [comment]
Hi @AndreiMaz do you have in plan for social login (Facebook, Google) with **WebApi plugin** right now there is only support for classic login with **email/password**.

**Comment by ahmedzakaria432** [comment]
can i know what is functionalities available in this plugin and can i customize it for my needs ?

**Comment by glhays** [comment]
This info is available on nopcommerce website I believe.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rahatur** [comment]
> @eadameg Hi Eduardo
> 
> 1. No, it's a new plugin
> 2. Yes, it'll be a much richer plugin
> 3. Not yet. We'll share more details later

Is it going to be a free plugin?

**Comment by Jehad-Alkhateeb** [comment]
Is there any plan to add GraphQL support?

**Comment by DmitriyKulagin** [comment]
Hi, @Jehad-Alkhateeb. There are no such plans at the moment.

**Comment by fdonnet** [comment]
sad that this plugin is a paid one. Today you can even deliver only the api and no front-end... and it would be better. I don't mind to pay for specific advanced functions etc. but for ez access to core functionnalities 850.- it is really again open source way of life.

It doesn't add anything (you go in src look at the code and dev an endpoint when you need it), it's just a fee for "if you don't want to waste time, see here you can pay a fee". 

First thing I was looking for on the github... what a bad surprise.

**Comment by jakubmaguza** [comment]
I believe wording should be changed. It's not open source, it comes with full source code.
