### ISSUE TITLE
Best Sellers report inflated when a product exists in multiple categories

### ISSUE THREAD

**Issue by wildj79** [nopSolutions/nopCommerce#5077]
nopCommerce version: 4.30

On the Admin Dashboard, the best sellers reports at the bottom seem to be off. If a product exists in multiple categories, the quantity and total amounts seem to be multiplied by the number of categories the products are in. 

Steps to reproduce the problem: Place a product in multiple categories, then place several test orders with that product. The numbers in the Bestsellers by quantity and Bestsellers by amount will show inflated results.

**Comment by joekrauss** [comment]
Issue was fixed on this commit.

https://github.com/nopSolutions/nopCommerce/commit/a3199c357695f4fd29796af2ee62039fec47f56b


Joseph Krauss



The content of this email is confidential and intended for the recipient specified in the message only. It is strictly forbidden to share any part of this message with any third party, without the written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future.

**Comment by wildj79** [comment]
Good to know! I'll go ahead and close this then.
