### ISSUE TITLE
Editing gift card quantity in order via admin panel does not affect quantity of cards issued

### ISSUE THREAD

**Issue by noncenz** [nopSolutions/nopCommerce#5161]
**nopCommerce version:** 4.3.0

**Steps to reproduce the problem:** 

1. Create an order with a single line item for gift card with qty of 2.
2. Go to admin panel > sales > orders and view order
3. Find gift card item and click edit
4. Adjust quantity up or down and click save

**Expected result:**

Gift cards are created or destroyed to match order.

**Observed result:**

Gift card quantity field changes value but actual number of cards issued remains unchanged.

**Comment by RomanovM** [comment]
Thanks. Already reported on our forums (see [here](https://www.nopcommerce.com/boards/topic/87526/bug-in-adding-quantity-to-shopping-cart)).
This is due to setting `ordersettings.autoupdateordertotalsoneditingorder` when it enabled. We are gonna fix it in https://github.com/nopSolutions/nopCommerce/issues/8
