### ISSUE TITLE
Configurable sorting of shipping options

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5204]
Let's allow a store owner to choose how he/she wants to sort shipping options. Let's a new "Sort shipping methods by" setting to the "Shipping settings" page. There will be two options - "Position" (the current one based on a shipping rate computation display order) and "Shipping cost"

So if a store owner chooses the "Shipping cost", then sort by price (asc). 

Apply this logic to all pages where it's used

**Comment by joekrauss** [comment]
Hello Andrei, as a store owner we override the selected shipping option. Although our two day express shipping @ $7 was the best option customers naturally navigated to the last or bottom of the shipping options believing it was the cheapest. 
It would be great to have the flexibility from the developers code to sort & default the selected shipping options.


> On Dec 7, 2020, at 6:52 AM, Andrei Mazulnitsyn <notifications@github.com> wrote:
> 
> ﻿
> Let's allow a store owner to choose how he/she wants to sort shipping options. Let's a new "Sort shipping methods by" setting to the "Shipping settings" page. There will be two options - "Position" (the current one based on a shipping rate computation display order) and "Shipping cost"
> 
> So if a store owner chooses the "Shipping cost", then sort by price (asc).
> 
> Apply this logic to all pages where it's used
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



Defense Solution Group, Inc. / DSG Arms
Office: 817-806-9242
Fax: 817-615-8820
Email: 
6100 Conveyor Drive
Cleburne, TX 76031-0998
CAGE: 1L0J5
GSA: GS-07F-6007R 
https://dsgarms.com
https://www.dsgholsters.com
http://www.dsginc.com
The content of this email is confidential and intended for the recipient specified in the message only. It is strictly forbidden to share any part of this message with any third party, without the written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future.
