### ISSUE TITLE
Setup failed: Target width 0 and height 0 must be greater than zero.

### ISSUE THREAD

**Issue by Lymperis79** [nopSolutions/nopCommerce#5219]
nopCommerce version: 4.40

Steps to reproduce the problem: 
Try to make a clean installation and the following message appears "Setup failed: Target width 0 and height 0 must be greater than zero."

I could also mention an idea of the option to be able to install multiple languages during the first installation.

**Comment by zombiegh0st** [comment]
I ran into same issue today and tried to debug. Unfortunately my ASP.NET knowledge is limited so I'm not sure how to solve the issue. All I can say is that the error is caused by **Nop.Services.Media.PictureService.ValidatePicture**. It seems the **_mediaSettings** is not initialized. The **PictureService** tries to resize a picture and fails because target **MaximumImageSize** is **0** while creating sample data.

**Comment by DmitriyKulagin** [comment]
Closed #5219

**Comment by DmitriyKulagin** [comment]
> One more suggestion is that if the installation fails the selection of the installation region to stay the same or to go again to the select value. When it was failing it was jumping in another value that the selected!

Thanks for the suggestion . I created a work item for this - #5223.
