### ISSUE TITLE
Display unnecessary bracket on product listing page.

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#5373]
nopCommerce version: 4.40 beta 

Steps to reproduce the problem: 

1) Go /Admin/Tax/Providers

2) click on Mark as primary provider for this Avalara tax provider.

3) Go /Admin/Product/List

![image](https://user-images.githubusercontent.com/41533502/108709616-f42adc00-7538-11eb-83ba-3701dcd19640.png)

**Comment by ilyasfocuspoint** [comment]
HI @RomanovM 

I had review the plugin but still facing same issue , Attach the screen shot [](https://prnt.sc/x9-lh5vxg8V3) , 
I had checked with Fresh NopCommerce 4.20 and fresh Tax plugin , but facing same issue in product listing page 

the issue is we need to escape "/" from script it prevent

**Comment by ilyaspatel91** [comment]
HI @RomanovM 

I had review the plugin but still facing same issue , Attach the screen shot click here ,
I had checked with Fresh NopCommerce 4.20 and fresh Tax plugin , but facing same issue in product listing page

the issue is we need to escape "/" from script it prevent

**Comment by ilyaspatel91** [comment]
HI @RomanovM

I had review the plugin but still facing same issue , Attach the screen shot [click here](https://prnt.sc/x9-lh5vxg8V3) ,
I had checked with Fresh NopCommerce 4.20 and fresh Tax plugin , but facing same issue in product listing page

the issue is we need to escape "/" from script it prevent
