### ISSUE TITLE
Support for multiple conditions for product attributes

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#541]
Currently a store owner can specify only one condition (depends on some other attribute). See related work item #11008 

Let's also support more complex using operators such as "equal", "not equal", "greater than", "less than", "contains", etc. 

We can also consider conditional checkout and product attributes based on products which are in the cart, subtotal, and/or shipping country would be great. IMHO it's not so demanded

**Comment by JosephMDavis** [comment]
This would be a great addition.

**Comment by IAmThatStrange** [comment]
My company, Nelnet too agrees that it would be a great addition.  Many of our clients who will be using Nopcommerce will have event registration online.  And the examples we've found almost all had attributes with multiple conditions.

**Comment by cableguyusa** [comment]
I would like to see something like this as well.  Currently I was trying to put a checkbox list together for other options so for each item they put a checkbox in it would add another attribute list for them to pick items from.  The problem is the way it is set up it is a AND where I want an OR.  

Here is the start to the example I was working on
[  ] Router
[  ] Printer

If Router checked
O Router Option 1
O Router Option 2
O Router Option 3

If Printer Checked
O Printer Option 1
O Printer Option 2
O Printer Option 3
O Printer Option ...

If just one of the check boxes is selected then it is ok, but I want if both are selected to show both the router options AND the printer options

**Comment by lbroell** [comment]
We also need this feature. We sell complex products with 5  to 7 product attributes, with each attribute having multiple options. 
We need the ability to have a condition that would display the next attribute if any of the options in the previous attribute were selected. Not keyed on one option like the current code.
Also, it would be nice if the next attribute could be filtered based on a selection in the previous option. For example if option A is selected from a list, the only options compatible with A would be displayed in the next attribute list.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development

**Comment by aealden** [comment]
This is a sorely needed feature, I am just wondering if anyone knows of a plugin that adds this functionality?

**Comment by piotrsz772** [comment]
Hello, maybe you will back to discuss this feature again in the next release?
