### ISSUE TITLE
Reinstall 4.40 Beta

### ISSUE THREAD

**Issue by untiedshoes** [nopSolutions/nopCommerce#5440]
nopCommerce version: 4.40 Beta

Steps to reproduce the problem: Install nopcommerce without sample data. Delete dataSettings.json & plugins.json and try to reinstall with sample data after entering details on install page
![Screen Shot 2021-02-24 at 11 37 27](https://user-images.githubusercontent.com/12123259/108995276-bc38ab80-7694-11eb-8c32-9024f7aeb239.png)
.

Error on installation screen - Setup failed: Sequence contains more than one element.

**Comment by AndreiMaz** [comment]
Your database should not contain any tables. Please delete them before installation

**Comment by untiedshoes** [comment]
Yes, I (although others may not) know of this, but maybe change the error message to something more user-friendly: "database already has tables installed"?

Also, maybe we could have an SQL script to install sample data, for those that forget to install the sample data at install, please?

Thanks,
Craig

**Comment by skoshelev** [comment]
Hi @untiedshoes.

``Also, maybe we could have an SQL script to install sample data, for those that forget to install the sample data at install, please?``

starting from the version of 4.30 we use only "code first" install approach because we started to support more than one database server, that is why we don't have a SQL script to insert sample data. But, you may adapt a [previous one ](https://github.com/nopSolutions/nopCommerce/blob/release-4.20/src/Presentation/Nop.Web/App_Data/Install/Fast/create_sample_data.sql)
