### ISSUE TITLE
Pages with a master checkbox. Uncheck the checkbox after clicking the "...selected" buttons

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#5444]
nopCommerce version: 4.4beta

Steps to reproduce the problem: 
1) Go to https://localhost:44308/Admin/ProductReview/List
2) Click on master check box of datatable 
3) Press on approval selected button and see the master checkbox

![chrome-capture](https://user-images.githubusercontent.com/10364140/109004174-684ab880-76ce-11eb-8d47-81c69bc3c272.gif)

Do the same for all pages with master checkboxes and buttons such as "deleted selected", "approve or disapprove selected"

**Comment by AndreiMaz** [comment]
@sangeetshah So what exactly do you expect from the master checkbox? Please clarify

**Comment by sangeetshah** [comment]
@AndreiMaz mastercheck should be unchecked when user press the any of button like approved selected,disapprove selected,delete selected

**Comment by DmitriyKulagin** [comment]
This has already been done. See commit - https://github.com/nopSolutions/nopCommerce/compare/2b1dfcd178c9...7528dadf131f

**Comment by sangeetshah** [comment]
@DmitriyKulagin I can see your commit that show this one is bug. what you think about it?

**Comment by DmitriyKulagin** [comment]
@sangeetshah It is worth adding that before the commit that I brought there was another one - [here it is](https://github.com/nopSolutions/nopCommerce/commit/2b1dfcd178c9eb709dfb8f4a7223d366132da63d). This will probably make it more clear why these changes followed. At the same time, I note that the functionality of the master checkbox was not broken, you could use it fully. Therefore, this improvement was made in order to establish the relationship of the checkbox with its table. This is necessary for the case when several tables are used on one page.
