### ISSUE TITLE
Do not use latest docker image

### ISSUE THREAD

**Issue by sefacan** [nopSolutions/nopCommerce#5490]
mysql:latest -> mysql:8.0
postgres:latest -> postgres:12.6

Using it this way may cause some version and compatibility issues. 
We should specify the stable version of all databases.

**Comment by skoshelev** [comment]
Hi @sefacan.

I do not quite understand what problems you are talking about, we have never encountered a situation when changes were made to products like MySql without backward compatibility support. Since we strive to use new technologies, we do not see any problems in using the latest versions of the database. Moreover, we attach our compose files for ease of testing, I don't think that someone will decide to use them in production without changes.

Closed #5490
