### ISSUE TITLE
4.40 Beta (Product Export zero quantity)

### ISSUE THREAD

**Issue by untiedshoes** [nopSolutions/nopCommerce#5508]
nopCommerce version: 4.40 Beta

Steps to reproduce the problem: Exporting products to Excel shows zero stock for all size combinations. I've found this because one of my clients has found the same issue with the product export from a 3.90 store - all product combinations have 1 for quantity.

![Screen Shot 2021-03-08 at 12 46 10](https://user-images.githubusercontent.com/12123259/110323597-b8017c00-800c-11eb-862b-bfe3d5aa98be.png)

![Screen Shot 2021-03-08 at 12 46 26](https://user-images.githubusercontent.com/12123259/110323607-bb950300-800c-11eb-917f-edf86f9c8281.png)

**Comment by skoshelev** [comment]
Hi @untiedshoes. This is not an error, since import/export does not take into account combinations of attributes, but only the attributes themselves, therefore the value of this field is taken directly from the ProductAttributeValue table (this field is applied only with AssociatedToProduct attribute value type)
