### ISSUE TITLE
Multi Instance Performance Degrade

### ISSUE THREAD

**Issue by streamzyuk** [nopSolutions/nopCommerce#5641]
nopCommerce version: 4.40.3

Steps to reproduce the problem: 

I have installed nopcommerce 4.40.3 on aws ECS fargate in docker.

Made some tests.

Running single instance on ECS with MySql Aurora Serverless and Single node Redis and ALB load balancer.

Whats strange is when spinning up a single task and setting the Load Locales and Resources on StartUp it runs smoothly.

With same startup settings when I increase the task count to 3 the response times really goes up. Sometimes I get timeouts.

I have checked some source codes with the caching and Localization settings.

It looks like its not optimized for multi instance.
Implementing PerInstance cache will hugely improve performance especially for localization which tends to stay unchanged if there is no software update.

When I disable Load Localization resources on startup the performance is degraded more but ist more consistent per instance.

I will implement perInstance cache and test the results and change the startup settings to let only specific instance to load localization cahche records on startup and assume the other instances that they are already loaded and get them from redis to instance cache.

**Comment by AndreiMaz** [comment]
Local caching will always be faster than distributed caching (e.g. Redis) but I wouldn't agree that it's not optimized. We fully support web farms stating 4.40.0 - https://docs.nopcommerce.com/en/installation-and-upgrading/installing-nopcommerce/web-farms.html. There could be many reasons why it's slower in your specific environment. But implementing PerInstance cache won't help much in your case because anyway entities are loaded only once

but please share your results once tested
