### ISSUE TITLE
Allow uninstall/install multiple plugins

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#567]
In /Admin/Plugin/List, change installation / uninstallation to having a checkbox by each plugin and allow installing / uninstalling multiple plugins at a time

**Comment by AndreiMaz** [comment]
already done in 4.00 (uploading)

**Comment by cnEUL** [comment]
Very good and usafull function, because some suites like a nopTemplate theme exists of 10 plugins and more and it needs 20 minutes to install all. It seems for me that the system restarts after every plugin. Also great for us as hosters would be an comamndline command (or utility ) to install plugins so we could setup a new shop completely in silent mode.

**Comment by skoshelev** [comment]
Fixed by #421
