### ISSUE TITLE
Order page (admin area) cannot handle POST if you have a lot of products (data transferred)

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#5950]
nopCommerce version:  4.4.4

Steps to reproduce the problem: 

1) Add 160 or more than Unique product in the cart.

2) Placed one order with 160 product.

3) Go to /admin/Order/List and open your order which you placed

4) Change order status It will gives 400 bad request apart from this if you change order items field than also you will get same 400 error.

**Note : You have more than 150 unique product in cart in my case I've 160 products in the cart**  

Problem is if form have a lot data than it will gives 400 error that is my assumption.

**Comment by skoshelev** [comment]
Hi @sk5202. We analyzed the problem, indeed, if there are so many items in the order, then there is a problem with the return of error 400. This is due to the limitations imposed on the form by the platform itself. We believe that this is part of the functioning of the security mechanism and have made a decision not to interfere with its work. If you really need to handle such large orders, then we recommend that you look towards the RequestFormLimits attribute or you can change the OrderModel and replace IList with a IPagedList

Closed #5950

**Comment by sk5202** [comment]
@skoshelev  I've tried both way
1. RequestFormLimits attribute not working if i add in particular action or globally in web config
2. if i change IList to Ipagedlist than not able to create object.

Do you have any other idea ?

**Comment by skoshelev** [comment]
@sk5202 Replacing IList with IPageList is not so simple, you need to redo the logic for creating the model, and the presentation layer will most likely have to be changed.

And for the RequestFormLimits attribute to work correctly, you also need the IgnoreAntiforgeryToken attribute without it may not work

**Comment by sk5202** [comment]
@skoshelev  i've tried RequestFormLimits above action and also add IgnoreAntiforgeryToken  but won't work.

Is there anything i mistake i did ?

please check below snap..

Your help would be appreciated..!!

![image](https://user-images.githubusercontent.com/41533502/142242877-c3556fd6-2a1f-4d98-b051-9495e91422c8.png)


![image](https://user-images.githubusercontent.com/41533502/142242989-d1924ad5-6264-4ba0-a220-753818163d7d.png)

**Comment by skoshelev** [comment]
Hi, @sk5202. Doesn't work, is it in the sense that it keeps showing error 400?

**Comment by esusavila** [comment]
Hi.
This problem "Error 400. Bad request" also occurs in version 4.40
My NopCommerce client has a lot of orders with more than 160 items, and he can't change the status either.
How to solve?
