### ISSUE TITLE
Performance optimization of \UpgradeTo450\LocalizationMigration.cs

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5960]
nopCommerce version: 4.50

\Nop.Web.Framework\Migrations\UpgradeTo450\LocalizationMigration.cs timeouts. We should refactor its logic. 

We should revert back https://github.com/nopSolutions/nopCommerce/issues/5942 and fix an elegant way (do not lowercase locales). Locales should NOT be lowercased in database as well.

**Comment by manuel3108** [comment]
Just to throw a new idea in. We could potentially also create a plain sql script and execute that one. I have create such a script and ran it agains a database and it took only 5 seconds or something.
```sql
Update LocalStringResource Set ResourceName = lower(ResourceName)
```
(might have typos in it, its from my head)

**Comment by skoshelev** [comment]
Closed #5960

**Comment by manuel3108** [comment]
Can we please reopen this? This does not fix the problem for existing installations running 4.40.x when upgrading to 4.50.x
We have identified a bunch of our customers with this problem, and as far as we can tell this problem should occur to every store that was created with a 4.40.x version. Thats propably a huge number of shops.

As suggested above, we should consider executing raw sql, because the same thing runs extremely fast with pure sql. I just a had a look at the code, and as far as i can tell, we should be able to use `BaseDataProvider.QueryAsync()` to fix this issue.

This is the correct query btw:
```sql
UPDATE LocaleStringResource SET ResourceName = LOWER(ResourceName)
```

I did some testing on two relatively clean shops and the execution time of this was both times below one second.

Please reconsider this decision and let me know what you are thinking.

**Comment by skoshelev** [comment]
Hi @manuel3108. We analyzed this issue in detail, most users will not have any errors, since this problem requires specific settings. For example, the setting for loading all locales at startup should be disabled, if you load all locales at the start of the site, this not only increases the performance of the site but also saves you from all problems with the register. As for the execution of commands via QueryAsync from the migration, this is a bad practice, since there is no guarantee that a specific SQL code will work correctly on all supported DBMS

**Comment by manuel3108** [comment]
Thanks for the explanation. I now understand your way of thinking and can at least partially agree now. Thanks.
