### ISSUE TITLE
Remove multi-step checkout

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6047]
We already have one-page checkout that is used worldwide. In order to keep our solution simpler, let's remove the multi-step checkout functionality

**Comment by zyjesobie** [comment]
Hi! i'm not sure this is a best idea.

We are using multistep in our shop, because onestep generate some issues (in 4.1 Noptemplates onepage). Multistep give possibility to analyse where Client go out from page. And then we can think about solution / optimize. In onepage checkout we don't have this possibility. "Client just go out".

I'm thinking better solution is remove few steps (like "information about payment" after choose payment / combine shipping / payment steps).

Some information you can move on the "cart" page, like (shipment step / payments step), then Client see "how much pay" in cart (this information they are looking there). In another steps we can take his data to bill / shippment. And reduce 5-6 steps to 3-4.

Also when i read "articles", not always onestep cart is better. It's better solution when we buy small / not expensive things, but in articles and some case when we buy more and more expensive things then multistep can be better. 

I give you 100% right multi-checkout / onepage checkout should be improved, but removing at all, it's not a good solution in my opinion.

Actual created "onepage" solutions in nopcommerce marketplace in 99% generate lots of bugs. I testing them all and after 10-15 minutes / some combinations we have long list errors in all (maybe nop-templates don't, but they use technology where we can't custom anything)... 

Checkout is the mostly important thing in all ecommerce. I'm not sure it's a best way to improve platform to remove "core" functionality. 

I think better solution is improve and make modern multistep checkout.

1. give more support to validation emails (don't support gamil.com and other wrong address)
2.  better solution for invoice (there should be checkbox where we choose "company or personal buy")
3.  Remove / combine some steps.
4. Improve "cart" page and give there some extra functions like "remove all" or recalculate cart without click "update" etc.

Here is solution one of the bigger SAAS company in Poland (theme design is ugly, but maybe you can check there "idea" i can look for something more. 
[https://www.domowystomatolog.pl](https://www.domowystomatolog.pl)

They have there 3-4 steps. 

I think also Zalando.com have good solution. And many other big ecommerce.

**Comment by Christopgr** [comment]
I am going to second some of zyjesobie suggestions, because they are vital for European stores:

**2) Better solution for invoice (there should be checkbox where we choose "company or personal buy")**
That's the most important one. We had to create a custom solution for all our non B2B stores which is not really a problem. The problem is that when somebody just wants to buy a template site he expects to have this functionality as it's supported in literally every other store which makes it difficult to make him pay for it as just stating that the core solution does not support it would make him doubt the core solution itself. 

**4) Improve "cart" page and give there some extra functions like "remove all" or recalculate cart without click "update" etc.**
Functionally this one works fine, because most of what you would want to do is there and making AJAX add/remove of products is something that should be payed for if somebody wants it. Would greatly improve the payed template experience though for the non tech-savvy client as people do actually ask for it.

**Comment by sinanopcommerce** [comment]
Do not do this, please. There are a lot of people who still like the multi-step checkout. [anyvas](https://anyvas.com/). There are a lot of places to improve the application rather than simply remove the multi-steps checkout.

**Comment by AndreiMaz** [comment]
Decided to leave both options
