### ISSUE TITLE
Dockerfile build issue on Ubuntu 20.01 LTS machine

### ISSUE THREAD

**Issue by akpdi** [nopSolutions/nopCommerce#6049]
nopCommerce version: 
master branch on Dec-21-2021

Steps to reproduce the problem: 
initializing postgres docker-compose on ubuntu server 20.01 LTS
/nopCommerce# docker-compose -f postgresql-docker-compose.yml up -d

I am getting below error
![image](https://user-images.githubusercontent.com/96499100/146994668-3bacffcc-0182-4350-9126-f3686fe7cf5b.png)

**Comment by skoshelev** [comment]
Hi @akpdi . The problem with PayPalSmartPaymentButtons plugin was fixed by [this commit](https://github.com/nopSolutions/nopCommerce/commit/5396449).

If you want to use docker image built yourself, you may use the 4.40-bug-fixes brunch.

Also, you may use our official docker image from [DockerHub](https://hub.docker.com/r/nopcommerceteam/nopcommerce/tags)

Closed #6049
