### ISSUE TITLE
Suggestion: Create sepearte migrations for pre-release releases & patch releases

### ISSUE THREAD

**Issue by manuel3108** [nopSolutions/nopCommerce#6059]
nopCommerce version: 4.50.x

Steps to reproduce the problem: 
1. Install [`release-4.50.0-beta`](https://github.com/nopSolutions/nopCommerce/releases/tag/release-4.50.0-beta) on a server
2. Update your installation to [`release-4.50.0-RC`](https://github.com/nopSolutions/nopCommerce/releases/tag/release-4.50.0-rc) 

**Problem**
The Migration file `Presentation/Nop.Web.Framework/Migrations/UpgradeTo450/LocalizationMigration.cs` i.e. hat some heavy modifications between the beta and RC release. All those changes did not get applied to the above installation, because the migration was already marked as installed.

**Solution to problem**
I would need to re-install the Database, or go ahead and make those modifications by hand.

**Suggestion**
Based on the naming pattern `UpgradeTo450` (aka the folder name) it seems that your are only planning to create seperate migrations for each minor version (aka 4.60, 4.70) and not for the patch versions (aka 4.50.1, 4.50.2). In order to avoid such problems as described above, i would suggest to create migrations for every patch & minor version bump.

If i missed something obvious, please explain me 😄

**Comment by skoshelev** [comment]
Hi, @manuel3108. Thank you for your suggestion, but our development process does not involve making any changes to minor versions that should be done through major migrations. Even if it becomes necessary to change some data within the minor version, we will create a point migration for them. As for your question, beta testing is primarily carried out in order to identify errors, which means it does not involve installation on production servers. In any case, you can delete the required entry from the MigrationVersionInfo table and the migration will be applied again. 
I see no point in creating migrations separately for beta testing.
Closed #6059
