### ISSUE TITLE
Site crashed if CSS not found

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#6091]
nopCommerce version: nopCommerce 4.5 RC

Steps to reproduce the problem: 
Give new css file reference in head view page and delete that file from physical folder and run application.
It will crash application.

Note: Minification should be disabled

**Comment by AndreiMaz** [comment]
@rajupaladiya Just don't delete the file. Why have you have that?

**Comment by rajupaladiya** [comment]
@AndreiMaz - suppose by mistake it was removed or somehow it missed on the server, in this case, store should not crash.

**Comment by rajupaladiya** [comment]
It is working fine with enable CSS minification

**Comment by glhays** [comment]
I consistently monitor the repository for my own website and future upgrades where an issue may essentially determine when I upgrade to a newer version. This so called issue doesn't seem to me as an issue of the software, but rather a let's see what happens if I remove a critical component from the site. By setting minification you have added back the component you intentionally removed. Just my two cents.


________________________________

**Comment by rajupaladiya** [comment]
strange (y)

**Comment by AndreiMaz** [comment]
It's not strange, it's by design. If you removed some file by mistake, just return it back. Otherwise, you'll see an error. Hence, you'll know about it. And  hence, you can fix it (by returning a file back)
