### ISSUE TITLE
PayPal Commerce plugin.  Next button is not displayed after payment

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#6132]
nopCommerce version: 4.40.4

> The next thing that is happening is that the redirect url (where the buyer gets sent after PayPal) is not going to the confirmation page. It is instead going back to the Payment page with the smart payment button. There is supposed to be a Next button on the page or the buyer is supposed to be redirected to the Confirmation page.
> 
> Your web developer needs to work with your shopping cart to fix the redirect page to go to the confirmation page. Most likely there is a theme or a setting that is stopping the redirection to the confirmation page.

Source: https://www.nopcommerce.com/boards/topic/91664/paypal-smart-buttons-plugin-not-working-in-nopcommerce-44 
https://www.nopcommerce.com/boards/topic/93366/missing-orders-after-paying-with-paypal

See also: #5813

**Comment by SelectSystemsInternational** [comment]
One problem is that the Payment is made in PaymentInfo step then after the return from Paypal 
Then the Customer needs to click Confirm Button to confirm the order. But if they dont then there is a payment with no order. 
I changed the flow in my version so that after the payment is made and the return from Paypal then the order is automatically created.
Also fixes this problem https://www.nopcommerce.com/en/boards/topic/93969/paypal-commerce-editing-order-before-confirm-but-after-payment

**Comment by RomanovM** [comment]
Fixed in a new implementation of the plugin, see https://github.com/nopSolutions/nopCommerce/commit/0d47801ef2108bf52812514f3e2e1edff3b23398
