### ISSUE TITLE
What does Yandex do in this software ?

### ISSUE THREAD

**Issue by cimpok** [nopSolutions/nopCommerce#6160]
Searching for the string 'yandex' (with 'match case' unchecked) results over 25000 (yes, 25 thousand!) matches in the source code.

I am not able and because of the sheer number not even trying to check every occurrence for its function in the code. I know yandex (Russian: Яндекс) is the Russian 'Google' being a search engine, media company, and many more. But, although the firm is registered in the Netherlands, the company founders and most of the team members, and presumably their servers or at least part of them are located in Putin's Russia.

Could you please clarify what yandex does in this software, why it is so intensively intertwined in the code.

With Yandex either directly or thru their crawlers with the help of these features in the software have better access to our e-commerce data (statistics, products, prices, maybe also visitors personal data, etc., at least their yandex ids, or cookies) knowing that this data can land on Russian soil, and reading that yandex some years ago already  'reached an agreement with FSB (formerly KGB) where the company would provide the required data' is at least worrying.

Yandex is definitely an unwanted 'feature' that my customers (shop operators and their customers) would not welcome in the context in this war* started by Russia. How can we get rid of yandex completely making sure our shops are not reporting to Moscow?

_*skip this word if reading from Russia, spreading it in Russia is a crime, punishable with up to 15 years in prison_

**Comment by skoshelev** [comment]
it is not entirely clear how you did the search that you found so many inclusions of the word yandex in the source codes, here is a screen from visual studio with a search throughout the project. 

![image](https://user-images.githubusercontent.com/16875599/156775643-ebaf0a89-92d8-4004-99fe-4df31a755d75.png)

Indeed, one can easily notice that there are quite a lot of references. However, you should pay attention to where exactly they meet. Since Yandex is a search engine, it has a search robot, here are 46 lines in the browscap.crawlersonly.xml file. The rest of the references are fonts and styles.

As you can see for yourself, we are not integrated with Yandex in any way.
