### ISSUE TITLE
Filter products by "Published" field in admin popup views 

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#6201]
nopCommerce version: 4.50

>we should add possibility to show only published products when we add products to category. Now we can only choose product single / producer  / category... there should be also "published / unpublished"

Source: https://www.nopcommerce.com/boards/topic/93869/add-products-to-category-give-possibility-to-show-only-published

At now we have _"published"_ filter on the main product list page, we could add the same for popup views (e.g. `AddProductToCategory`, `AddProductToDiscount`, etc).

Also, we could make a generic search model for all these views and then add new filters in a single place.

**Comment by nextfool** [comment]
IMHO, the products list page or even better all list pages in admin areas should be improved by adding features like sorting, filtering by fields, showing or hiding fields etc. All the sorting/filtering criteria should be appended to the url and sent by a get request instead of post. So we can always bookmark some query for daily use.

**Comment by glhays** [comment]
Here, here agreed


________________________________

**Comment by JeevaRP-SDE** [comment]
Suggestions  Please?

**Comment by RomanovM** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization.

**Comment by JeevaRP-SDE** [comment]
OK thank you for REPLY
