### ISSUE TITLE
GetCatalogRoot doesn't contains sup-categories 

### ISSUE THREAD

**Issue by Alaa-Eddin-jo** [nopSolutions/nopCommerce#6345]
Hi,
This endpoint dose not contains sup Categories  
/api-frontend/Catalog/GetCatalogRoot

I think the problem in GetCategorySimpleModel at CatalogModelFactory
it doesn't contain SubCategories

var model = new CategorySimpleModel
            {
                Id = int.Parse(elem.XPathSelectElement("Id").Value),
                Name = elem.XPathSelectElement("Name").Value,
                SeName = elem.XPathSelectElement("SeName").Value,

                NumberOfProducts = !string.IsNullOrEmpty(elem.XPathSelectElement("NumberOfProducts").Value)
                    ? int.Parse(elem.XPathSelectElement("NumberOfProducts").Value)
                    : (int?)null,

                IncludeInTopMenu = bool.Parse(elem.XPathSelectElement("IncludeInTopMenu").Value),
                HaveSubCategories = bool.Parse(elem.XPathSelectElement("HaveSubCategories").Value),
                Route = urlHelper.RouteUrl("Category", new { SeName = elem.XPathSelectElement("SeName").Value })
            };

**Comment by skoshelev** [comment]
Hi @Alaa-Eddin-jo. This is not a bug or a problem, this is by design. We do not pass the entire directory structure at once in this method in order to reduce the waiting time. if you need to load child categories you can use the GetCatalogSubCategories method. The CategorySimpleModel object contains the HaveSubCategories property and you can rely on it when determining whether there is a need to load data about child categories
