### ISSUE TITLE
Update EasyPost package to 4.0

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#6424]
nopCommerce version: develop

**Comment by RomanovM** [comment]
@Justintime50 We have updated EasyPost package to the latest version. Since there were breaking changes from 3.0 to 4.0, could you please look at [this commit](https://github.com/nopSolutions/nopCommerce/commit/c6901df4217280d05ca4d534737b289155937ba4)?

**Comment by Justintime50** [comment]
@nwithan8 is our resident C# expert, I'll ping him to take a look here!

**Comment by nwithan8** [comment]
On first pass, everything looks good to me. All the properties are titled-cased rather than snake-cased.

Going beyond this commit, looks like you guys correctly accounted for all the EasyPost services coming from a client instance (e.g. https://github.com/nopSolutions/nopCommerce/blob/c6901df4217280d05ca4d534737b289155937ba4/src/Plugins/Nop.Plugin.Shipping.EasyPost/Services/EasyPostService.cs#L416)

Sorry you had to make custom extensions to compare a dictionary of parameters to an existing EasyPostObject (e.g. Parcel, Shipment). We have a first-party way of comparing two EasyPostObjects, but especially since we removed the first-party ToDictionary function, there's no built-in way to do that via our library. Perhaps we can reintroduce that.

**Comment by RomanovM** [comment]
@nwithan8 
>Perhaps we can reintroduce that.

Yes, that would be great.
Thanks for your help.

**Comment by nwithan8** [comment]
In the meantime, this might be useful to you. It's not an official EasyPost utility, just something I've been maintaining myself:
https://github.com/nwithan8/easypost-extensions-dotnet
