### ISSUE TITLE
Video add on display product list view page in preview

### ISSUE THREAD

**Issue by SagarKayastha** [nopSolutions/nopCommerce#6437]
nopCommerce version:  nopCommerce 4.60-beta

Steps to reproduce the problem: 
Step 1: Go to product edit page
Step 2: Go to Multimedia panel
Step 3:  Select Video tab
Step 4: Enter embed video URl and click on add product video button
Step5: Grid in display product list view page in preview field
![image](https://user-images.githubusercontent.com/82799708/206364333-746e2c12-c59e-4ba4-9d3e-a7a17bfe2db1.png)

**Comment by skoshelev** [comment]
Hi @SagarKayastha. I was able to repeat the situation you described, only by adding just a set of characters instead of the video URL, I don’t think that in a real site someone will add something like that. I added a number of checks, but even they do not guarantee that you will not insert any other URL instead of the video URL.

Closed #6437
