### ISSUE TITLE
jpg thumbs missing file extension

### ISSUE THREAD

**Issue by gkennedy1** [nopSolutions/nopCommerce#6564]
nopCommerce version: 4.6.0 (same on develop branch)

images with .jpg extension are being created in the thumbs folder without an extension
Introduced by this commit - https://github.com/nopSolutions/nopCommerce/commit/4600a5ca600f85d64e5fbcf339862a0498227006
Should be 
```
           lastPart = lastPart switch
            {
                "pjpeg" or "jpg" => "jpg",
                "jpeg" => "jpeg",
              ...
```

Steps to reproduce the problem: 
1) Upload a product with an image with .jpg file type
2) Browse to the product
3) Note the missing file type generated in the \thumbs folder. Also, the browser doesn't render the image

**Comment by skoshelev** [comment]
Hi, @gkennedy1. I do not quite understand how to repeat the problem, especially since according to [this resource](https://mimetype.io/all-types#image) there are only two mime types for jpeg images: image/jpeg and image/pjpeg.

I tried uploading images with .jpg extension for the product and have no problem, their mime type matches the standard image/jpeg

**Comment by gkennedy1** [comment]
That is strange. I was upgrading a 4.5 site and copied across all the existing images from the production site and any image that had a .JPG extension created an extensionless thumb file

**Comment by AndreiMaz** [comment]
@gkennedy1  Could you please share some of these files?

**Comment by skoshelev** [comment]
@gkennedy1 Could you share the MimeType for such images in your database in the Picture table

**Comment by gkennedy1** [comment]
![image](https://user-images.githubusercontent.com/1694515/216565234-63a567db-e2b7-4ec8-a3fd-ad00e2f43c49.png)

**Comment by skoshelev** [comment]
@gkennedy1 Yes, that's what I assumed. For some reason, you have the wrong mime type entered in the database, perhaps this is due to previous versions of nopCommerce, but I have not yet found where this could happen. In my opinion, the simplest and most correct solution is to replace the mime type in the database with the correct one (image/pjpeg) and delete the already created thumbs files

**Comment by gkennedy1** [comment]
Thanks @skoshelev, I will do that

**Comment by KelvinDavid-Wrk** [comment]
For future peeps who run into this issue and want a little more context. This info helped us understand why invalid mime-types worked on the old version but not the new. Our old version also had a bunch of `image/jpg` mime-types.

This "issue" was caused by the change of behavior in this commit d2f62140e1ec251e81a9d4ec421fccd0b286620b, where nop team tightened the validation around valid content-types.

Those running an older version of nop commerce wouldn't run into this issue as the original content-type fetch returned whatever was passed in if it was a unexpected type. New way just doesn't return a content-type when invalid which breaks old paths.

We followed the solution here and just updated the mime-types to what's expected in the database:
`image/jpg` >> `image/jpeg`
