### ISSUE TITLE
_migrationRunner.Up not working for sqlite 

### ISSUE THREAD

**Issue by suatsuphi** [nopSolutions/nopCommerce#6606]
Hi, 

could you add an example for _migrationRunner.Up in ApplyUpMigrations in TEST. Because there is a problem for sqlite... 
```cs
  public void ApplyUpMigrations(Assembly assembly,
            MigrationProcessType migrationProcessType = MigrationProcessType.Installation,
            bool commitVersionOnly = false)
        {
            _migrationRunner.MigrateUp(637200411689037680);

        }

```

so it is not working this section for SQLite
```cs
                //update nopCommerce core and db
                var migrationManager = engine.Resolve<IMigrationManager>();
                var assembly = Assembly.GetAssembly(typeof(ApplicationBuilderExtensions));
                migrationManager.ApplyUpMigrations(assembly, MigrationProcessType.Update);
```

**Comment by skoshelev** [comment]
Hi, @suatsuphi. Please post your questions on the [forums](https://www.nopcommerce.com/boards), we only use GitHub for suggestions and bug reports.

In your code, you must use the IMigrationRunner directly, because the TestMigrationManager that is registered with the test IoC only performs the specific migration that is needed solely to create the table structure.

As an example of usage _migrationRunner.Up method, you can look at the code of the GetUpMigrations and ApplyUpMigrations methods from the MigrationManager class
