### ISSUE TITLE
Clear Cache With Distributed Cache

### ISSUE THREAD

**Issue by AdiIndoSwiss** [nopSolutions/nopCommerce#6624]
nopCommerce version: 4.5.01

**Steps to reproduce the problem:** 
I tried already the solution mentioned in the link . 
https://github.com/nopSolutions/nopCommerce/issues/5593#issuecomment-1196267689

The website never loads properly.
Need quickly some working workaround.
regards,
Aditya

**Comment by AndreiMaz** [comment]
@AdiIndoSwiss Please provide a list of steps to reproduce the issue on the clean "develop" branch"

**Comment by sinanopcommerce** [comment]
The best solution using rabbitmq pub/sub pattern for synchronizing the cache (resourcestring, settings, category, discount) for all instances. nop already does this inside the application.  Just replace the in-application one with rabbitmq fanout. Same thing just for multiple instances rather than one instance.

Move, the customer, and shopping cart to distributed cache and others to the memory cache(Entities that are not updated very frequently). If you tried distributed cache for scalability, you can try this approach.

**Comment by skoshelev** [comment]
Hi, @AdiIndoSwiss. The essence of the problem is not clear, you say that you looked at ticket #5593. There is a linked commit in this ticket https://github.com/nopSolutions/nopCommerce/commit/5acbd99662a4dd052333261c68c91216493eabec which closes the issue with clearing the distributed cache. Please describe your problem in detail, and indicate if it is possible to reproduce it on version 4.60.2

**Comment by AdiIndoSwiss** [comment]
thks guys will try out the solutions. closing the issue for now. have a great day.
