### ISSUE TITLE
Add support for dimensions for attributes

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#663]
I'd like to add support for dimensions for attributes. Right now attributes support price and weight adjustments but not different dimensions.  This makes it hard to have as attributes different variations of the same product. Most probably if a product's weight is different also it's size is different.

It could become qute complex because we don't know how exactly attributes can change dimension. Should we just sum them to the main product dimensions? Cube method? Etc? 

Also see https://www.nopcommerce.com/boards/t/16762/suggestion-enhance-product-attributes-for-selling-by-dimensions.aspx#68691

**Comment by cableguyusa** [comment]
I agree with Mariannk.  I have a customer that does custom prints.  Each custom print has a limited run, and is available as just a print, or framed at various sizes.  He prints after the order is placed and wants to auto-calculate shipping, but doesn't want to accidentally sell over the specified amount of his intended run.  Since you have weight in there and size is almost as important when calculating shipping I vote for adding dimensions as an option to attributes

**Comment by jaxuk** [comment]
+ 1 for this.

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box because it's a too specific requirement
