### ISSUE TITLE
Tax value calculated pre-discount

### ISSUE THREAD

**Issue by andrenpt** [nopSolutions/nopCommerce#6649]
nopCommerce version: 4.6

Steps to reproduce the problem: 
1 - Create a Discount that is applied to Order Total. Example 10% off
2 - Add a product to the basket
3 - Apply the Discount/Voucher
4 - You will notice that the tax value displayed is before the discount was applied.
5 - This is wrong and will cause several Accounting problems.

Not really sure how something this important is still a problem but tougth in letting you guys know.

Thanks.

**Comment by AndreiMaz** [comment]
Also see https://github.com/nopSolutions/nopCommerce/issues/337

**Comment by RomanovM** [comment]
@andrenpt This is not a bug, this is by design.
Order total in nopCommerce is actually the amount to customer pay. It's not just a total of products and services, it's the total amount of the order, including the price of products, shipping rate, payment method fee, and all taxes. And that's the amount the discount of `AssignedToOrderTotal` type applies to.

If you need a pre-tax discount, you should use `AssignedToOrderSubTotal` type, in this case, the discount will be applied to the order subtotal (amount of product prices), and after that taxes are calculated. 
The same for shipping if it's taxable. Use `AssignedToShipping` type to apply the discount first and then taxes.

@AndreiMaz  Since users sometimes misunderstand `OrderTotal` and `OrderSubtotal` values, we could add a setting allowing assign a discount before or after taxes are applied to the order total. But it's redundant imho.

**Comment by andrenpt** [comment]
@RomanovM If I choose `AssignedToOrderSubTotal` the discount wont be applied to the shipping cost and then I will have to create another discount just for the Shipping. I disagree with you this looks really misleading and it's not standard practice on an ecommerce platform. Also if the order is then sent to an Accounting System like for example XERO this will create accounting problems.

**Comment by AndreiMaz** [comment]
@andrenpt As Maksim mentions it's by design - in this case you'll have to create two discounts. Many people wants "OrderTotal" discount to incude taxes

**Comment by AndreiMaz** [comment]
Also see https://www.nopcommerce.com/en/boards/topic/101432/when-prices-include-tax-fixed-discounts-assigned-to-subtotal-have-tax-applied-again
