### ISSUE TITLE
Profit Area Is Only Includes Order Sub Total

### ISSUE THREAD

**Issue by mbilalari** [nopSolutions/nopCommerce#6692]
nopCommerce version: 4.60.2

Steps to reproduce the problem: 

After refund an order which included additional fees, profit area is decreasing under 0.

1. Add some additional fees an order (In this example we have additional payment fee for credit card.)
2. After payment is done refund this order.
3. Profit area is not working by Order Total. It is only looking Order Sub Total.

![image](https://user-images.githubusercontent.com/45788337/235881472-d6f099c9-771b-4740-815f-038b554e22dd.png)

**Comment by RomanovM** [comment]
@mbilalari Calculations are correct here. Profit is `OrderTotal - ShippingRate - PaymentMethodFee - Taxes - OriginalCost - RefundedAmount`.
In your case, you made a full refund including a payment method additional fee, which payment providers usually don't return to you as a merchant, they only refund the customer. So, your profit for this order is negative.

**Comment by yusufsarman** [comment]
Actually, our developed payment plugin provides integration directly with the bank rather than payment providers. In our country, banks offer installment options and charge different rates of commission within the installment amount. For example, 5% for 3 installments, 7% for 4 installments, and so on. These commissions are deducted from the fee we send via our virtual POS. Therefore, we enable installment selection in the Payment Information section and calculate the commission according to the selected installment and add an additional fee to the order.

We appreciate the functionality that the payment plugin provides and are grateful for your support. While we understand that the requested feature is relatively small, we would prefer not to make changes to the core if possible. Would it be possible to add a configuration option that ensures a minimum profit value of zero, which would address our concern? Thank you for your assistance and understanding.

**Comment by AndreiMaz** [comment]
@yusufsarman Thanks a lot for details. But we'll leave it for customization
