### ISSUE TITLE
Selected attribute for "Page size" and "Order By" is not changed to the newly selected option from the dropdowns

### ISSUE THREAD

**Issue by toshko93** [nopSolutions/nopCommerce#6718]
nopCommerce version: 4.6 (from 4.4 up)

Steps to reproduce the problem: 

1. Go to any category page in the nopCommerce demo - https://demo.nopcommerce.com/camera-photo
2. Change the "Page size" or the "Order by" from the respective dropdown (the issue is present on both)
3. The "selected" attribute won't change as there is no "onchange" event to handle it like there is for the Grid/List view buttons (a "selected" class is used there instead of an attribute)

![image](https://github.com/nopSolutions/nopCommerce/assets/8720660/e49c3c20-5d18-4c79-8f68-d74cdeab24e5)

**Comment by danFbach** [comment]
The selected attribute is only used when you are rendering a new page, in order to tell the browser which option, if any is to be selected when the page is loaded. This attribute does not need to be, and is not, changed.
If you ran the `document.getElementById('products-pagesize').value` from your dev console, you will see it returns whatever you currently have have selected, regardless of which element has the `selected` attribute.
You would only change the selected attribute if the element itself were re-rendered which, in this case, it is not.

**Comment by RomanovM** [comment]
@danFbach Thanks for this clarification.
