### ISSUE TITLE
Uploading new image to FTP doesn't not update

### ISSUE THREAD

**Issue by untiedshoes** [nopSolutions/nopCommerce#6746]
nopCommerce version: 4.60.3

Steps to reproduce the problem: With 4.40.4, and using Azure Blob Storage, we could update product images by uploading a new image (same file name, so just overwriting) to www/images/ folder. This would then create the new thumbs, and push them to azure.

With 4.60.3, this isn't happening. If we upload a new product with new images via the admin, it's all good an works as you'd expect.

Even 'turning off' azure blob storage, so just using local storage for images, the product image doesn't get updated if we ftp a new image with the same file name.

Any ideas?

*update: The thumbnail shown in the admin products list gets updated, but the main product image doesn't.

Front end:
![Screen Shot 2023-06-28 at 14 39 20](https://github.com/nopSolutions/nopCommerce/assets/12123259/ea62630c-986a-4328-b33c-9bc37ea302d4)

Product List in the admin (showing the new image):
![Screen Shot 2023-06-28 at 14 39 27](https://github.com/nopSolutions/nopCommerce/assets/12123259/10248d2d-1953-4006-b640-83ad44d15024)

Product page in the admin:
![Screen Shot 2023-06-28 at 14 40 47](https://github.com/nopSolutions/nopCommerce/assets/12123259/308699a0-f1c5-4955-a05a-e4cea5e48581)

Source: https://www.nopcommerce.com/en/boards/topic/97475/4603-dropping-images-into-ftp-doesnt-update

**Comment by RomanovM** [comment]
@untiedshoes Since version 4.40, there were no significant changes in PictureService, only support for SVG was added.

Anyway, there is no need for this issue now, as uploading images in the admin area works as expected.
Post your question on [our forums](https://www.nopcommerce.com/boards), perhaps the community can help. And if it turns out that the problem is in project code, we'll reopen this issue.

**Comment by untiedshoes** [comment]
We have multiple stores (multi-stores), with thousands of products, and have always updated the product images this way, but since moving to 4.60.3 it doesn't work.

**Comment by untiedshoes** [comment]
There's defiantly a bug somewhere, but can't find it.

Making a change to the Product thumbnail image size (catalog) makes that image change to uploaded one, but making a change to Product detail image size keeps the original file.

**Comment by glhays** [comment]
@untiedshoes
In the PictureService of 4.40 method of UpdatePictureAsync the lines 970-972
`
  //delete old thumbs if a picture has been changed
            if (seoFilename != picture.SeoFilename)
                await DeletePictureThumbsAsync(picture);
`
Were changed in lines 993-994
`
//delete old thumbs if exists
            await DeletePictureThumbsAsync(picture);
`
Not sure if this may be your issue, I guess you can always try adding the comparison if back in and see if it is the issue. I use the admin as I do not deal with the numbers of images your referring to.

**Comment by untiedshoes** [comment]
@glhays @RomanovM  Thanks man, but as I thought, that didn't change anything.

Anyway, we've come back this morning, and 'some' of the images have changed overnight!?

Looking at the image below, the thumbs are all using the 'old' image, whereas the large image is using the 'new' image with a grey background. The new image was just dropped into the images folder 3 days ago, and has taken to this morning to change.

![Screen Shot 2023-06-29 at 10 30 57](https://github.com/nopSolutions/nopCommerce/assets/12123259/b7cd160b-b9ad-4375-a102-277675afc65f)

But, all of the images in the admin are still still using the 'old' image with the white background.
![Screen Shot 2023-06-29 at 10 35 43](https://github.com/nopSolutions/nopCommerce/assets/12123259/ecdb982b-6163-433b-a21c-8c3bbfba796c)

Thanks,
Craig

**Comment by Ajay7700** [comment]
It seems like you are facing an issue with image updates in your e-commerce platform when using Azure Blob Storage in different versions of your software. Troubleshooting this issue will require a systematic approach. Here are some steps you can follow to diagnose and potentially resolve the problem:

Check Your Configuration:

Ensure that your Azure Blob Storage configuration in your application is correctly set up for both versions (4.40.4 and 4.60.3).
Verify the connection strings, container settings, and permissions.
Update Logic Analysis:

Examine the update logic in your application's codebase between these two versions. Look for any changes in how images are processed or updated.
Logging and Debugging:

Enable comprehensive logging for image uploads and updates in your application to identify any errors or unexpected behavior.
Debug the image update process to pinpoint where it might be failing.
Cache Consideration:

Check if your application is caching images. Cached images might not reflect the changes immediately, so clearing the cache might be necessary for updates to appear.
Azure Blob Storage Changes:

Review any changes in the Azure Blob Storage service or SDK that could affect how images are updated. There may be new behavior or limitations.
File Overwrite Behavior:

In Azure Blob Storage, file overwrite might work differently depending on whether the file already exists. Ensure that you are explicitly handling overwriting in your code.
File Timestamps:

Verify whether the timestamps on the files are getting updated when you overwrite an image. This could indicate whether the update is occurring at the file level.
Caching Mechanism:

Examine if there are any changes in the caching mechanism in your application or on your server that might affect how images are displayed.
Database Updates:

Check if any database records are not being updated correctly when new images are uploaded.
Third-Party Libraries:

If your application uses third-party libraries or plugins for image processing, ensure that they are compatible with the newer version.
Version-Specific Documentation:

Refer to the documentation specific to version 4.60.3 of your e-commerce platform. It may contain information about any changes in image handling.
Community and Support Forums:

Visit the support forums or communities for your e-commerce platform to see if others have encountered similar issues and if there are any known workarounds or solutions.
Testing on a Clean Environment:

If possible, create a clean environment and test the image update functionality in both versions to isolate whether the issue is related to changes in the code or the environment.
Contacting Support:

If you are unable to resolve the issue after exhaustive troubleshooting, consider reaching out to the support team of your e-commerce platform for assistance.
Remember to document your findings during this process, and if necessary, consider rolling back to the previous version where the image update was working and comparing the configurations and code between the two versions to identify the root cause of the problem.
