### ISSUE TITLE
Assembly issue

### ISSUE THREAD

**Issue by ekjuanrejon** [nopSolutions/nopCommerce#6764]
nopCommerce version: 4.60.0

Steps to reproduce the problem: 

pulled lasted from master branch:

The 'RestSharp' assembly has collision, application loaded the 'RestSharp, Version=106.12.0.0, Culture=neutral, PublicKeyToken=598062e77f915f75' assembly, but the 'Shipping.EasyPost' plugin required the 'RestSharp, Version=106.4.2.0, Culture=neutral, PublicKeyToken=598062e77f915f75' assembly

**Comment by RomanovM** [comment]
There is no EasyPost plugin in 4.60 out of the box, so there are no conflicts. 
As for other plugins, the merchant needs to use them consistently, since the plugins cannot use different versions of libraries at the same time, this is a limitation of the platform infrastructure. In particular, `RestSharp 106.12.0.0` is used in SendinBlue plugin, so you need to use the same RestSharp version in these plugins or remove one of them.
See also #4834

**Comment by ekjuanrejon** [comment]
hmmm i just pull master and running it from my local environment
