### ISSUE TITLE
New assembly handling makes cross-referencing plugin DLLs hard to deploy

### ISSUE THREAD

**Issue by GaborFarkas** [nopSolutions/nopCommerce#6828]
nopCommerce version: 4.60

Steps to reproduce the problem: 
1. Create plugin A
2. Create plugin B
3. Reference plugin A from plugin B
4. Build plugin A
5. Build plugin B (separately, like in a CI/CD workflow)
6. Upload plugin A
7. Upload plugin B
8. NopCommerce fails on the DI process

I know this is a very edge-case scenario and does not affect most of the nopCommerce developer community, but the revised assembly handling in nopC 4.60 made our life a bit harder. We have a plugin setup, where our base plugin is extended by a second one with additional features we would not like to share with our clients and instead offer as an extra service hosted only by us.

The problem is, this new assembly handling mechanism treats two assemblies with the same content and version from different compilations as 2 different assemblies with the same name and kills the DI process.

Our current solution is to copy the DLL of the shared plugin DLL after an update from one plugin folder to the other. This works, but other than being a suboptimal solution, Windows treats our plugin code as a trojan virus when we do this update process manually, requiring us to disable the firewall before every update. Of course, this will be solved when we nail our automatic updater, but still, you should know about this.

**Comment by skoshelev** [comment]
Hi @GaborFarkas. I don’t quite understand what exactly the new mechanism is in 4.60, but in any case, it seems to me that your task can be solved by removing the common logic into a separate assembly (not a plugin) which is then linked to both plugins. Then plugin B does not have to inherit from plugin A. We implemented the same approach for our WEB API plugin, and it works fine. Moreover, probably, extended functionality can also be implemented with an additional library, and only plugin A should be left, which will be equipped with either a basic assembly or an extended one (but I’m not sure if this is right for you, because I don’t know what exactly are the differences in your plugins)

**Comment by jjcowo** [comment]
I am currently encountering the issue that @GaborFarkas explained. 
We are adding a reference Nop.Plugin.Misc.WebApi.Backend to our custom plugin so we can extend some functionality from the backend api.
