### ISSUE TITLE
RedisSynchronizedMemoryCache issues

### ISSUE THREAD

**Issue by ahmadkq** [nopSolutions/nopCommerce#6888]
nopCommerce version: *

Steps to reproduce the problem: 
I have reveiwed the code for RedisSynchronizedMemoryCache, and when you have more than one server (web farm), i found that:
1- When calling ClearCache from one of the servers, just that server will be cleared, other servers will not be notified.
2- When add, update or delete a specification attribute to a product from the product page, the cache from that server will be updated, other servers will not be notified to clear thier cache.
3- there are other like this

Is there any possible to fix this?

**Comment by skoshelev** [comment]
Hi @ahmadkq. RedisSynchronizedMemoryCache will only be added in version 4.70 and we have tested it to ensure it correctly handles adding and deleting keys (including full cleanup) in a distributed system. Are you actually using the version that is in development? If so, please describe in more detail your infrastructure and how you conduct testing.

**Comment by ahmadkq** [comment]
@skoshelev Hi, yes i am using the development code. I have 2 load balancer servers, when clearning cache from one server, it doesn't cleared from the other one. I tried to do a debug and found that second server didn't recevie a notification to clear its cache. I can see RedisSynchronizedMemoryCache class has no clearcasche so the subscribers will be notified. Is it possible to show me where do you handle this when you do full clear cache?

**Comment by skoshelev** [comment]
Hi @ahmadkq. I checked everything again and everything works as expected. At the moment when the SynchronizedMemoryCacheManager.Clear method is called (essentially the MemoryCacheManager.Clear method), and a signal is sent to the default implementation of IMemoryCache to cancel all keys (call _clearToken.Cancel()), which leads to a change in the state of objects in the cache that are processed by the RedisSynchronizedMemoryCache.OnEviction method. All events are sent in full.
I think you need to look at why your second server is not processing these events. By the way, have you tried cleaning on another server, does the first one receive events?

**Comment by skoshelev** [comment]
Can't reproduce

Closed #6888

**Comment by fendric** [comment]
@skoshelev We are experiencing the same thing.
If we have servers A, B and C in the farm, and server A gets the cache clear command, yes it will evict its keys. Servers B and C will receive notifications to evict their corresponding keys as well.
But if server A has keys 1, 2 and 3 and server B has keys 1,2, 4 and 5, and server C has keys 1,3,5 and 6, then you can see that caches for 4-6 will remain on servers B and C.
This is apparent when a marketing manager updates the prices for a product and when they refresh their browser, may land on a server with the updated price or a server that did not receive the updated price.
We see this every day.
If the manager updated the prices on server B and cleared cache on server A, which didn't have the key, the prices will not update.
Of course, this is random and we have no control on which server and admin lands on.

In Nop 4.2 when we were using the Redis cache with synchronization the prices would update. 
Since upgrading to 4.7 this new cache does not reflect the same price on all servers - just the ones that received the event.

The Clear cache command should send a signal to tell all servers to dump ALL their keys, not just the ones that are on the list from the server that issued the cache clear command.
