### ISSUE TITLE
Move back from "short time" caching to "per request" caching

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6893]
There's no any real need to cache many entities between HTTP requests, even for 3 minutes (a default value). For example, customers, mapping between customers and customer roles generic attributes. It doesn't make any sense and just "bloat" the memory.

Furthermore, after some testing we've found out that it could reduce usage of CPU and memory.

Further performance optimization is related to "long time" caching. There's no need cache in long term entities such as forum posts and topics, forum votes, private messages, queued emails, newsletter subscription. All of them should be cached in "short term" (so now only during the current HTTP request)

**Comment by skoshelev** [comment]
Closed #6893

**Comment by professor-k** [comment]
I kind of understand how this can save some miniscule amount of memory in expense of extra roundtrips to DB, i.e. extra network/CPU time. However, I completely fail to see how extra roundtrips to DB can save on CPU compared to in-memory hashtable lookup. Care to elaborate?

This "optimization" is arguable at least: on our (reasonably large) instance synthetic tests show something like 2x degradation of performance, and number of database roundtrips went up by order of magnitude. We envision that it's going to be slightly better in real-life conditions, but still way worse that it was with 4.60: performance degradation is naked eye observable on our test environment.

Or right, and you can't just plug regular in-memory cache instead of "per-request cache" to return to previous behavior, because interfaces are not compatible. I would expect someone making interface for every single class would know better.

This "improvement" is effectively blocking us from upgrade to 4.70.
