### ISSUE TITLE
Add more database indexes (performance)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6940]
nopCommerce version: 4.60.5

We can improve performance by adding more database indexes:
1. [Product].[Name]
2. [Forums_Topic].[Subject]

**Comment by curllog** [comment]
Hi @AndreiMaz  @skoshelev  i have this [pull request ](https://github.com/nopSolutions/nopCommerce/pull/6944)can you please review it ? thanks

**Comment by curllog** [comment]
@skoshelev  thanks for merge but i think we need to remove NonClustered() because it's sql server specefic [https://github.com/fluentmigrator/fluentmigrator/blob/b2158a93315968d3037d20de881a99333da9c942/src/FluentMigrator.Extensions.SqlServer/SqlServer/SqlServerExtensions.cs#L66](https://github.com/fluentmigrator/fluentmigrator/blob/b2158a93315968d3037d20de881a99333da9c942/src/FluentMigrator.Extensions.SqlServer/SqlServer/SqlServerExtensions.cs#L66) what do you think?
