### ISSUE TITLE
False positives about license violations

### ISSUE THREAD

**Issue by BryceBarbara** [nopSolutions/nopCommerce#6946]
nopCommerce version: 4.60.5

Steps to reproduce the problem: 🤷‍♂️

1. Does this system assume that nopCommerce is also the frontend and not just a backend?
2. How does the `https://www.nopcommerce.com/license-check?url={1}&version=4.60.5email={2}&language={3}` endpoint determine an issue has been found?
3. How do I disable the ability for nopCommerce to disable aspects of my site remotely?

**Comment by glhays** [comment]
I am bewildered by this erroneous issue.
Let's say we have been using Nop since version 2.60 and have made
multitudes of code changes across this time frame to present.  Never have
we encountered fraudent invasive coding practices you are inferring.
Please kindly tell all of us why you believe there are.

**Comment by BryceBarbara** [comment]
I'm referring specifically to this and its changes to the various admin pages:

https://github.com/nopSolutions/nopCommerce/commit/db1f6b98703278ec7997e17297ff67e9531f65e9
