### ISSUE TITLE
Uppercased constant identifiers in 4.70?

### ISSUE THREAD

**Issue by noptools** [nopSolutions/nopCommerce#6975]
nopCommerce version: 4.70
I see you've recently refactored to rename constants.  By most conventions, constants are named using PascalCase.  Why the change?

Examples:
public const string CustomerRegisteredStoreOwnerNotification = "NewCustomer.Notification";
->
public const string **CUSTOMER_REGISTERED_STORE_OWNER_NOTIFICATION** = "NewCustomer.Notification";

public static class AreaNames
    public const string Admin = "Admin";
    ->
    public const string **ADMIN** = "Admin";

**Comment by skoshelev** [comment]
Hi, @noptools. Since there are many code style conventions in the world, we are forced to choose something specific. So we have developed internal rules for ourselves, which you can [find in our documentation](https://docs.nopcommerce.com/en/developer/tutorials/coding-standards.html#naming-conventions). With the latest changes in the code, we standardized the constants in our code to our own rules.

Closed #6975
