### ISSUE TITLE
Add support for ETag

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#700]
Make it configurable. But first let's invistigate whether it's really required (and possible) to be done in nopCommerce. Shouldn't it be done in IIS, etc?

see http://stackoverflow.com/questions/6642815/create-etag-filter-in-asp-net-mvc

Looks like it's supported out of the box in ASP.NET Core. Let's invetigate - https://madskristensen.net/post/send-etag-headers-in-aspnet-core and https://gist.github.com/madskristensen/36357b1df9ddbfd123162cd4201124c4

Furthermore, some services already support eTags. For example, https://support.cloudflare.com/hc/en-us/articles/218505467-Does-Cloudflare-support-ETag-headers-

Another question is whether we really need it (see comments in the article by madskristensen)

**Comment by AndreiMaz** [comment]
After some investigation we've found that:
1. Static resources already use ETAG. They are required often (for almost each page request), so it's good
2. There's no need to implement it for dynamic resources (HTML pages) because such pages are not really visited so ofter by the same customer. There are even no much websites (really not much) that use ETAG for dynamic content. Furthermore, it requires additional server resources to calculate hash for each page. And furthermore, you can always use free third-party services that can do it for you (e.g. CloudFlare)
