### ISSUE TITLE
Input box for order number on admin dashboard to go directly to order

### ISSUE THREAD

**Issue by nealculiner** [nopSolutions/nopCommerce#7028]
I'm using 4.60.5 having just switched from another ecomm platform. One nice feature they had on the prior platform was on the admin dashboard an input box to input an order number that takes me right to the desired order. Right now I have to click into sales, orders, and input the order number. This can be made simpler and faster to lookup an order for a customer inquiry.

**Comment by danFbach** [comment]
I have also thought about this feature too.
My thought was to make the search box used to search the menu also search order numbers, customers (by email or name.) 
I know my customer service reps would LOVE a feature like this.
And frankly - using the search to search the menu is hardly a useful feature, as the search constraints are too tight. 
If the menu items could have search synonyms, it might be more useful...like if one wrote "Email" in the search box, Templates, Message Queue, and other email related items would show, instead of only the "Email Accounts - Configuration."

**Comment by nealculiner** [comment]
Good idea @danFbach 

I think order number and customer email are both good to have on the dashboard, at least. I'm either going to lookup an order or customer typically.

**Comment by AndreiMaz** [comment]
Thanks a lot for suggestion. But we do not plan to implement this functionality out of the box and leave it for customization

**Comment by danFbach** [comment]
> Good idea @danFbach 
> 
> I think order number and customer email are both good to have on the dashboard, at least. I'm either going to lookup an order or customer typically.

let's build a plugin. email me at dan@fbach.us

**Comment by danFbach** [comment]
@nealculiner 
I built it. I was gonna sell it but, whatever. You can search order number, customer email/name, products by sku/name.
you can fork it for a different nop version if you need it. it's built for 4.60
after install you'll need to enable the widget so the js and css get injected.
[https://github.com/danFbach/dfdev.Plugin.Widgets.AdvancedAdminSearch](https://github.com/danFbach/dfdev.Plugin.Widgets.AdvancedAdminSearch)

**Comment by nealculiner** [comment]
Thanks @danFbach - will take a look.
