### ISSUE TITLE
Product list initial call never completes

### ISSUE THREAD

**Issue by biggik** [nopSolutions/nopCommerce#7081]
nopCommerce version: 4.60.6

Further description:
I have a product catalog with 7037 products (3092 active/non-deleted)
Note this issue is not in 4.60.5, at least I cannot reproduce it on  my test system, running on the same server as the main site.

Steps to reproduce the problem:
Simple, go to Administration, Catalog, Products. This gear in top right corner is turning and the query never finishes (I waited up to 15 minutes!). I debugged the issue and saw that a huge number of tasks is started (don't have an exact number, but in one Debug->Break the task list have ~2500 entries)

Steps I took to analyze the issue:
I deduced that the issue was in PrepareToGridAsync (in method PrepareProductListModelAsync in ProductModelFactory line ~795)

I started to remove all the async calls and set some default values:
                    productModel.SeName = "n/a";
                    (productModel.PictureThumbnailUrl, _) = ("images\\default-avatar.jpg", (string)null);
                    productModel.ProductTypeName = ProductType.SimpleProduct.ToString();
                    if (product.ProductType == ProductType.SimpleProduct && product.ManageInventoryMethod == ManageInventoryMethod.ManageStock)
                    {
                        productModel.StockQuantityStr = "42";
                    }

and then, one at a time, I reset to original code, and it is the following line that is causing the issue  
                    (productModel.PictureThumbnailUrl, _) = await _pictureService.GetPictureUrlAsync(defaultProductPicture, 75);

If I limit the search, by entering an item name, and re-searching, then thumbnails are generated in the images\thumbs folder and the return is very quick. 40 to 100+ products tested.

So, any idea what could be going on here?
Or what else I could try?

**Comment by glhays** [comment]
Try posting to the community forums.


________________________________
From: Birgir Kristmannsson ***@***.***>
Sent: Sunday, February 18, 2024 2:22:11 PM
To: nopSolutions/nopCommerce ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nopSolutions/nopCommerce] Product list initial call never completes (Issue #7081)


nopCommerce version: 4.60.6

Further description:
I have a product catalog with 7037 products (3092 active/non-deleted)
Note this issue is not in 4.60.5, at least I cannot reproduce it on my test system, running on the same server as the main site.

Steps to reproduce the problem:
Simple, go to Administration, Catalog, Products. This gear in top right corner is turning and the query never finishes (I waited up to 15 minutes!). I debugged the issue and saw that a huge number of tasks is started (don't have an exact number, but in one Debug->Break the task list have ~2500 entries)

Steps I took to analyze the issue:
I deduced that the issue was in PrepareToGridAsync (in method PrepareProductListModelAsync in ProductModelFactory line ~795)

I started to remove all the async calls and set some default values:
productModel.SeName = "n/a";
(productModel.PictureThumbnailUrl, _) = ("images\default-avatar.jpg", (string)null);
productModel.ProductTypeName = ProductType.SimpleProduct.ToString();
if (product.ProductType == ProductType.SimpleProduct && product.ManageInventoryMethod == ManageInventoryMethod.ManageStock)
{
productModel.StockQuantityStr = "42";
}

and then, one at a time, I reset to original code, and it is the following line that is causing the issue
(productModel.PictureThumbnailUrl, _) = await _pictureService.GetPictureUrlAsync(defaultProductPicture, 75);

If I limit the search, by entering an item name, and re-searching, then thumbnails are generated in the images\thumbs folder and the return is very quick. 40 to 100+ products tested.

So, any idea what could be going on here?
Or what else I could try?

**Comment by AndreiMaz** [comment]
It works absolutly fine and fast by default.

glhays is right. Please post all questions on [our forums](https://nopcommerce.com/en/boards/).
