### ISSUE TITLE
Discount requirement

### ISSUE THREAD

**Issue by mhmd7776** [nopSolutions/nopCommerce#7178]
nopCommerce version: 4.70

Steps to reproduce the problem: 
Discount requirement does not save and display correctly.

**Comment by AndreiMaz** [comment]
@mhmd7776 What exactly discount requirement are you testing? It works fine on our demo website - https://admin-demo.nopcommerce.com/

**Comment by mhmd7776** [comment]
@AndreiMaz
I check the problem further.
The discount requirement is saved correctly, but it is not displayed because it's cached.
We have to clear the cache manually every time

**Comment by danFbach** [comment]
Do you have prices cached in Catalog Settings?
![image](https://github.com/nopSolutions/nopCommerce/assets/17554977/e616023c-1f5c-47be-a7e0-e68544df773c)

I can confirm that having this enabled with Customer Role based discount rules that the prices become inaccurate. As stated in the hint - "Check to cache product prices. It can significantly improve performance. But you not should enable it if you use some complex discounts, discount requirement rules, or coupon codes." @AndreiMaz (this text should probably be rewritten as it contains typos.) maybe to "Check to cache product prices. It can significantly improve performance, but you should not enable it if you use some complex discounts, discount requirement rules, or coupon codes."

I personally live with the occasionally wrong prices because my site becomes really slow with it disabled and then have my Cache clearing task set to run hourly to try and mitigate it better. 
I have many compounding factors. Lots of grouped products, so when a category page is loaded, it is loading sometimes 200+ product prices to get the grouped product "From" price. 

I started refactoring the Pricing cache service so that the cache key included any applied discounts ids, and if someone has a coupon applied to their cart then just ignore the cache and load prices fresh, but never finished the work.

**Comment by skoshelev** [comment]
Hi @mhmd7776. By default, the discount edit page does not apply any caching to requirements. I can't reproduce the problem either locally or on the demo site. Perhaps you have some kind of plugin that changes the caching behavior or have made some custom edits to the code
