### ISSUE TITLE
View await eventPublisher.PublishAsync

### ISSUE THREAD

**Issue by abodehq** [nopSolutions/nopCommerce#7261]
nopCommerce version: 

Steps to reproduce the problem: 

if facebook pixel plugin enabled and its used conversion api and for some reason there was an error in facebook pixel api then the page will stuck on load untill the exception occure.

why in nopcommerce in view await eventPublisher.PublishAsync like in _root.head chtml
why not simply remove the await call so if any error occured this will not affect the load time
eventPublisher.PublishAsync(new PageRenderingEvent(NopHtml));

your response i really appreciated.

**Comment by skoshelev** [comment]
Hi @abodehq. 

We have two reasons for this:
1. Calling the PublishAsync method without waiting for it to complete may lead to unstable operation of this code since Microsoft does not guarantee that this code will be executed before the main process terminates.
2. With a high load on the site, this approach can, and most likely will, lead to exhaustion of the thread pool
