### ISSUE TITLE
Order Guid continue generating new on each request

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#7431]
https://github.com/nopSolutions/nopCommerce/blob/5579f5097a8d1e64248f96f073cf59a5737174a5/src/Libraries/Nop.Services/Payments/PaymentService.cs#L436

In above mention line, condition
`interval.TotalSeconds < _paymentSettings.RegenerateOrderGuidInterval`
should be 

`interval.TotalSeconds > _paymentSettings.RegenerateOrderGuidInterval`

Current condition creating new order guid on each request event configured interval time [value of setting - paymentSettings.RegenerateOrderGuidInterval] period is not passed

**Comment by skoshelev** [comment]
This code is not problematic because the interval is checked not to regenerate the order GUID but to extract it from the value stored in the session (previousPaymentRequest).
`
if (interval.TotalSeconds < _paymentSettings.RegenerateOrderGuidInterval)
            {
                processPaymentRequest.OrderGuid = previousPaymentRequest.OrderGuid;
                processPaymentRequest.OrderGuidGeneratedOnUtc = previousPaymentRequest.OrderGuidGeneratedOnUtc;
            }
`
That is why the check is inverted relative to your proposal. Please, See the [new test](https://github.com/nopSolutions/nopCommerce/commit/6f97c23f08606d2b0622c7f104a3e7628a076116) for more details.

**Comment by rajupaladiya** [comment]
@skoshelev - New guid creating during mobile app request with nopCommerce API plugin.
Generated guid during payment method and order guid after create order are different.

**Comment by RomanovM** [comment]
@rajupaladiya This is probably related to #7379

**Comment by rajupaladiya** [comment]
@RomanovM - Yes you right
