### ISSUE TITLE
Discount requirements selected value is not saved in discount edit page

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#7468]
nopCommerce version: 4.8

Steps to reproduce the problem: 

![image](https://github.com/user-attachments/assets/efff7b6c-d1ee-4a24-bad4-25f62be29c97)
![image](https://github.com/user-attachments/assets/46c02d0d-f44c-46b7-ab68-90a013fbad92)
![image](https://github.com/user-attachments/assets/bf040cc7-9fe6-4e86-b5d2-6d12719a8c4f)

**Comment by atulrungta** [comment]
@AndreiMaz actually this is because of Rocket loader, and a lot of JS code stops working when you enable Rocket loader in Cloudflare. Also, this was checked on admin demo of nopCommerce which is still on nopCommerce 4.70.

Additionally, we were able to generate this issue in nopCommerce 4.80 on our local test websites but that was due to some caching. We are not able to re-generate after we restarted the website locally on IIS.

You can still investigate if there is any issue with caching otherwise close this task since it wasn't discussed with me before posting here. Really sorry!
